### ISSUE TITLE
2.3.4 does not have static folder

### ISSUE THREAD

**Issue by danmontalvo** [yourlabs/django-autocomplete-light#1001]
It looks like `2.3.4` does not package `autocomplete_light/static`, which means that `autocomplete.js` is missing when browsers open a page using autocomplete.

https://pypi.python.org/pypi/django-autocomplete-light/2.3.4

Pypi archive for `2.3.4`:
https://pypi.python.org/packages/a4/20/7243565ba3404c54cc30de3189968f9b38aaf7935b1d16bb921995960e8b/django-autocomplete-light-2.3.4.tar.gz#md5=1b63d6e5ae67ed6a2ef9877ab4d665ce

**Comment by jpic** [comment]
Thanks for your report ! Is this fixed in 2.3.5 ?

**Comment by danmontalvo** [comment]
Yes, I see the static folder in 2.3.5.

**Comment by jpic** [comment]
Thanks, is your project working as expected after you upgrade to 2.3.5 ?

**Comment by danmontalvo** [comment]
Yes.

**Comment by jpic** [comment]
Thanks !
