### ISSUE TITLE
Version 3.3.0-rc6 actually doesn't contain fix for #959 

### ISSUE THREAD

**Issue by vshab** [yourlabs/django-autocomplete-light#1018]
Hello!

Seems like #1002 just isn't there. Tested on pip and from repository. Just download https://github.com/yourlabs/django-autocomplete-light/archive/3.3.0-rc6.zip and look at file `src/dal_select2/widgets.py`

**Comment by moorchegue** [comment]
Indeed, #959 is fixed on master, but not on rc6. At least not anymore, because I vaguely remember it was there, but not 100% sure.

**Comment by jpic** [comment]
Can you try with 3.3.0 please ?

**Comment by moorchegue** [comment]
3.3.0 works, thanks!

**Comment by vshab** [comment]
Now the fix is there! Thanks.
