### ISSUE TITLE
Django SELECT2_TRANSLATIONS does not exists in 1.11

### ISSUE THREAD

**Issue by todorvelichkov** [yourlabs/django-autocomplete-light#1029]
Commit 35b0046686cd883cf83f66f3cf2b2d77af520047 uses `SELECT2_TRANSLATIONS` from `django.contrib.admin.widgets` but they do not exists in [Django 1.11](https://github.com/django/django/blob/1.11.15/django/contrib/admin/widgets.py)

**Comment by jpic** [comment]
Oopsie, are you willing to contribute a patch to fix this ?

**Comment by hugorodgerbrown** [comment]
@jpic I've submitted a PR, but the CI build seems to be failing for everyone.

**Comment by raratiru** [comment]
I am registering to this post in order to be aware of the issue's footsteps. 

In the meantime, I downgraded to `django-autocomplete-light==3.2.10` that works fine.
