### ISSUE TITLE
django-autocomplete-light edit form

### ISSUE THREAD

**Issue by VagnerNico** [yourlabs/django-autocomplete-light#1045]
Good morning,

I use the widgets ModelSelect2Multiple and ModelSelect2 and in the view i used the get_selected_result_label and get_result_label to return html with image and text for get_result_label and only html image to get_selected_result_label and this work's fine!
But when i load a form with an instance for editing the entrance on database the widget don't load the declared html format, just simple text with de x mark to exclude, even if i remove and add the same item again the widget doesn't load with the html.

Best regards.

**Comment by jihoon796** [comment]
Just to check - did you set the ```data-html``` attribute on your widget? 

```python
class PersonForm(forms.ModelForm):
    class Meta:
        widgets = {
            'birth_country': autocomplete.ModelSelect2(
                url='country-autocomplete',
                attrs={'data-html': True}
            )
        }
```

**Comment by VagnerNico** [comment]
> Just to check - did you set the `data-html` attribute on your widget?
> 
> ```python
> class PersonForm(forms.ModelForm):
>     class Meta:
>         widgets = {
>             'birth_country': autocomplete.ModelSelect2(
>                 url='country-autocomplete',
>                 attrs={'data-html': True}
>             )
>         }
> ```

Yes i'm using.
I'm attaching the images with the behavior, in the first i don't have anything on the instance, but in the second i have.

Best regards,
![asdf1](https://user-images.githubusercontent.com/31249471/45627299-06e77f80-ba68-11e8-93e8-9124f6aa8313.png)
![asdf2](https://user-images.githubusercontent.com/31249471/45627300-06e77f80-ba68-11e8-9d1a-ac504daca2c5.png)

**Comment by jihoon796** [comment]
In your models.py, what is your ``` __str__ ``` method?

I think the only way to have it be an image is if you update your ```__str__``` method to return an image. I faced a similar problem a while back but couldn't solve it.

**Comment by VagnerNico** [comment]
> In your models.py, what is your `__str__` method?
> 
> I think the only way to have it be an image is if you update your `__str__` method to return an image. I faced a similar problem a while back but couldn't solve it.

Thank you, it's a good approach to solve, now i can see my image, not yet the best way because i have other issues to solve, maybe i will change the layout of the web application and things will work fine!

Best regards!
