### ISSUE TITLE
Getting issues with jQuery.noConflict call

### ISSUE THREAD

**Issue by leibowitz** [yourlabs/django-autocomplete-light#1046]
Since https://github.com/yourlabs/django-autocomplete-light/pull/1042 I am getting this error, and the widgets are not loading properly.
```
jquery.init.js:9 Uncaught TypeError: Cannot read property 'noConflict' of undefined
    at jquery.init.js:9
(anonymous) @ jquery.init.js:9
11:54:28.601 autocomplete.init.js:8 Uncaught TypeError: Cannot read property 'fn' of undefined
    at autocomplete.init.js:8
    at autocomplete.init.js:123
(anonymous) @ autocomplete.init.js:8
(anonymous) @ autocomplete.init.js:123
11:54:28.610 select2.js:5 Uncaught TypeError: $ is not a function
    at select2.js:5
    at select2.js:116
```

All the files referenced (`jquery.init.js`, `autocomplete.init.js`, `select2.js`) are the one provided by `django-autocomplete-light`, i.e.:
- autocomplete_light/jquery.init.js
- autocomplete_light/autocomplete.init.js
- autocomplete_light/select2.js

I believe this is caused by the fact that the `jQuery` variable used should be `django.jQuery`
https://docs.djangoproject.com/en/2.1/ref/contrib/admin/#contrib-admin-jquery

Note that `admin/js/jquery.init.js` is actually being called before `autocomplete_light/jquery.init.js` in my case, which could be the crux of the issue here (according to the [comments](https://github.com/yourlabs/django-autocomplete-light/blob/master/src/dal/static/autocomplete_light/jquery.init.js#L11-L14))

**Comment by coredumperror** [comment]
Ah, it looks like I may have missed an interaction between DAL's jquery.init.js and some other usage of django's jquery.init.js. Could you please describe in what way you're using DAL that's causing this error message to appear? For instance, are using DAL on a Django Admin form, or a custom form, or perhaps a CMS form (e.g. Wagtail)? And, if possible, could you check out the source of the page that's throwing this error, and find out which version(s) of jQuery are being loaded?

**Comment by leibowitz** [comment]
In standard admin forms, but I'm using other libraries as well.
The version of jquery is the default provided by django 2.0.8 (I believe that was jquery 2.2.3)

I will attempt at sending a patch once I get to it (in the coming days hopefully)

What I don't understand with https://github.com/coredumperror/django-autocomplete-light/blob/d9e552adc83bac8dbef8b4fd3e461b10713517a8/src/dal/static/autocomplete_light/jquery.init.js content is the purpose of doing all this

Wouldn't `yl.jQuery = django.jQuery;` be enough?
By re-introducing the dependency on `admin/js/jquery.init.js` to be loaded before `autocomplete_light/jquery.init.js` in my opinion that would be enough. But I'm probably missing something here?

**Comment by coredumperror** [comment]
Shoot, there was something nibbling at the back of my mind about that fix I wrote, and now you've exposed exactly what I did wrong. The change I made worked for me in the Wagtail admin, but will not work in the django admin, because it uses a different set of javascript includes. I had *thought* that things would work out, but clearly I was wrong.

I'm going to need to spend some time debugging this to find a universal solution. But I don't have think I'll have time today. For now, I'd suggest downgrading to DAL v3.3.0 until I figure out what the best path forward is.

**Comment by coredumperror** [comment]
OK, I'm as confident as I can be that the newest commit on master fixes this issue. It's a real doozey of complicated change, though. No wonder the original code had a comment about wishing there was a better way to do `jquery.init.js`.

**Comment by jpic** [comment]
Let's release a version that works with django admin again rather, you can stick to that one for wagtail.

I will make a release that passes our tox tests asap.

**Comment by leibowitz** [comment]
master is working fine for me 👍 feel free to close this issue

**Comment by jpic** [comment]
Also, tests in the admin are actually working fine for me, except one for the GFK but let someone fix it. It's a pain that travis has degraded free service so much it systematically fails running our tests for a while.
