### ISSUE TITLE
django-autocomplete-light 3.3.1 / 3.3.2 (latest) - having issue as $(...).select2 is not function

### ISSUE THREAD

**Issue by ramana-kk** [yourlabs/django-autocomplete-light#1047]
HI, 
I checked all possible combinations of jquery default django version, latest jquery verion ...etc. Also with all downloading combinations of first jquery, then autocomplete and again jquery. but nothing works.
can someone help me.

select2.js:66 Uncaught TypeError: $(...).select2 is not a function
    at HTMLSelectElement.<anonymous> (select2.js:66)
    at HTMLDocument.dispatch (jquery.js:4737)
    at HTMLDocument.elemData.handle (jquery.js:4549)
    at Object.trigger (jquery.js:7819)
    at HTMLSelectElement.<anonymous> (jquery.js:7903)
    at Function.each (jquery.js:365)
    at jQuery.fn.init.each (jquery.js:137)
    at jQuery.fn.init.trigger (jquery.js:7902)
    at HTMLSelectElement.initialize (autocomplete.init.js:82)
    at Function.each (jquery.js:365)

**Comment by ramana-kk** [comment]
Hi, It's a custom form. I didn't add 'admin/js/vendor/select2/select2.full.js' when I got this problem.
Now, I added this script before autocomplete scripts which worked for me.
I think you must update the documentation that with the following media along with autocomplete media.
'admin/js/vendor/select2/select2.full.js'
'admin/css/vendor/select2/select2.css'

**Comment by coredumperror** [comment]
The DAL widget should be supplying that script and that CSS for you automatically. I can't think of a reason that they would not have been included...

Could you please try removing the files you added manually, then load the page (and get the error), and then copy-paste your `<head>` element, or whatever part of your page includes the `<script>` tags, into this ticket? I'm honestly not sure how it's possible for those files to not be included there, so any clues you can provide would be helpful.

**Comment by yuriiz** [comment]
Not sure if I have to open new issue for this.
It also always happens with django-1.x and django-autocomplete-light-3.3.2 because dal_select2 references /static/admin/js/vendor/select2/select2.full.js which is not included in django-1.x. I think either django-1.x has to be supported as well or documentation have to be updated to explicitly mention that django-1.x is not supported at all (currently it says "1.x.x deprecated") and setup.py should include django>=2 for clarity.
