### ISSUE TITLE
Select2: incompatible with Django 1.11

### ISSUE THREAD

**Issue by Schnouki** [yourlabs/django-autocomplete-light#1058]
Version 3.3.2 of `dal_select2` depends on [`admin/css/vendor/select2/select2.css`](https://github.com/yourlabs/django-autocomplete-light/blob/3.3.2/src/dal_select2/widgets.py#L57). But this file doesn't exist in Django 1.11; in fact the whole `admin/css/vendor` folder is [missing](https://github.com/django/django/tree/1.11.16/django/contrib/admin/static/admin/css). It seems to be introduced in [Django 2.0](https://github.com/django/django/tree/2.0/django/contrib/admin/static/admin/css).

Would it be possible to fix that please?
Thanks!

**Comment by jpic** [comment]
Any effort put into making DAL compatible with old versions of Django and Python should better be put into porting your project to Django 2 and Python 3 (paying your tech debt).

That said, contributions are welcome. Please just try to not duplicate the issue.

**Comment by Schnouki** [comment]
FYI 1.11 is not just an old version of the Django, it's the current LTS.

**Comment by jpic** [comment]
@Schnouki being LTS doesn't make it recent. In March 2018, Ubuntu 16.04 was old, even if it was LTS until 18.04.

Contributions for python 2 or django 1.11 are welcome, but don't count on me because from my opinion it's old versions.

**Comment by raratiru** [comment]
>  pay your debt as early as possible instead of waiting the last minute, because as you wait, interest for your tech debt grow.

Cruel, indeed, but technically correct from all respects - especially for a free service of this level.

**Comment by jpic** [comment]
Please re-open if occurs again on 3.4.0 which re-enables python 2 support
