### ISSUE TITLE
DAL forward - ignoring read_only fields

### ISSUE THREAD

**Issue by FreakyTea** [yourlabs/django-autocomplete-light#1061]
Hi,

i today ran into an error, where i needed a read_only field as forwarded value in ModelSelect2 Widget. the 
`$.serializeArray()`
in jQuery ignores disabled fields. I bypassed this issue with overriding the forward.js and checking if a field is disabled - enable it, serialize the field and re-disable it.

I wondered that nobody tried to do this before.

Is there a possibility to get this native in DAL?

**Comment by durdenk** [comment]
@FreakyTea , Can you share your solution, enabling and disabling thing. I have the same issue.
Thanks.

**Comment by durdenk** [comment]
Ok, I got this working.
If someone encounters this problem, please use below script temporary. This cost me 30 minute to figure this out.



```
        var strategy = getForwardStrategy(field);
        if ($(field).is(':disabled')) {
            $(field).removeAttr('disabled');
            var serializedField = $(field).serializeArray();
            $(field).attr('disabled', 'disabled');
        }
        else {
            var serializedField = $(field).serializeArray();
        }

```

**Comment by jpic** [comment]
Can you propose a patch to recognize readonly fields by default ?

**Comment by FreakyTea** [comment]
Hi,

Sorry I should have included it right away :)

Got it this way:

`if (serializedField == false) {
            if ($(field).prop('disabled') == true) {
                $(field).prop('disabled', false);
                serializedField = $(field).serializeArray();
                $(field).prop('disabled', true);
            }
        }`

The proper way to set properties is .prop :)
