### ISSUE TITLE
Port fix for jQuery usage in af721ca to Django 1.11 compatible releases (> 3.2.10)

### ISSUE THREAD

**Issue by mandarg** [yourlabs/django-autocomplete-light#1070]
So af721ca54c75625d80b22007db70c93ca096b81c proved to be the definitive fix for "Select2: An instance of jQuery or a jQuery-compatible library was not found." type issues seen when using just `dal` and `dal_select2` with no other jQuery or Select2 modules. The issues seem to have been due to the fact that `$` was not being defined by either django-jquery or the `jquery.init.js` in this module, but the bundled `select2.full.js` expected `$` to be present. (I was halfway towards writing a fix before I found @coredumperror's much better one on master, so I'll let him weigh in in case I'm saying something wrong).

Anyway, the reason for this issue is – I'm still stuck on using Django 1.11, which is supported only by the 3.2.10 release, so I couldn't take advantage of the fix on master (which is only in 3.3 and upwards, which are [not supported for Django 1.11](https://github.com/yourlabs/django-autocomplete-light/pull/1064/files). 

So, to use it with Django 1.11, I changed some minor things in the patch and applied it to the 3.2.10 release [here](https://github.com/mandarg/django-autocomplete-light/commit/4bd04780061b36bc608b58dd07d40c0836a3eba6). Would you be open to cutting a new 3.2.11 release with that patch applied? (This will mean a new branch starting at the `3.2.10` tag). [Direct link to patch](https://github.com/mandarg/django-autocomplete-light/commit/4bd04780061b36bc608b58dd07d40c0836a3eba6.patch) that can be `git am`'d if it helps.

Let me know if you want any more work/input from me here, this is just to gauge the level of interest in a fix and 3.2.11 release. I'm fairly certain this also closes #824, and possibly #886 as well.

**Comment by jpic** [comment]
I don't mind merging your patch: I don't target 1.11 compat myself, but I have nothing against it.

**Comment by jpic** [comment]
You mean like maintaining a branch in Django 1.11 and another in Django 2.0 ? oh my :joy:

**Comment by mandarg** [comment]
> You mean like maintaining a branch in Django 1.11 and another in Django 2.0 ? oh my 😂

Er sorry, I'm getting a little confused here. Were you going to apply my patch directly, or do you want me to do something else, like create a merge request against some branch?

I see that there is a `dj111` branch, but it seems to be fairly behind the 3.2.10 release.

```
$ git log --oneline `git merge-base dj111 3.2.10`..3.2.10 | wc -l
      75
```

Let me know if any further action is needed from my side for getting the patch into a 3.2.11 release.

**Comment by jpic** [comment]
Thanks @mandarg , a pull request would be great.

**Comment by jpic** [comment]
Please re-open if occurs again on 3.4.0
