### ISSUE TITLE
Query returning object

### ISSUE THREAD

**Issue by KrunchMuffin** [yourlabs/django-autocomplete-light#1072]
Without going into detail right now, does anyone have an answer off the top of their head why I would get an object back instead of the actual data?

`{"results": [{"id": "154", "text": "Profile object (154)", "selected_text": "Profile object (154)"}], "pagination": {"more": false}}`

I can post more details if required. Just tired right now. 😫  🛌

**Comment by jpic** [comment]
I think that it shows the str representation of the object by default, you can change it https://django-autocomplete-light.readthedocs.io/en/master/tutorial.html#displaying-results-using-custom-html

**Comment by KrunchMuffin** [comment]
Ahh thanks! I assumed it would show strings by default.
I update the view class with these overrides.


    def get_result_label(self, item):
        return item.company_name

    def get_result_value(self, item):
        return item.profile_id

    def get_selected_result_label(self, item):
        return item.company_name

**Comment by davidshumway** [comment]
Not sure if this is in the docs, but based on this issue I was able to create a single autocomplete view class and reuse it multiple times on the same table, switching between model attributes based on an argument passed in view `.as_view`.

views.py
```python
class MetadataAutocomplete(autocomplete.Select2QuerySetView):
  view = None

  def __init__(self, *args, **kwargs):
    self.view = kwargs.get('view', None)
    
  def get_result_label(self, item):
    return getattr(item, self.view)

  def get_result_value(self, item):
    return item.strain_id

  def get_selected_result_label(self, item):
    return getattr(item, self.view)

  def get_queryset(self):
    if self.q:
      qs = Metadata.objects.filter(
        Q(cKingdom__istartswith = self.q)
      ).order_by(self.view).distinct(self.view)
    else:
      qs = Metadata.objects.all().order_by(self.view).distinct(self.view)
    return qs
```

And for example, in urls.py:
```python
  path('metadata_autocomplete_kingdom/', views.MetadataAutocomplete.as_view(view='cKingdom'), name='metadata_autocomplete_kingdom'),
  path('metadata_autocomplete_phylum/', views.MetadataAutocomplete.as_view(view='cPhylum'), name='metadata_autocomplete_phylum'),
```

And forms.py:
```python
class CollectionsForm(forms.ModelForm):
  cKingdom = forms.ModelChoiceField(
    queryset = Metadata.objects.all(),
    widget = autocomplete.ModelSelect2(url = 'chat:metadata_autocomplete_kingdom')
  )
  cPhylum = forms.ModelChoiceField(
    queryset = Metadata.objects.all(),
    widget = autocomplete.ModelSelect2(url = 'chat:metadata_autocomplete_phylum')
  )
  
  class Meta:
    model = Metadata
    fields = ['cKingdom', 'cPhylum']
```
