### ISSUE TITLE
Scripts loading inside form tag and at bottom

### ISSUE THREAD

**Issue by KrunchMuffin** [yourlabs/django-autocomplete-light#1073]
I have spent a couple hours trying to sort this out. Not sure what is going on.
I want them at the bottom obviously.
Also, I **don't want to include jQuery** since I already have it loaded for the site. Couldn't find an option for that.

**scripts inside form**
![image](https://user-images.githubusercontent.com/1037197/48669009-3d716300-eac8-11e8-833e-f0c63c9835d1.png)

**scripts at bottom with `{{ form.media }}`**
![image](https://user-images.githubusercontent.com/1037197/48669011-4feb9c80-eac8-11e8-9a57-685909ccb2cf.png)

**Form**

    class AccountSearchForm(forms.ModelForm):
        class Meta:
            model = Profile
            fields = ('profile_id', 'company_name',)
            widgets = {
                "company_name": autocomplete.ListSelect2(url='account-autocomplete', attrs={
                    # Set some placeholder
                    'data-placeholder': 'Search Accounts',
                    # Only trigger autocompletion after 3 characters have been typed
                    'data-minimum-input-length': 3,
                    }, )
                }

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.helper = FormHelper()
            self.helper.form_method = 'post'
            self.fields['company_name'].label = False

**Template**

    {% extends 'base/base.html' %}
    {% load crispy_forms_tags %}
    {% load static %}
    {% load django_bootstrap_breadcrumbs %}
    {% block breadcrumbs %}
        {{ block.super }}
        {% breadcrumb "Account List" "account-list" %}
    {% endblock %}
    {% load common_extras %}
    {% block content %}
        <div class="animated fadeIn">
            <div class="card">
                <div class="card-header">
                    <h3><i class="fa fa-building-o"></i> Schedule101
                        <span class="badge badge-pill badge-primary">{{ paginator.count }}</span>
                        {% if not request.GET.inactive %}
                            <span class="badge badge-success">Active</span>
                        {% endif %}
                        Accounts</h3>
                    {% crispy form %}
                    <div class="card-header-actions">
                        <a class="card-header-action btn" href="
                                {% url 'account-list' %}{% if not request.GET.inactive %}?inactive=1{% endif %}">
                            Show
                            {% if request.GET.inactive %}
                                Only Active
                            {% else %}
                                All
                            {% endif %}
                            Accounts
                        </a>
                    </div>
                </div>
                <div class="card-body">
                    <table class="table table-striped table-bordered datatable">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>City</th>
                            <th>State</th>
                            <th>Status</th>
                            <th>Registration date</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for account in accounts %}
                            <tr>
                                <td>{{ account.company_name }}</td>
                                <td>{{ account.company_city }}</td>
                                <td>{{ account.company_state_id }}</td>
                                <td>
                                    <span class="badge {{ account.active|statusbadge }}">{{ account.active|statustext }}</span>
                                </td>
                                <td>
                                    {{ account.dateadded|date }}
                                </td>
                                <td>
                                    <a class="btn btn-success" href="{% url 'account-detail' account.profile_id %}">
                                        <i class="fa fa-search-plus"></i>
                                    </a>
                                    <a class="btn btn-info" href="#">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <a class="btn btn-danger" href="#">
                                        <i class="fa fa-trash-o"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    {% include 'includes/paginate.html' %}
                </div>
            </div>
        </div>
    {% endblock %}
    {% block extra_js %}
        {{ form.media }}
        <script>
            $(document).ready(function () {
                let dt = $('.datatable');
                dt.DataTable();
                dt.attr('style', 'border-collapse: collapse !important');
            });
        </script>
    {% endblock %}

**View**

    class AccountAutocomplete(autocomplete.Select2QuerySetView):
        def get_queryset(self):
            if not self.request.user.is_authenticated:
                return Profile.objects.none()

            qs = Profile.objects.all()

            if self.q:
                qs = qs.filter(company_name__istartswith=self.q)

            return qs

        def get_result_label(self, item):
            return item.company_name

        def get_result_value(self, item):
            return item.profile_id

        def get_selected_result_label(self, item):
            return item.company_name

**Comment by jpic** [comment]
Did you try overriding the crispy forms template ?

**Comment by KrunchMuffin** [comment]
I just tried. It gets rid of one of the sets of scripts. But how do I prevent DAL from loading jquery? And does this mean it's not compatible with crispy? Or is there some voodoo I have to do?

Thanks @jpic 💯
