### ISSUE TITLE
Select widget loses focus after selection since v3.3.0

### ISSUE THREAD

**Issue by bhrutledge** [yourlabs/django-autocomplete-light#1077]
I've got a Django-admin time-entry app that relies on keyboard navigation for quick entry.

![screen shot 2018-11-28 at 10 14 07 am](https://user-images.githubusercontent.com/1326704/49161216-62e74380-f2f6-11e8-9d1c-e0e0ed984271.png)

In v3.3.0rc6, when I select a value from the "Activity" select (via Space or Enter), the select widget retains focus, making it easy to Tab to the "Edit" icon, then to the "Time" input in the next row. 

In v3.3.0 and up, when I select a value from the "Activity" select (via Space or Enter), the select widget loses focus, so the next time I hit Tab, the focus goes to the "Django administration" link at the top of the page.

**Comment by jpic** [comment]
Is this a regression in select2 or dal ?

**Comment by bhrutledge** [comment]
@jpic Good question. I didn't get that far in isolating it.

**Comment by dwasyl** [comment]
This is continuing to happen with 3.3.2.

**Comment by etiennepouliot** [comment]
This issue is related to select2 rather than this projet.

See this fix : https://github.com/select2/select2/commit/45ee7340e54259156b3b0ed38786f6a730810587

If you don't feel like digging, open select2.full.js, and below this line :
`    self.$selection.focus();`

And those lines :
`      window.setTimeout(function () {
        self.$selection.focus();
      }, 0)
`

**Comment by bhrutledge** [comment]
Thanks, @etiennepouliot. However, it looks to me like that change was released in select2 version 4.0.6-rc.1, which seems to be what the 3.3.2 release of this package is using.

However, it seems that in 3.3.0rc6, select2.full.js version 4.0.6-rc1 was being loaded from `/static/autocomplete_light/vendor/select2/dist/js/select2.full.js`. In 3.3.2, it's being loaded from`/static/admin/js/vendor/select2/select2.full.js` (i.e. the Django admin static files) which is version 4.0.3.

I haven't looked into when/why that change was made, but it suggests to me that this is still a potential issue with this project.

**Comment by jpic** [comment]
That's a pretty good point which would motivate going back to serving our
own version of select2 to follow up with upstream releases freely and more
frequently than Django.

**Comment by jpic** [comment]
Please re-open if occurs again on 3.4.0 (uses upstream select2 release now)
