### ISSUE TITLE
can not resolve name  - django version 2.1.3  

### ISSUE THREAD

**Issue by leventengin** [yourlabs/django-autocomplete-light#1078]
I get   "django.core.exceptions.FieldError: Cannot resolve keyword 'name' into field."  error  with        

if self.q:
            qs = qs.filter(name__istartswith=self.q)

django version 2.1.3 

same response  when used from url...  is it smth related to new url definitions ?

**Comment by jpic** [comment]
nope, maybe your model changed and does not have a name field anymore ?

**Comment by leventengin** [comment]
thxs. solved...
