### ISSUE TITLE
create_field for two objects

### ISSUE THREAD

**Issue by illQuo** [yourlabs/django-autocomplete-light#1084]
I have a model which requires `name` and `location`. When using create_field, I can only pass through `name`.

The following code only looks for the first index: 

`return self.get_queryset().get_or_create(
			**{self.create_field: text})[0]`

How can I override the `create_object()` method and extend the functionality? I've tried to inherit this class method but it is never called.

Any help is greatly appreciated.

**Comment by jpic** [comment]
Can you paste your class and url definition please ?

**Comment by jpic** [comment]
Yep, you can [override the create_object method](https://django-autocomplete-light.readthedocs.io/en/master/_modules/dal/views.html#BaseQuerySetView.create_object)
