### ISSUE TITLE
Forward without ForeignKey

### ISSUE THREAD

**Issue by onasipim** [yourlabs/django-autocomplete-light#1086]
I have following model:

```
class Payment(models.Model):
    COURSE = 1
    EVENT = 2
    GRADUATION = 3
    PAYMENT_TYPE = (
        (COURSE, 'Course'),
        (EVENT, 'Event'),
        (GRADUATION, 'Graduation'),
    )
    payment_type = models.IntegerField(
        choices=PAYMENT_TYPE,
        default=COURSE_BILLING,
    )
    payment_ref = models.IntegerField()
    amount_paid = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=2)
```

Every payment is of a specific type, stored in payment_type. The field payment_ref is an integer "referencing" the actual item which is paid for in form of an id in another table (Course, Event, Graduation). I chose this schema to prevent having a new column with referenced ids for every new payment type in Payment, as there can be more added in the future.

After saving an object in Django Admin the correct id for payment_ref is saved. But obviously when editing the object, Django/DAL doesn't know which model to use for this id, thus resulting in an empty Select2 list.

How is it possible to achieve the desired schema? Or would it be much wiser to just use a new column with every new payment type (and probably hide the unnecessary ones in the form with JS, depending on the payment type selection)

The view:
`class PaymentRefAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return Course.objects.none()

        payment_type = int(self.forwarded.get('payment_type', None))

        if payment_type == Payment.COURSE:
            qs = Course.objects.all()

            if self.q:
                qs = qs.filter(course__name__istartswith=self.q)
        elif payment_type == Payment.EVENT:
            pass
        elif payment_type == Payment.GRADUATION:
            pass

        return qs`

**Comment by jpic** [comment]
Please try with three backticks next time !
![2019-04-30-221359_1238x459_scrot](https://user-images.githubusercontent.com/94636/56990655-f10d7180-6b95-11e9-90e6-280f797ad4d8.png)

**Comment by jpic** [comment]
If you're going to have payment_type and payment_ref, why not add a [GenericForeignKey (level++ 4 u m8 !)](https://docs.djangoproject.com/en/2.2/ref/contrib/contenttypes/#generic-relations) to the mix ?

Then, you can follow [dal's gfk man](https://django-autocomplete-light.readthedocs.io/en/master/gfk.html) and make an autocomplete with django-queryset-sequence :D

**Comment by jpic** [comment]
Now if you want my personal advice in your place I would rather do a Product model and make Course, Event, Graduation etc inherit from that model, and make Payment.product relate to the Product model.

Then, you will have moar querying powas leveraging the basic FK from Payment to Product that the inheritance will allow you to travel through.

If needed, django-model-utils will provide the missing queryset methods to benefit most from this pattern.

Now that's the kind of counseling you would get for $2000/day if we weren't living in h4x0|2 worldz haha

Take care, you got my mobile number on my site listed at 24/7 Tech support if needed ;)
