### ISSUE TITLE
Allow overriding label_from_instance for dal_queryset_sequence.widgets.QuerySetSequenceSelectMixin

### ISSUE THREAD

**Issue by gtnx** [yourlabs/django-autocomplete-light#1087]
In django, it's possible to override the representation of an instance in the context of a choice field. It's done by overriding `label_from_instance` method:

https://github.com/django/django/blob/7c68cea7ee406fcb1b632e3a1a7f6f53e1423839/django/forms/models.py#L1208-L1214

I guess a similar mechanism could be used for `QuerySetSequenceSelectMixin` by changing [this line](https://github.com/yourlabs/django-autocomplete-light/blob/master/src/dal_queryset_sequence/widgets.py#L36) from

```
                ('%s-%s' % (ctype_pk, r.pk), six.text_type(r))
```

to 

```
                ('%s-%s' % (ctype_pk, r.pk), self.label_from_instance(r))
```

with `label_from_instance` which returns six.text_type by default

What do you think?

**Comment by jpic** [comment]
Salut Guillaume !

Yes I very much agree with what your statements they say.

Please thanks a lot for pull request.

If you don't put a test then please make a good joke in commit message. Note that if you want to add test then please keep it unit-level and don't bother about the other tests that are not passing, as i just started taking controle over this repo today, things are going to move during the gestation.

Thank you very much and you can has a beautiful day

:1st_place_medal:

**Comment by gtnx** [comment]
Hello la Poitou Charente,

Here's the royal [pull request](https://github.com/yourlabs/django-autocomplete-light/pull/1091).

**Comment by jpic** [comment]
Wow funny reply m8 so please reopen if moar and have a great day :sun_with_face:
