### ISSUE TITLE
Missing static file for select2 i18n - wrong path?

### ISSUE THREAD

**Issue by philgyford** [yourlabs/django-autocomplete-light#1108]
I'm using the `dal.autocomplete.TaggitSelect2()` widget in my app's admin and, after collecting static files and loading the "add" page for my Django model, the console shows that the file
`/static/vendor/select2/i18n/en.js` 404s.

I think the path should be `/static/vendor/select2/dist/i18n/en.js` - i.e. the version in use is missing the `dist` directory.

I'm *guessing* the error is in [this line](https://github.com/yourlabs/django-autocomplete-light/blob/32e50a6b4fbb08fdab5eaa5ee3d5acfcdb1da1c3/src/dal_select2/widgets.py#L78) in `dal_select2/widgets.py` ?

I'm using v3.4.0.

**Comment by philgyford** [comment]
Reverting to v3.3.5 fixed the error.

**Comment by jpic** [comment]
Thank you very much for your report !
Fixed in 3.4.1 release.
