### ISSUE TITLE
Select2 token separator can not be customized

### ISSUE THREAD

**Issue by filippo-20tab** [yourlabs/django-autocomplete-light#1113]
The `data-tags` attribute seems not to be mapped correctly in the select2 widget initialization as you can see [here](https://github.com/yourlabs/django-autocomplete-light/blob/e15864ef7eeb6d295705219cd305120bafb9e642/src/dal_select2/static/autocomplete_light/select2.js#L73). The ternary condition uses `data-tags` as condition but does not take it into account to set separators. Should it be turned into a split, in order to transform the data attribute string into an array as expected by select2?

**Comment by filippo-20tab** [comment]
Actually, I was probably misled by how `data-tags` is used [here](https://github.com/yourlabs/django-autocomplete-light/blob/e15864ef7eeb6d295705219cd305120bafb9e642/src/dal_select2_taggit/widgets.py#L15). Was it meant to be just a boolean? Then, customizing the separators could be turned into a future enhancement.

**Comment by jpic** [comment]
Agreed
