### ISSUE TITLE
When are create_object() and post() run?

### ISSUE THREAD

**Issue by mihalt** [yourlabs/django-autocomplete-light#1114]
Hi! I can't reproduce running of create_object() and post() methods in BaseQuerySetView class. Debugger don't work on it, when I create or change object in admin panel. 

Can you write more clearly, how can I run this methods and for what cases can I overwrite them?

**Comment by jpic** [comment]
Pretty good question ! I couldn't remember exactly, but searched for "post" in the repo and found that function: https://github.com/yourlabs/django-autocomplete-light/blob/b1d019d190ecd8d829583abb5289e79940562d51/src/dal_select2/static/autocomplete_light/select2.js#L89


Apparently, selecting an option with the create_id will do a post request that will trigger post() which will in turn call create_object()

Did you try following these steps ? https://django-autocomplete-light.readthedocs.io/en/master/tutorial.html#creation-of-new-choices-in-the-autocomplete-form
