### ISSUE TITLE
Compatibility issue with Django 3.0 due to django.utils.six

### ISSUE THREAD

**Issue by Mogost** [yourlabs/django-autocomplete-light#1115]
Django 3.0 scheduled for December removed Python 2 compatibility APIs used by django-autocomplete-light (django.utils.six, django.utils.encoding.python_2_unicode_compatible).

See https://docs.djangoproject.com/en/dev/releases/3.0/#removed-private-python-2-compatibility-apis
It would be wise to switch now to the direct use of six.

**Comment by jpic** [comment]
Agreed
