### ISSUE TITLE
Add compatibility with Django 3.0

### ISSUE THREAD

**Issue by hernancito** [yourlabs/django-autocomplete-light#1126]
In Django 3.0, according to the [release note](https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis):

> django.utils.six - Remove usage of this vendored library or switch to six

Just using ```python manage.py shell``` raises the error.

```bash
~/venv/lib/python3.7/site-packages/dal/views.py", line 10, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' 
```

**Comment by Mogost** [comment]
Allready fixed in #1121 
Upgrade to 3.5.0
