### ISSUE TITLE
Changelog says jquery was removed but it's still there

### ISSUE THREAD

**Issue by timthelion** [yourlabs/django-autocomplete-light#1130]
Changelog [says](https://github.com/yourlabs/django-autocomplete-light/blob/master/CHANGELOG#L4)

```
    - jquery.js has been **removed** from widget.media, this means that you are
      now responsible for ensuring that jquery is loaded in your page prior to
      displaying the form (form.media).
```

But jquery is still loaded automatically:

https://github.com/yourlabs/django-autocomplete-light/blob/bc83aecdde2328e683b278149ff7cdce3ebf4065/src/dal_select2/widgets.py#L87

**Comment by adnathanail** [comment]
Hi, is there any chance you could make a release with this change in? Cheers!

**Comment by jpic** [comment]
Released in 3.5.1

**Comment by adnathanail** [comment]
Brilliant thanks!

**Comment by jpic** [comment]
Keep up the great work yall!

Le mar. 4 févr. 2020 à 12:01, Alex Nathanail <notifications@github.com> a
écrit :
