### ISSUE TITLE
missing :Dependencies between autocompletes

### ISSUE THREAD

**Issue by AWSBarker** [yourlabs/django-autocomplete-light#1150]
I'm trying to learn DAL. I'm trying to find a way to link autocomplete fields between two models outside admin and I'm having to refer to older documentation from ver 2 that seems to be missing in ver 3. see

https://django-autocomplete-light.readthedocs.io/en/2.3.1/dependant.html?highlight=dependencies

Or am I missing something?

**Comment by jpic** [comment]
Here https://django-autocomplete-light.readthedocs.io/en/master/tutorial.html#filtering-results-based-on-the-value-of-other-fields-in-the-form
