### ISSUE TITLE
How to migrate from 3.5.1 to 3.8.1 

### ISSUE THREAD

**Issue by pvergain** [yourlabs/django-autocomplete-light#1184]
Hello,

I'm a Django developper and my skills with Javascript are very limited.

I'm using dal with the following Django statements

```python
from dal import autocomplete

class AchatServiceForm(forms.ModelForm):

    class Meta:
        model = AchatService
        fields = (
            "id",
            "etat_poste",
            "article",
            "description",
            "projet",
            "prestataire",
            "quantite",
            "prix_unitaire",
            "date_butoir",
            # la partie réponse
            "reponse",
        )
        widgets = {
            "article": autocomplete.ModelSelect2(
                url="articles:api_get_articles",
                attrs={
                    # Set some placeholder
                    "data-placeholder": "Choisissez l'article",
                    # Only trigger autocompletion after n characters have been typed
                    "data-minimum-input-length": 1,
                },
            ),
            "projet": autocomplete.ModelSelect2(
                url="projets:api_get_projects_encours",
                attrs={
                    # Set some placeholder
                    "data-placeholder": "Choisissez le projet",
                    # Only trigger autocompletion after n characters have been typed
                    "data-minimum-input-length": 1,
               
```
In this [page](https://django-autocomplete-light.readthedocs.io/en/master/tutorial.html#overriding-javascript-code) you give a Javascript solution for this statement:
![image](https://user-images.githubusercontent.com/57228/95833259-a6f15f00-0d3b-11eb-949e-355ac536159f.png)

What is the Javascript solution for this statement ?

![image](https://user-images.githubusercontent.com/57228/95833458-f33c9f00-0d3b-11eb-9a16-5011c9270167.png)

Thank for your job !
Have a nice day

**Comment by jpic** [comment]
I do not think you have anything to change, but we had a JS problem with 3.8.0, can you try your code as-is with 3.8.1 release please ?

Sorry for the mistake

**Comment by pvergain** [comment]
Ok I will try tomorrow.

**Comment by jpic** [comment]
Thank you very much, sorry for the bad release, really hoping 3.8.1 release does fix at least 10 open tickets ;)

**Comment by pvergain** [comment]
Hello,

Sorry, I've tried the 3.8.1 release but the problem is not solved for me.
It seems that the events are not more attached to the DAL widget.

So for the moment I fix the 3.5.1 version in my Pipfile.

DAL 3.5.1
========

All the DAL events are attached to the widgets.

![image](https://user-images.githubusercontent.com/57228/95948608-23924500-0df1-11eb-8977-34dae0a7e0cd.png)


DAL 3.8.1
=========

No more DAL events.

![image](https://user-images.githubusercontent.com/57228/95948631-36a51500-0df1-11eb-9eca-588a21bdf1d2.png)

**Comment by jpic** [comment]
In 3.8.1, DAL has a single JavaScript file, can you show your form template ? I'm affraid `{{ form.media }}` /might/ be missing.

**Comment by pvergain** [comment]
Hi !


It works  !
==========


Thank you very much :). I know I was misusing the DAL library. You were right: after including {{ form.media }}.
It works ! Thank you for your patience.

![image](https://user-images.githubusercontent.com/57228/96222248-355c1f80-0f8c-11eb-9ef0-ed9254d19680.png)

An other subject : for information: drag and drop with vanilla javascript and FormData
=====================================================================


This is not the subject but yesterday I've also learned a very interesting Web API : [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData). 

I Wanted to share this article https://www.smashingmagazine.com/2018/01/drag-drop-file-uploader-vanilla-js/ which may be interesting for the readers.

![image](https://user-images.githubusercontent.com/57228/96222893-5709d680-0f8d-11eb-8dab-fdf7594e16cf.png)

```
function uploadFile(file) {
  let url = 'YOUR URL HERE'
  let formData = new FormData()

  formData.append('file', file)

  fetch(url, {
    method: 'POST',
    body: formData
  })
  .then(() => { /* Done. Inform the user */ })
  .catch(() => { /* Error. Inform the user */ })
}
```
**My goal is to write vanilla javascript.**

Other links on the  FormData Web API:

- https://javascript.info/formdata
- https://blog.filestack.com/thoughts-and-knowledge/ajax-file-upload-formdata-examples/

I
Thank you for your patience.
Have a nice day !

**Comment by jpic** [comment]
Nice advertisement for FormData :joy: 

All CRUDLFA+ forms are sent with [FormData in a StimulusJS controller](https://yourlabs.io/oss/crudlfap/-/blob/master/js/controllers/form_controller.js) (I thought I used to have file upload code in there ?!) that we want to convert to Web Component like we already have from https://gitub.com/yourlabs/jquery-autocomplete-light to https://github.com/yourlabs/autocomplete-light

Then I think we'll have gone back the full circle from when Angular proposed to augment HTML at the time data-* attributes were new and cool ... but this time the browser has the core of modern JS component frameworks standard and built-in !

Many Python developers already generate HTML components in a modern way I mean without templates, it's the case for Iommi, Ryzom, Django-Material v2 branch, CRUDLFA+ ryzom branch ... Exciting times really !

Keep up the great work

:tophat:

**Comment by pvergain** [comment]
Thank you for these informations :) !
