### ISSUE TITLE
Demo link down

### ISSUE THREAD

**Issue by farridav** [yourlabs/django-autocomplete-light#1201]
The demo link on the readme appears to be down https://dal--jpic.repl.co/

Thanks :)

**Comment by Flightkick** [comment]
Two months later, this still seems to be ongoing. FYI

![afbeelding](https://user-images.githubusercontent.com/8693699/107442522-81ccfb80-6b37-11eb-99a1-c2f3841eaf5f.png)
![afbeelding](https://user-images.githubusercontent.com/8693699/107442569-98735280-6b37-11eb-83ad-5e774a7dad82.png)

**Comment by jpic** [comment]
We should remove that demo link, again. Every time I set this up on some free hosting it breaks after a little while.

It's easy to run the test_project locally, it's sure to work because all browser tests run on it.

**Comment by jpic** [comment]
We now have something running here: https://django-autocomplete-light-1.jpic.repl.co/

**Comment by Flightkick** [comment]
Thanks for the update, unfortunately the live demo doesn't run.  

sh: 1: demo.sh: not found

I may try the offline alternative later when I got some time to look at it further.

**Comment by jpic** [comment]
It worked for a moment :P

I don't have any ready-to-go solution without moving the repo to GitLab-CI
which we have been using for new projects, so the best is to remove the
demo link until someone suggest a free hosting service we can use.

**Comment by jpic** [comment]
Live demo fixed in 355db3785a0d58b660fee47e710998d9948ec88b to release soon
