### ISSUE TITLE
seek of closed file error

### ISSUE THREAD

**Issue by fragalcer** [yourlabs/django-autocomplete-light#1213]
Application breaks when trying to update the definition or image of a stewardship organisation.
For some reason this is only happening in development (localhost)
The only way to make it work is to update the SO profile image too.

![image](https://user-images.githubusercontent.com/31025299/107295952-8c9a7880-6ac4-11eb-8879-a34895724299.png)

**Comment by jpic** [comment]
Not related to DAL, not enough traceback nor code posted to tell any better, but it seems that some f.seek() call is tried after the file handler have been closed, is it outside of the `with open(path) as f:` ? Maybe try to upgrade your dependencies.
