### ISSUE TITLE
New Release any time soon?

### ISSUE THREAD

**Issue by grahamu** [yourlabs/django-autocomplete-light#1215]
Hi @jpic it seems DAL has some good new functionality since October 15, 2020, and it seems the documentation has been updated as well. Is there anything blocking a new PyPi release for these changes? Thanks!

**Comment by jpic** [comment]
There were some blockers indeed but I think they have been fixed in upstream releases, will check and release this weekend.

**Comment by grahamu** [comment]
Superb, thanks!

**Comment by jpic** [comment]
We had the release
