### ISSUE TITLE
DAL breaks Django 3.2 native autocomplete when both exist on one admin page

### ISSUE THREAD

**Issue by michael-sayapin** [yourlabs/django-autocomplete-light#1239]
Django 3.2 requires three more GET params for autocomplete, please refer to https://github.com/django/django/blob/3.2/django/contrib/admin/static/admin/js/autocomplete.js

When DAL is loading autocomplete_light.js, it's overriding this behavior and every request to /admin/autocomplete/ returns 403 error.

**Comment by jpic** [comment]
Fixed in 3.9.0-rc2 release
