### ISSUE TITLE
setting "theme" an select fields

### ISSUE THREAD

**Issue by kevin-olbrich** [yourlabs/django-autocomplete-light#1240]
Hi!

I like to use this:
https://www.npmjs.com/package/select2-bootstrap-5-theme

How can I set "theme" in the select fields?
When using this:
```
$("select").select2({
    theme: "bootstrap-5",
});
```
... I break the other options, the plugin alrady sets on the select.

How can I set this?

**Comment by kevin-olbrich** [comment]
`$.fn.select2.defaults.set("theme", "bootstrap-5");`

**Comment by sabyasachi** [comment]
> `$.fn.select2.defaults.set("theme", "bootstrap-5");
> `
> 

Did you get it to work with this?

**Comment by kevin-olbrich** [comment]
> > `$.fn.select2.defaults.set("theme", "bootstrap-5"); `
> 
> Did you get it to work with this?

Yes, works perfectly.
