### ISSUE TITLE
Replit demo broken 

### ISSUE THREAD

**Issue by saschahofmann** [yourlabs/django-autocomplete-light#1250]
The demo on https://dal--jpic.repl.co/ is in a permanent waking up state for me:

![image](https://user-images.githubusercontent.com/24508496/121026652-3d2c3680-c79e-11eb-83af-32141174f94f.png)

I am on macOS 11.3 using Chrome 90.0.4430.212

**Comment by jpic** [comment]
Same for me, anyway, fixed https://github.com/yourlabs/django-autocomplete-light/commit/824a20f985a6761a94692e820bbac9bb6e9e3029
