### ISSUE TITLE
[Django 4.0] the function lookup_needs_distinct  is renamed to lookup_spawns_duplicates()

### ISSUE THREAD

**Issue by pvergain** [yourlabs/django-autocomplete-light#1260]
Django 4.0
=========

- https://github.com/django/django/blob/main/docs/releases/4.0.txt

* The undocumented ``django.contrib.admin.utils.lookup_needs_distinct()``
  function is renamed to ``lookup_spawns_duplicates()``.

This function is used in https://github.com/yourlabs/django-autocomplete-light/blob/master/src/dal/views.py

**Comment by jpic** [comment]
Fix in master, thanks to @fraimondo

**Comment by jpic** [comment]
I believe this is fixed in 3.9.0rc2 release, please reopen if necessary.
