### ISSUE TITLE
Django 4.0 release has tripped up your demo project (url->path)

### ISSUE THREAD

**Issue by topiaruss** [yourlabs/django-autocomplete-light#1276]
Installing your demo project gives me...
  ImportError: cannot import name 'url' from 'django.conf.urls' 
when I...
  python manage.py migrate...

Reason for the error is that url is no longer defined in this way, since 4.0.

As a quick fix, I pinned Django in the requirements.txt under test_project, by adding
    Django==3.2.7
    
The alternative to url, path, has been available since Django 2.0, so it must be safe to switch to using path, so that both 3.x and 4.x will run properly

**Comment by jpic** [comment]
Thank you for your report, this should be fixed in 3.9.1 release, please reopen otherwise :tophat:
