### ISSUE TITLE
Missing changelog / release notes

### ISSUE THREAD

**Issue by gdvalderrama** [yourlabs/django-autocomplete-light#1295]
The latest changelog doesn't contain the latests 4 versions available through pip.
I've checked the changelog, releases, and tags and can't find this information.

**Comment by jpic** [comment]
Sorry about that, I forgot about this since the release shell script, will definitely add it

**Comment by alessio-b2c2** [comment]
any update on this?

**Comment by jpic** [comment]
Scripted CHANGELOG updates, added it to the release script, and updated the CHANGELOG for the last releases
