### ISSUE TITLE
Non-rc release forthcoming?

### ISSUE THREAD

**Issue by davidlougheed** [yourlabs/django-autocomplete-light#1351]
Hello,
Thanks for your work on this project. It's been a while since the last non-prerelease version; the convention with `rc` releases it that these are 'release candidates' and so not for production use. As such, is there any chance of a forthcoming production release with Django 4.2+ support on PyPI?

**Comment by lightswitch05** [comment]
I too am very interested in a non-rc version for 3.10 to get Django 4.2 support. Support for Django 3.2 ends April 1st. Any ideas if that is to be expected? I'm not interested in Django 5 yet.

**Comment by jpic** [comment]
Ok, considering https://github.com/bento-platform/katsu/pull/473/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R34 as confirmation that 3.11.0rc1 is fine, released 3.11.0, please reopen in case it's not good, meanwhile

Njoy :tophat:
