### ISSUE TITLE
get_absolute_update_url weird bug

### ISSUE THREAD

**Issue by sandroden** [yourlabs/django-autocomplete-light#172]
Hi,

when using choice_label in (Multi)ChoiceWidget yout get a custom formatting of the select item but you also get that same  html for the widget. I'd like to have different representation. Is there a simple/recommanded way to achieve this? i.e.: a choice_label for the select item and one for the widget item?

**Comment by jpic** [comment]
Couldn't reproduce, you're probably doing something wrong.

Would love to have a demo: http://django-autocomplete-light.readthedocs.org/en/stable-2.x.x/faq.html#how-to-ask-for-help
