### ISSUE TITLE
FieldError, cannot resolve keyword...

### ISSUE THREAD

**Issue by latsami** [yourlabs/django-autocomplete-light#177]
Hello,
I used the library in several apps in the same project, working just fine.
I have one problem though with an AutocompleteGenericBase class; I use it on a person application to link to different models (event, course, project, publication...). 

Those different models are accessible, but only the latest ones used; when I start to type in the search field, it looks for keyword "t" although I asked for "title". If I ask keyword "name" for example, it tries to look for keyword "n": 
"""
FieldError at /autocomplete/AutocompleteTaggableItems/

Cannot resolve keyword 't' into field. Choices are: attachment_set, audio_set, calendars, categories, children, description, exclusions, generators, id, image_set, language, level, lft, location, occurrences, oneliner, parent, relationship_set, rght, season_description, sessions_description, slug, title, tree_id, video_set
"""

Here's my class:
"""
class AutocompleteTaggableItems(autocomplete_light.AutocompleteGenericBase):
    choices = (
        Event.objects.all(),
        Course.objects.all(),
        Publication.objects.all(),
        Project.objects.all(),
    )
    search_fields = ("title",)
autocomplete_light.register(AutocompleteTaggableItems)
"""

Do you have an idea why it only takes the first letter of my string?

**Comment by kamal-el** [comment]
i use django-autocomplete-light with django-gm2m :
for applying the filter on all the querysets :

qs = qs.filter(EMP-FIRST-NAME__icontain=self.q).

my models have a different fields:

** EMP-FIRST-NAME for models Employees.

** FIRST-NAME for models Freecontracts.

** AG_NAME for models Freeagencies.

** FRE_FIRST_NAME for models Freelancers

how can i do for applying filter for all models (qs)??

** Views.py ** :

class RessourceAutocompleteView(Select2QuerySetSequenceView):

    def get_queryset(self):

        employees = Employees.objects.all()
        freecontracts = Frecontract.objects.filter(IS_ACTIVE=True)
        freeagencies = Freagencies.objects.filter(IS_ACTIVE=True)
        freelancers = Freelancers.objects.filter(IS_ACTIVE=True)

        if self.q:
            employees =   Employees.objects.filter(EMP_FIRST_NAME__icontains=self.q)
            freecontracts =    Frecontract.objects.filter(FIRST_NAME__icontains=self.q)
            freeagencies = Freagencies.objects.filter(AG_NAME__icontains=self.q)
            freelancers = Freelancers.objects.filter(FRE_FIRST_NAME__icontains=self.q)

            qs = QuerySetSequence(employees, freecontracts, freeagencies, freelancers)

        if self.q:
            # This would apply the filter on all the querysets
            # this tuple how can i do for apllying filter in all models qs??!!!
            qs = qs.filter(EMP_FIRST_NAME__icontains=self.q)

**Comment by kamal-el** [comment]
Can someone help me. please !!!
