### ISSUE TITLE
fixPosition does not really fix position with test_grappelli

### ISSUE THREAD

**Issue by mpasternak** [yourlabs/django-autocomplete-light#226]
Hi,

the dropdown list with options is displayed improperly attached to the first input on the page in some particular situation in test_grappelli.

To replicate:
1) run test_grappelli
2) go to /admin/inline_autocomplete/trip/add/
3) click "Add another trip_city" a few times, so you have about 5 or 6 inlines added
4) click on the last input field ("city")
5) type "Wa" to display "Warsaw" or "Ge" to display "Geneva" and see, that the dropdown list will appear at the FIRST input box, from the first inline row -- and not the last one. 

Currently, from what I saw, yourlabs.Autocomplete.prototype.fixPosition uses this.input.position() which is a relative position, and it should use absolute instead. 

I am working on a fix, I will update this issue as soon as I have it.

**Comment by jpic** [comment]
This breaks Django admin, see #265.

Reverting and re-opening.

**Comment by jpic** [comment]
We're back into absolute positioning which should work better - except that it's known to not work on IE so that's a bit of a pain LOL see #431
