### ISSUE TITLE
ModelChoiceField and admin readonly_fields

### ISSUE THREAD

**Issue by spookylukey** [yourlabs/django-autocomplete-light#235]
Using "autocomplete_light.ModelChoiceField" in a form, and using that form in the admin with readonly fields doesn't seem to work.

In particular, it returns a validation error for the readonly field - "this field is required". This doesn't happen otherwise. The error message doesn't actually show, because the field is displayed in readonly mode, you just get "Please correct the errors below".

There are no docs for running tests, at least that I could find, so I'm afraid I ran out of energy in trying to create a test case for this.

Tested in 2.0.0a9

**Comment by Hedde** [comment]
The example link is down, I have this exact issue using the following implementation (django 1.8);

    class PurchaseForm(forms.ModelForm):
        grower = autocomplete_light.ModelChoiceField('GrowerAutocomplete', label=_(u"Grower"))

        class Meta:
            exclude = tuple()
            model = Purchase


    class PurchaseAdmin(admin.ModelAdmin):
        readonly_fields = ('status', 'date_created', 'date_pushed',)

        form = PurchaseForm

        def get_readonly_fields(self, request, obj=None):
            if obj:
                return ('grower',) + super(PurchaseAdmin, self).get_readonly_fields(request, obj=obj)
            return super(PurchaseAdmin, self).get_readonly_fields(request, obj=obj)

**Comment by jpic** [comment]
The link is still up: http://django-autocomplete-light.readthedocs.org/en/v2/faq.html#how-to-ask-for-help

> How to report a bug effectively ?
> Read How to Report Bugs Effectively and open an issue on django-autocomplete-light’s issue tracker on GitHub.
>
> How to ask for help ?
> The best way to ask for help is:
>
> fork the repo,
> add a simple way to reproduce your problem in a new app of test_project, try to keep it minimal,
> open an issue on github and mention your fork.
> Really, it takes quite some time for me to clean pasted code and put up an example app it would be really cool if you could help me with that !
>
> If you don’t want to do the fork and the reproduce case, then you should better ask on StackOverflow and you might be lucky (just tag your question 
with django-autocomplete-light to ensure that I find it).

**Comment by Hedde** [comment]
It's not working for me: https://github.com/yourlabs/django-autocomplete-light/blob/readonly_fields/autocomplete_light/example_apps/readonly_autocomplete_field/admin.py
