### ISSUE TITLE
Use ModelAdmin.search_field as default for ModelComplete.search_fields

### ISSUE THREAD

**Issue by blueyed** [yourlabs/django-autocomplete-light#239]
While the following appears to work in the registry, I think it would be a nice default, instead of using DEFAULT_SEARCH_FIELDS (which may not be available):

    autocomplete_light.register(Model, search_fields=ModelAdmin.search_fields)

I don't know if that's easily possible, or another attempt has to be used in the registry to make it work - I just wanted to leave it here as an idea.

**Comment by jpic** [comment]
Closing in favor of PR #361
