### ISSUE TITLE
Make .choice-detail and .choice-update visible in deck and/or completion; currently hidden

### ISSUE THREAD

**Issue by blueyed** [yourlabs/django-autocomplete-light#240]
Is there a reason why these CSS classes are hidden by default?

Especially since they appear to be used only in `model_template/choice.html` template, and the documentation mentions this to be nicer, if absolute urls are configured.

Commit 4058190 has removed it and the changelog entry is in 6d7164e - it was renamed later.
The changelog says "This fixes the default model template, see in test_project: http://localhost:8000/admin/default_template_autocomplete/testmodel/add/".

Wouldn't it make sense to not hide these features provided in this special template?

**Comment by jpic** [comment]
If we want it visible in completion, we've got to prevent the choice select event sent when the user clicks the option.

**Comment by jpic** [comment]
old
