### ISSUE TITLE
Autocomplete widget not working for UpdateView

### ISSUE THREAD

**Issue by cebxan** [yourlabs/django-autocomplete-light#245]
Hi. I have a problem. I have two views, one for creating an object (using CreateView) and one for editing (using UpdateView). Both use the same form which inherits from autocomplete_light.ModelForm. In the create form, the autocomplete widgets work just fine, but when I want to modify the object they lose the autocomplete functionality. I'm attaching a screenshot showing the UpdateView.

![updateview_problem](https://f.cloud.github.com/assets/42040/2020048/361a89c2-882d-11e3-8e83-72c6fd64b93d.png)

This field is a ForeignKey to Area. As you can see, I don't have a button for deleting the previously selected object, nor adding a new one, and the input doesn't search for existing ones. Do I have to do something special to the UpdateView?

Thank you for your help.

**Comment by carpincho** [comment]
I know that this is closed. However, this actually solved my issue too. 
I also forgot to include the corresponding autocomplete static files 👍
