### ISSUE TITLE
BIG FAT WARNING: BC is going to happen on v2

### ISSUE THREAD

**Issue by jpic** [yourlabs/django-autocomplete-light#246]
Hi all,

I made some bad design decisions to keep a promise "make everything configurable in the autocomplete class".

For example, [allowing to change the template used by widgets.py from the autocomplete class](https://github.com/yourlabs/django-autocomplete-light/blob/c47f3c08a07da315dc77cd3fa52b4d2f7543610e/autocomplete_light/widgets.py#L168):

        template = getattr(autocomplete, 'widget_template',
                self.widget_template)

I ended up with many hooks like that, for example trying to allow [setting attributes like placeholder directly in the autocomplete](https://github.com/yourlabs/django-autocomplete-light/blob/c47f3c08a07da315dc77cd3fa52b4d2f7543610e/autocomplete_light/widgets.py#L173):

    self.attrs.update(getattr(self.autocomplete, 'attrs', {}))

I've indentified way to many hooks like that.

So, it'll be unified in v2 it'll look something like that:

    class YouAutocomplete(AutocompleteBase):
        widget_kwargs = {
            'attrs': {'placeholder': 'foo'},
        }
        field_kwargs = {
        }

So all the hooks will be removed in favor of just a hook in `WidgetBase.__init__()` and `FieldBase.__init__()`.

Sorry for the inconvenience and BC break this will cause.

Hopefully it's the only mistake I have identified in my last codereview that fixing will cause BC break.

Thanks for your understanding

Sincerely

James

**Comment by jpic** [comment]
We have proper upgrade docs, closing.

**Comment by mitchelljkotler** [comment]
> We have proper upgrade docs, closing.

Where are the upgrade docs?  All I can find is this blog post https://blog.yourlabs.org/posts/2016-03-05-django-autocomplete-light-v3-whats-going-on/ which does not actually contain any instructions on upgrading from v2 to v3.  (Yes I know I put off the migration for much too long)

**Comment by jpic** [comment]
@mitchelljkotler I think now follow the tutorial on an empty fresh project to find out how it works in v3, but basically v3 doesn't have a registry anymore nor a ModelFormMetaclass
