### ISSUE TITLE
Autocomplete_light and MongoDB

### ISSUE THREAD

**Issue by Manca** [yourlabs/django-autocomplete-light#248]
Hey there,

I was wondering if it's possible to connect autocomplete_light with the monogengine and its Documents? I have created few documents(models), but registering them with autocomplete doesn't work. I get this type of an error: "Document Profession may not be subclassed" which is expected, as they are not models but Documents.

I have tried loading all the necessary data into choices and then using that, but it doesn't get automatically updated when I add a new document.

Any ideas how to make this great plugin work with mongodb?

Thanks!

**Comment by zhiyajun11** [comment]
How could the following form work? It has nothing to do with ProfessionAutocomplete.
class RegisterForm(forms.Form):
profession = forms.CharField()
