### ISSUE TITLE
RemovedInDjango18Warning deprecation warnings

### ISSUE THREAD

**Issue by blueyed** [yourlabs/django-autocomplete-light#257]
I see two RemovedInDjango18Warning warnings (from Django 1.7alpha) with autocomplete-light:

 - [ ] …/autocomplete-light/autocomplete_light/forms.py:266: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form ModelForm needs updating
      attrs)
 - [ ] …/autocomplete-light/autocomplete_light/forms.py:449: RemovedInDjango18Warning: Calling modelform_factory without defining 'fields' or 'exclude' explicitly is deprecated
      return django_modelform_factory(model, **kwargs)

**Comment by linaskilius** [comment]
I'd love to see this patch released as well.  Hopefully I count as some added user demand :)

**Comment by jpic** [comment]
Fix released in 2.0.8.

It's going to be way cool when Django 1.8 LTS is released we'll be able to start removing legacy code.
