### ISSUE TITLE
New Feature Dynamic Autocompletion

### ISSUE THREAD

**Issue by agliottone** [yourlabs/django-autocomplete-light#266]
New Feature Dynamic Autocompletion

We have developed a way to add filters to the query of autocomplete that is explained in more details here:

   http://docs.thux.it/jmb.core/django/misc/autocompletion.html

it is useful when the choices are conditioned by other fields present in the page. In this case the url called also uses these info as in::

   /ticket/autocomplete/MyAutocomplete/?q=san&organization_id=1530&project_id=10

I created a class DynamicAutocompleteModelBase that extends from AutocompleteModelBase:
you can see here:
http://docs.thux.it/jmb.core/_modules/jmb/core/utils/autocomplete.html#DynamicAutocompleteModelBase

I used this not optimal code for give the filters option to javascript:

```python
self.autocomplete_js_attributes['filter_by'] = "||".join(
            ["%s|%s" % (key, val)  for key, val in self.filters.iteritems()])
```
because I could not give to a json. there a good way?

In javascript, I have override this:
```javascript
    yourlabs.Autocomplete.prototype.makeXhr = function () {
        if (this.filterBy) {
            filters = this.filterBy.split("||")
            autocomplete = this
            $(filters).each(function (k, v) {
                filter_key = v.split("|")[0]
                filter_value = $(v.split("|")[1]).val()
                if (filter_value && typeof (filter_value) == "object") filter_value = filter_value[0]
                if (filter_value) {
                    autocomplete.data[filter_key] = filter_value
                }
            })
        }
        this.xhr = $.ajax(this.url, {
            type: "GET",
            data: this.data,
            complete: $.proxy(this.fetchComplete, this)
        });
    }
```
Is there another solution to this problem I’m not aware of?
Can you consider to integrate this functionality into your package?

I think this is a feature that many would like to have! 
I take this opportunity to say hello and thank you for the great work you do

**Comment by jpic** [comment]
The current documented solution just requires a bit of straight forward userland javascript.

With the proposed solution, we'd have to maintain extra python and javascript in django-autocomplete-light. If someone wants to implement something like that then be sure that the dev team is open and that pull requests are welcome.

**Comment by nwaxiomatic** [comment]
Any chance this actually got merged?

**Comment by jpic** [comment]
While obviously I fail to see the advantage over doing the bit of glue in js: http://django-autocomplete-light.readthedocs.org/en/v2/dependant.html#autocompletes there is no pull request to merge so I'm not sure what you're talking about.

**Comment by nwaxiomatic** [comment]
I don't want to have to write a .js file for every admin page, so I'm working on a more generic solution along these lines.

**Comment by jpic** [comment]
I see, you needn't to make a .js file for every admin page. Anyway, we need
a PR with documentation, functional and unit tests.

**Comment by nwaxiomatic** [comment]
Yeah, I'm sure why this filtering business is such a hassle even for standard django fields.

How would you not need to write an extremely not DRY js file related to each admin from the dependency tutorial?

**Comment by jpic** [comment]
I think we could make a function from the example js ie
`autocomplete_add_filter()` and replace country by a variable ie. `from`
and city by another ie. `to` and just have one js function for starters.
Then maybe we could call that from Widget for each
`data-widget-add-filter-too` HTML attribute the widget has. Then you could
call maybe `register(CountryAutocomplete,
attrs={'data-widget-add-filter-to': 'id_region1, id_region2'}` or something
like that.

**Comment by nwaxiomatic** [comment]
it doesn't seem to be letting me autocomplete_js_attributes that aren't standard, or at least they don't show up in the fields

**Comment by nwaxiomatic** [comment]
ie, this does not att any attr to the field

```
class DynamicAutocompleteModelBase(autocomplete_light.AutocompleteModelBase):
    def __init__(self, *args, **kw):
        if not hasattr(self, 'autocomplete_js_attributes'):
            self.autocomplete_js_attributes = {}
        self.autocomplete_js_attributes['filter_by'] = "||".join(
            ["%s|%s" % (key, val)  for key, val in self.filters.iteritems()])
        super(DynamicAutocompleteModelBase, self).__init__(*args, **kw)
```

**Comment by jpic** [comment]
autocomplete_js_attributes is for django-autocomplete-light v1 series.

**Comment by nwaxiomatic** [comment]
I also tried modifying self.attrs, but also failed

**Comment by jpic** [comment]
I really wonder what you're doing :D​

**Comment by nwaxiomatic** [comment]
Yeah I think your suggesting will work. Personally I am going to just add it to the base model choice widget because these dependencies happen so often, especially for inlines depending on their parent.

**Comment by jpic** [comment]
Yeah I was thinking about inlines and my proposal doesn't work for that
indeed​, does it ? Well we'd have to try to find out if there would be an
elegant way. I don't know your project structure maybe making your base
widget is the best solution maybe it would be the same to add it to your
base autocomplete though.
