### ISSUE TITLE
Importing genericm2m unconditionally can trigger `relation "genericm2m_relatedobject" does not exist` error

### ISSUE THREAD

**Issue by blueyed** [yourlabs/django-autocomplete-light#275]
I have run into an issue, where genericm2m causes an error during migrations (https://github.com/coleifer/django-generic-m2m/issues/17).

It seems like this is triggered by django-autocomplete-light uncoditionally importing genericm2m (https://github.com/yourlabs/django-autocomplete-light/blob/v2/autocomplete_light/forms.py#L30).

Maybe autocomplete-light should check if genericm2m is installed (`if 'genericm2m' in settings.INSTALLED_APPS` and the proper method for Django 1.7+).

The same would apply to taggit then probably, too.

**Comment by jpic** [comment]
Is it still the case with master version ? thx B)

**Comment by jpic** [comment]
Fixed a while ago, thanks for your report !
