### ISSUE TITLE
v2: admin/base_site.html different from Django's: branding block missing / logout link not visible

### ISSUE THREAD

**Issue by blueyed** [yourlabs/django-autocomplete-light#281]
I have recently moved autocomplete_light before Django's admin in INSTALLED_APPS (when reading it in the documentation), and just noticed that this causes the "Logout" link to not be visible (white text on white background).

The reason appears to be that the branding block is empty and therefore the header does not get enough height.

Here is the diff between Django's 1.6 and autocomplete_light's v2 version of the file: https://gist.github.com/0e9e8671c40385920c6e

I've noticed this when temporarily disabling grappelli (which I use normally).

**Comment by jpic** [comment]
Let's keep it simple and not try to be smart about that: let the user include the JS.

We're not shipping a broken template anymore anyway.

Would you like to close this ?

**Comment by blueyed** [comment]
Closing, since `base_site.html` has been removed.

It's used for the test projects now only:
```
./test_grappelli/templates/admin/base_site.html
./test_project/templates/admin/base_site.html
```

Thanks!
