### ISSUE TITLE
Form label and placeholder

### ISSUE THREAD

**Issue by santocch** [yourlabs/django-autocomplete-light#283]
Hello, I successfully implemented (django-autocomplete-light==2.0.0a17) a global autocomplete form "a-la-facebook" as explained in the docs but there are few issues which I'd like to verify if this is the expected behavior...

First: I used two queries and added two separator in autocomplete.html as indicated in the doc (*Making a global navigation autocomplete* chapter):
```
<span class="separator">Artists</span>
... 
<span class="separator">Genres</span>
```
The problem is that the form get a new label (which was not there without the separators): **Artist Genres**... I don't want this label... Is there any option to hide it? If not, what is the best approach to hide it?

Second: After the autocomplete has been selected, the input is kept in the form and I need to use
```
            var choiceTag = choice.text();
            $("#navigation_autocomplete_tag").val("");
            $("#navigation_autocomplete_tag").attr("placeholder", choiceTag);
```
I would expect that at least the form is automatically cleared but this is not my case... What I did is the correct way or I'm missing something?

Third: is there any simple way to identify within the input.bind function if an artist or a genres has been chosen? My goal is to call two different function depending on the choice...

**Comment by jpic** [comment]
Answered, no feedback.
