### ISSUE TITLE
Select M2M via other model?

### ISSUE THREAD

**Issue by ricefield** [yourlabs/django-autocomplete-light#287]
I am trying to do the following, and after reading the documentation I am still not sure if it is possible with autocomplete-light (the closest thing is maybe http://django-autocomplete-light.readthedocs.org/en/latest/generic.html)

I have a M2M field which takes users, and autocomplete-light works great if you just type the usernames out one by one. **In my case, I want to also have the ability to add groups of users all at once.** For example, if a group of users are on a team, I want to be able to type in the team name, and then grab all the users associated to that team and throw them into the M2M field. 

Is this doable by customizing autocomplete-light or completely impossible?

**Comment by jpic** [comment]
Hello ! Any feedback ?

**Comment by jpic** [comment]
Answered, no feedback.
