### ISSUE TITLE
Automatically create new related objects from form data (free text)

### ISSUE THREAD

**Issue by blueyed** [yourlabs/django-autocomplete-light#290]
I would like to make autocomplete-light automatically create related objects if no match was selected/provided via the autocomplete input field, but it contains some value - i.e. the user typed something, but no match was found.

It seems like autocomplete_light could provide/setup a (field) widget, which could create the related object automatically and return its fk in `field.widget.value_from_datadict` (called via `_clean_fields`).

This would be optional of course, and some method / configuration would have to be provided to control how the object gets created.

E.g. for a simple model `Person` with only a field `name` (used in an admin inline form), it would create a new object with the given input as `name` and use its pk when saving the main form.

Is something in this regard possible already?
Where should this get hooked into?

I could imagine doing this via the form's `clean` method:

    class MyModelInline(admin.TabularInline):
        model = MyModel
        form = MyModelForm

    class MyModelForm(autocomplete_light.ModelForm):
    def clean(self):
        ...

Here, you have the form's data and could create a new object based on the form's `autocomplete` field value (which is what was typed), in case no PK id was provided for this field.

It would be more flexible to have a special `ChoiceWidget` though, which could get enabled somehow (e.g. via the modelform factory), and which would handle it - if that's possible.

(see also this question on StackOverflow: http://stackoverflow.com/questions/24243853/django-autocomplete-light-allow-free-text)

**Comment by gt-liu** [comment]
Is this issue solved or not? Could someone illustrate the best way to solve it? And close this issue?

**Comment by gt-liu** [comment]
I tried that example app but it didn't seem to work.

Is this issue solved? If solved, shouldn't this be closed?

And could someone illustrate the best  and convenient approach to solve it?

**Comment by jpic** [comment]
I tried the example app and it works and it shows the best and convenient approach to solve it that I know of.

When we start doing autocompletes we imagine that we can provide a transparent way for the user to have related objects "get or created". It turns out that this is very weak to typos and would thus lead to duplicate entry. With the `create_choices_on_the_fly` approach, the user can select the "Create Fly" option and that will create and select the choice.

I think a bit more documentation on this subject would be good before we close this issue.

**Comment by jpic** [comment]
Isn't that good enough ?
http://dal-yourlabs.rhcloud.com/admin/create_choice_on_the_fly/fly/add/

**Comment by blueyed** [comment]
Thanks @jpic!

It's good enough.
I have created #528 to improve it.

**Comment by evasquezcr** [comment]
Hello, I have a problem with autocomplete, It is that after I chose an option the input is set Disable. How can I change It? the field is "ManyToMany()"

Best regards, thanks

**Comment by jpic** [comment]
Apparently there is a bug in jquery autocomplete light. If you aren't good
with JavaScript and are unable to debug I recommend you use DAL v3 which
uses select2 and has a more active community than jquery autocomplete light.
