### ISSUE TITLE
Ampersand character (&) cannot be typed in the autocomplete input

### ISSUE THREAD

**Issue by yliharma** [yourlabs/django-autocomplete-light#294]
If you try to type the character _&_ (which in my qwerty european keyboard is SHIFT+6) nothing happens.
I probably found the solution to that by adding a condition in autocomplete.js, row 453 in yourlabs.Autocomplete.prototype.move, that checks if the key pressed is the shift key (apparently the browser mistakes Shift for keyUp...)

Your code:
```javascript
    // If not KEY_UP or KEY_DOWN, then return.
    if (e.keyCode == 38) var way = 'up';
    else if (e.keyCode == 40) var way = 'down';
    else return;
```
becomes:

```javascript
    // If not KEY_UP or KEY_DOWN, then return.
    if (e.keyCode == 38 && !e.shiftKey) var way = 'up';
    else if (e.keyCode == 40) var way = 'down';
    else return;
```

**Comment by aidanlister** [comment]
Is this fixed now? I can't find a commit referencing it

**Comment by yliharma** [comment]
Your pull request has been merged!

**Comment by blueyed** [comment]
@aidanlister 
It has been committed in 51e20fa31189d47a05625335dbad96480bc82def.

**Comment by blueyed** [comment]
@aidanlister @yliharma 
Can you please test if the following patch/PR still/also fixes it for you:
https://github.com/yourlabs/django-autocomplete-light/pull/398

It should be cleaner that way, but I want to not cause a regression here.
