### ISSUE TITLE
Widget select list gets under new-added inline (django-suit)

### ISSUE THREAD

**Issue by rocknrollnerd** [yourlabs/django-autocomplete-light#296]
![ac_light](https://cloud.githubusercontent.com/assets/4882763/3423914/3eeaaaa8-ffb2-11e3-9f7a-37336146b16e.png)

The picture pretty much describes itself. Maybe that's django-suit issue and not autocomplete's, but still - how could I get rid of that weird select list?

**Comment by jpic** [comment]
Hi ! Any feedback ?

**Comment by jpic** [comment]
I think this is fixed in 2.2.0rc3 by #426: handle z-index since we're absolutely-positioning in 2.2.x

Please re-open and contribute a test project if that's still a problem.
