### ISSUE TITLE
AutocompleteModel: respect/use get_field_queryset

### ISSUE THREAD

**Issue by blueyed** [yourlabs/django-autocomplete-light#300]
I have extended Django's `BaseModelAdmin.get_field_queryset` to limit the choices based on `request.user`.

Unfortunately this does not get picked up by autocomplete_light automatically.

For one, I have made the following change, so that the `queryset` for the field gets not overwritten by autocomplete_light:

    diff --git i/autocomplete_light/fields.py w/autocomplete_light/fields.py
    index e202aca..9c0d9d7 100644
    --- i/autocomplete_light/fields.py
    +++ w/autocomplete_light/fields.py
    @@ -30,11 +30,12 @@ class FieldBase(object):
                         autocomplete_js_attributes, extra_context)
             kwargs['widget'] = widget

    -        parents = super(FieldBase, self).__self_class__.__bases__
    -        if ((forms.ModelChoiceField in parents or
    -                forms.ModelMultipleChoiceField in parents)
    -                and isinstance(self.autocomplete.choices, QuerySet)):
    -            kwargs['queryset'] = self.autocomplete.choices
    +        if 'queryset' not in kwargs:
    +            parents = super(FieldBase, self).__self_class__.__bases__
    +            if ((forms.ModelChoiceField in parents or
    +                    forms.ModelMultipleChoiceField in parents)
    +                    and isinstance(self.autocomplete.choices, QuerySet)):
    +                kwargs['queryset'] = self.autocomplete.choices

             super(FieldBase, self).__init__(*args, **kwargs)

This isn't enough though, or rather has no influence.
It seems like `choices` is determined when registering the Model: https://github.com/yourlabs/django-autocomplete-light/blob/v2/autocomplete_light/registry.py#L166-167

Is it possible for autocomplete_light to provide this feature by default?

**Comment by LegoStormtroopr** [comment]
+1 the heck out of this, this would be great to see rolled into main. Thanks for the work

**Comment by jpic** [comment]
Agreed, good work @blueyed, I've added you to GitHub and PyPi in case you
want to [make a release](http://docs.yourlabs.org), else maybe Samuel wants
to give it a shot ?

**Comment by blueyed** [comment]
I have not looked into this for some time.
It's probably mostly PR #301 and #305 that's related, and I was asking for feedback on it back then.

I might find some time in the next weeks to get back to it, and sort out / update the various PRs.

**Comment by blueyed** [comment]
Closing this issue in favor of the new PR at #360.
