### ISSUE TITLE
Using autocomplete in a TabularIine for a single field

### ISSUE THREAD

**Issue by htomika** [yourlabs/django-autocomplete-light#307]
I'm using the autocomplete for a TabularInline admin part.
The inlines represent invoice items, the user can autocomplete on the item/product name, I pass back a special choice template with a couple of data-x values for a js that fills the neighbouring field with the hidden values.
The problem is: whereas autocomplete requires data-value to be a pk, django admin requires this single field to be a text. So I did the workaround below.
Might be not nice, but I wanted this FYI. 

    def choices_for_values(self):
            """
            Return ordered choices which pk are in
            :py:attr:`~.base.AutocompleteInterface.values`.
            """
            assert self.choices is not None, 'choices should be a queryset'
            pks = []
            for x in self.values:
                if x:
                    if isinstance(x, int):
                        pks.append(x)
                    elif x.isnumeric():
                        pks.append(x)
                    else:
                        tpk = self.choices.get(name=x).pk
                       pks.append(tpk)
            return self.order_choices(self.choices.filter(pk__in=pks))
            # return self.order_choices(self.choices.filter(
            #     pk__in=[x for x in self.values if x]))

**Comment by jpic** [comment]
Fixed in recent versions.
