### ISSUE TITLE
Model not acquired from AutocompleteModelBase in AutocompleteRegistry.extracts_args

### ISSUE THREAD

**Issue by alsonkemp** [yourlabs/django-autocomplete-light#313]
First off: apologies, but I don't have time right now to submit a PR...  But I did want to get some notes over to you.  And thanks for your excellent work!

AutocompleteRegistry.extracts_args doesn't extract the model from the Autocomplete object.  I've included a wee monkey patch which I'm using for your reference.  The part that matters is just adding the following:

    if autocomplete and not model:
        model = getattr(autocomplete, 'model', None)
So:

    @classmethod
    def extract_args(cls, *args):
        """
        Takes any arguments like a model and an autocomplete, or just one of
        those, in any order, and return a model and autocomplete.
        """
        model = None
        autocomplete = None

        for arg in args:
            if issubclass(arg, models.Model):
                model = arg
            else:
                autocomplete = arg

        if autocomplete and not model:
            model = getattr(autocomplete, 'model', None)

        return [model, autocomplete]

Here's the monkey patch I'm using:

    ##########################################################################
    # This is a monkey patch on autocomplete_light which fixes a bug in which 
    # the model is not acquired from the Autocompleter.
    def _fixed_extract_args(cls, *args):
        model, autocomplete = c._bugged_extract_args(*args)
        if autocomplete and not model:
            model = getattr(autocomplete, 'model', None)
        return [model, autocomplete]
    c = autocomplete_light.AutocompleteRegistry
    setattr(c, '_bugged_extract_args', getattr(c, 'extract_args'))
    c.extract_args= classmethod(_fixed_extract_args)
    ##########################################################################

**Comment by jpic** [comment]
Hi ! Would you have time to make a PR before the next release ? 

Thanks B)
