### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by MaZZly** [yourlabs/django-autocomplete-light#314]
An Autocomplete field that has `minimum_characters: 0` will freeze the browser when selected (until Call stacks is exceeded).

| function | file:line |
| :-- | --: |
| Uncaught RangeError: Maximum call stack size exceeded | jquery.min.js:2 |
| n.extend.camelCase | jquery.min.js:2 |
| n.extend.css | jquery.min.js:3 |
| Zb | jquery.min.js:3 |
| n.cssHooks.(anonymous function).get | jquery.min.js:3 |
| n.extend.css | jquery.min.js:3 |
| (anonymous function) | jquery.min.js:4 |
| n.access | jquery.min.js:3 |
| n.fn.(anonymous function) | jquery.min.js:4 |
| yourlabs.Autocomplete.fixPosition | autocomplete.js:511 |
| yourlabs.Autocomplete.show | autocomplete.js:400 |
| yourlabs.Autocomplete.fetch | autocomplete.js:549 |
| yourlabs.Autocomplete.show | autocomplete.js:409 |
| yourlabs.Autocomplete.fetch | autocomplete.js:549 |
| yourlabs.Autocomplete.show | autocomplete.js:409 |
| yourlabs.Autocomplete.fetch | autocomplete.js:549 |
| yourlabs.Autocomplete.show | autocomplete.js:409 |
| ... | ... |
| yourlabs.Autocomplete.fetch | autocomplete.js:549 |
| yourlabs.Autocomplete.show | autocomplete.js:409 |

Odd thing is that this only happens on remote server, when running locally no problems.

**Comment by jpic** [comment]
This might be a bug in yourlabs.Autocomplete.prototype.hasChanged which is responsible for preventing this.

**Comment by jpic** [comment]
Is there any way we could reproduce this ?

Thanks !

**Comment by blueyed** [comment]
> only happens on remote server, when running locally no problems

This might indicate that some latency is needed to trigger this, or that the remote app behaves differently, e.g. because of `DEBUG=True` etc.
