### ISSUE TITLE
Error: cannot import name force_text

### ISSUE THREAD

**Issue by rubinhozzz** [yourlabs/django-autocomplete-light#319]
I get that error. It seems because I'm using Django version 1.4. Is there a way to use the django-autocomplete-light with 1.4.

Thanks in advance.

**Comment by defbyte** [comment]
Does this mean django-autocomplete-light is not compatible with older Django versions, such as 1.3.x?

**Comment by blueyed** [comment]
I am not sure, but at least v2 is not being tested against Django < 1.4.

I've also found this: http://django-autocomplete-light.readthedocs.org/en/stable-2.x.x/django13.html

**Comment by blueyed** [comment]
@defbyte 
It might be possible to get it working - but given that Django 1.3 is not supported in general anymore, I do not think it's worth the effort.

**Comment by defbyte** [comment]
Understandable for sure! Unfortunately, the thing I am working on is a legacy project that cannot yet be upgraded to a later version of Django ;)

After some hackery, I was able to get it up and running in Django 1.3.x

**Comment by blueyed** [comment]
@defbyte 
Cool. I think that a pull request would be welcome.

**Comment by defbyte** [comment]
@blueyed oh, the hackery was to the project implementation, not the django-autocomplete-light itself.

**Comment by jpic** [comment]
If you're running 1.3 in 2015 then there's nothing we can do for you, you're already backporting security fixes yourself right ? ;)

**Comment by defbyte** [comment]
@jpic lol. yeah, you know it.
