### ISSUE TITLE
Is there a way to add a vertical scrollbar to the results?

### ISSUE THREAD

**Issue by yliharma** [yourlabs/django-autocomplete-light#324]
When the number of results is high (50 and more) it's incredibly painful to scroll the entire page down: having the possibility to add a vertical scrollbar would be very welcome.
I cannot use a lower limit in the class config because I use an AutocompleteGeneric and I would not find all the items required (given that the results cannot be ordered).

**Comment by MaZZly** [comment]
How to solve the problem of the dropdown hiding when scrollbar is clicked/dragged? Scrolling with mousewheel works fine.

**Comment by yliharma** [comment]
MaZZly the dropdown in the admin works fine for me clicking/dragging the scrollbar. 
Probably it's something related to your css or to some other javascript in the page.

**Comment by MaZZly** [comment]
It might be due to having it in a modal with bootstrap..Will have to investigate more..
