### ISSUE TITLE
django-bootstrap3's bootstrap_form templatetag breaks form submission due to "required" attribute

### ISSUE THREAD

**Issue by soult** [yourlabs/django-autocomplete-light#325]
I am using the autocomplete light extension with the [django-bootstrap3](https://github.com/dyve/django-bootstrap3) extension.

When I use the ```bootstrap_form``` templatetag instead of the usual ```form.as_p``` or similar, the boostrap extension adds a "required" attribute to the input HTML tag. Browsers that support the tag will then not let me submit the form.

My current workaround is to manually set the ```is_required``` attribute to ```False``` for all autocomplete widgets. You can see the check used by django-bootstrap3 [here](https://github.com/dyve/django-bootstrap3/blob/develop/bootstrap3/forms.py#L140-141).

Do you think it would be useful to automatically set the ```is_required``` attribute on all autocomplete widgets?

**Comment by jpic** [comment]
Any feedback ? please reopen ;)
