### ISSUE TITLE
Provide jquery-formset example

### ISSUE THREAD

**Issue by Mamsaac** [yourlabs/django-autocomplete-light#327]
I browsed the issues and this issue seemed to be fixed long time ago. However, when working with both django-autocomplete-light stable and with 2, I couldn't get it to work.
After debugging the code for around 20 minutes, I just added:

``` javascript
$('[data-widget-ready]',row).removeAttr('data-widget-ready');
```

In the jquery.formset.js code, right before inserting the element. So it looks like this:

``` javascript
applyExtraClasses(row, formCount);
$('[data-widget-ready]',row).removeAttr('data-widget-ready');
row.insertBefore(buttonRow).show();
```

I did so because I noticed on the django-autocomplete-light JS code that when validating for an added widget, you check for the attribute if it is set.

I decided that I shouldn't make modifications to jquery-dynamic-formset since this is more of a django-autocomplete-light issue. So, I removed the change and actually commented out the ':not([data-widget-ready])' from the validation to see if it is an added widget. Probably because I haven't used it much and I haven't read all of the docs (pretty extensive documentation out there! That's great), but I don't really understand the need for the not in the css query.

``` javascript
else { // added a widget ?
    var notReady = '.autocomplete-light-widget';//:not([data-widget-ready])'
    var widget = $(e.target).find(notReady);

    if (!widget.length) {
        return;
    }

    // Ignore inserted autocomplete box elements.
    if (widget.is('.yourlabs-autocomplete')) {
        return;
    }

    // Ensure that the newly added widget is clean, in case it was
    // cloned with data.
    widget.yourlabsWidget('destroy');
    widget.find('input').yourlabsAutocomplete('destroy');

    // added a widget: initialize the widget.
    widget.trigger('initialize');
}
```

See, the problem appears to me that is that when the jquery.formset plugin clones the row, it does it keeping the data-widget-ready attribute. Thus the new row is not taken into account by the code. 

I am unaware of rows that have the autocomplete-light-widget class, the data-bootstrap="normal"  attribute and are being just inserted into the document that should have the widget-ready data as 1. Of course, I don't know much of what is going on behind the scenes, since I barely read some of the code.

My forms look like this:

``` python
class OrdenForm(ModelForm):
    justificacion = forms.CharField(
        max_length=300,
        widget=forms.Textarea(attrs={'cols': 80, 'rows': 3}))

    class Meta:
        model = Orden
        fields = ('justificacion',)


class OrdenProductoForm(autocomplete_light.ModelForm):
    orden = forms.ModelChoiceField(
        label="", queryset=Orden.objects.all(),
        widget=forms.HiddenInput())

    class Meta:
        model = OrdenProducto
        fields = ('producto', 'cantidad', 'orden')


class ProductoForm(forms.ModelForm):

    class Meta:
        model = Producto
        fields = '__all__'


OrdenProductoFormSet = inlineformset_factory(
    Orden, OrdenProducto, form=OrdenProductoForm, extra=2)
```

My autocomplete_light_registry looks like this:

``` python
class ProductoAutocomplete(autocomplete_light.AutocompleteModelBase):
    search_fields = ['^modelo', 'nombre']
    attrs = {'placeholder': 'Modelo y/o nombre', }
    empty_html_format = """
<span class="div">
    <em>%s</em>
    <a href="#crear_producto"
       class="crear_producto_abre">
      Crear producto
    </a>
</span>"""


# This will generate a PersonAutocomplete class
autocomplete_light.register(Producto, ProductoAutocomplete)
```

The template (simplified) looks like this:

```
<h1>Crear orden</h1>
        <form action="{% url 'maindemo:orden_crear' %}" method="post" id="orden_crear_forma">
            {% csrf_token %}
            <div>
                {{ form.as_p }}
            </div>
            <fieldset>
                <legend>Productos de la orden</legend>
                {{ ordenproducto_form.management_form }}
                {{ ordenproducto_form.non_form_errors }}
                {% for form in ordenproducto_form %}
                    {{ form.id }}
                    <div class="inline {{ ordenproducto_form.prefix }}">
                        {{ form.description.errors }}
                        {{ form }}
                    </div>
                {% endfor %}
            </fieldset>
            <input type="submit" value="Crear orden" class="submit" id="orden_crear_submit" />
        </form>
<script type="text/javascript">
    $(function() {
        $(".inline.{{ ordenproducto_form.prefix }}").formset({
            prefix: "{{ ordenproducto_form.prefix }}",
            addText: "Agregar otro",
            deleteText: "Quitar",
        })
    })
</script>
```

By keeping it like this with the modifications I added, it is working perfectly. However, I don't like the idea of changing the widgets.js code of the imported app, since an update would break the code. Am I doing something wrong?

**Comment by jpic** [comment]
Instead of overriding the whole code, try overriding just methods: http://django-autocomplete-light.readthedocs.org/en/stable-2.x.x/script.html#overriding-widget-js-methods

A pull request would be great.

**Comment by jpic** [comment]
We should remove data-widget-ready on clone, i thought it was the case already ?

Time to add this example app.

**Comment by jpic** [comment]
It does work in inline relateds.

**Comment by jpic** [comment]
Ok, let's have a jquery-formset example in 2.3.

**Comment by ajinkya-bhosale** [comment]
where I can find jquery-formset example for v3 stable ?
 http://django-autocomplete-light.readthedocs.org/en/stable-2.x.x/script.html#overriding-widget-js-methods   This link is not working.

**Comment by jpic** [comment]
It was not implemented, PRs welcome.

But I suggest that a PR be made on django-dynamic-formset instead, so that it matches django.contrib.admin's formset system, or perhaps even reuse its scripts, because all widgets are compatible with django.contrib.admin's formset by design.

**Comment by dwasyl** [comment]
Wait, so DAL v3 isn't compatible with django-dynamic-formset? I've got things seemingly working, except when I try to add a row I get a select2 javascript error which makes things go wonky.

**Comment by jpic** [comment]
Rather, django-dynamic-formset is not compatible with django. DAL is compatible with dynamic formsets the way django.contrib.admin does it. If django-dynamic-formsets worked the way django.contrib.admin's dynamic formsets do, which it should, then DAL would be compatible with it.

For the moment, I don't need this. However, if you want I can make a crowdfunding campaign to fix django-dynamic-formset.

**Comment by dwasyl** [comment]
Ahhh, okay I understand now. Wish I'd realized that a few hours ago, but it's been a good learning experience. Since I'm already shoehorning Selectize in to DAL, but I'll try work on manually using it with my formset fields. Would love to be able to contribute to fixing dynamic-formset but it's both beyond my abilities and budget :)

Thanks for the quick reply. Any chance you know of another formset library that just works with DAL?

**Comment by jpic** [comment]
We now have an example outside the admin https://github.com/yourlabs/django-autocomplete-light/blob/master/test_project/select2_outside_admin/templates/select2_outside_admin.html
