### ISSUE TITLE
debug_toolbar broken by autocomplete light in Django 1.7

### ISSUE THREAD

**Issue by puterleat** [yourlabs/django-autocomplete-light#328]
My problem is almost exactly described here:

https://github.com/toastdriven/django-haystack/issues/1074

Except that have django-autocomplete-light==1.4.14 and django-debug-toolbar==1.2.1

**Comment by jpic** [comment]
Hello ! Could you provide an update please ? Thanks !

**Comment by jpic** [comment]
Closing, this is most certainely fixed in recent releases.
