### ISSUE TITLE
2.0.1 release does not contain compiled locale files

### ISSUE THREAD

**Issue by mpasternak** [yourlabs/django-autocomplete-light#336]
Hi,

2.0.1 release installed via pip does not contain any compiled locale files, just .po sources .

**Comment by jpic** [comment]
Thanks Michal ;)

Fixed: 

$ tar xvf ~/env/src/autocomplete-light/dist/django-autocomplete-light-2.0.7.tar.gz  | grep \\.mo
django-autocomplete-light-2.0.7/autocomplete_light/locale/it/LC_MESSAGES/django.mo
django-autocomplete-light-2.0.7/autocomplete_light/locale/ru/LC_MESSAGES/django.mo
django-autocomplete-light-2.0.7/autocomplete_light/locale/pt_BR/LC_MESSAGES/django.mo
django-autocomplete-light-2.0.7/autocomplete_light/locale/hr/LC_MESSAGES/django.mo
django-autocomplete-light-2.0.7/autocomplete_light/locale/nl/LC_MESSAGES/django.mo
django-autocomplete-light-2.0.7/autocomplete_light/locale/es/LC_MESSAGES/django.mo
django-autocomplete-light-2.0.7/autocomplete_light/locale/fr/LC_MESSAGES/django.mo
django-autocomplete-light-2.0.7/autocomplete_light/locale/cs/LC_MESSAGES/django.mo
django-autocomplete-light-2.0.7/autocomplete_light/locale/pl/LC_MESSAGES/django.mo

**Comment by mpasternak** [comment]
Thanks!

2015-01-20 15:39 GMT+01:00 James Pic <notifications@github.com>:

> Closed #336
> <https://github.com/yourlabs/django-autocomplete-light/issues/336>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yourlabs/django-autocomplete-light/issues/336#event-221629561>
> .
>



-- 
Pozdrawiam,
Michał Pasternak
📱 +48 793 66 87 33
