### ISSUE TITLE
Using DAL 'add another' functionality for a <select>

### ISSUE THREAD

**Issue by SaeX** [yourlabs/django-autocomplete-light#339]
I've got a form for `Document` where the end user should pick a category from a list (<select>). The items in that list are coming from a different model ´DocumentCategory`.
There will be only a few categories, but I'd like to have the possibility to add a category through the "+" button, after which the newly entered category would be selected in the <select>.

I had a look at http://django-autocomplete-light.readthedocs.org/en/latest/addanother.html which tells more about this, but seems focused on autocomplete as well.

What would be the easiest way and DRY to achieve the above? Since I'm using django-autocomplete-light in other forms, I'd prefer not to copy/paste and hack around.

**Comment by jpic** [comment]
Could you reproduce your question in stackoverflow and link it here if necessary ?

Thanks ! 

And Welcome to AUTHORS BTW B)
