### ISSUE TITLE
MultipleChoiceWidget next entry dropping down too far

### ISSUE THREAD

**Issue by eduvik** [yourlabs/django-autocomplete-light#344]
I discovered an issue with the MultipleChoiceWidget dropping the autocomplete selection box down too far when each subsequent entry was created. The problem is in autocomplete.js line 519:
// Calculate and set the outer container's absolute positionning.
```javascript
yourlabs.Autocomplete.prototype.fixPosition = function() {
    // Insert the autocomplete container after the input.
    var pos = $.extend({}, this.input.position(), {
        height: this.input.outerHeight()
    });

    this.input.parents().filter(function() {
        return $(this).css('overflow') === 'hidden';
    }).first().css('overflow', 'visible');
	
    this.box.insertAfter(this.input).css(
            {top: pos.top + pos.height, left: pos.left});
}
```

If I replace `top: pos.top + pos.height` with just `top:pos.height` it works correctly for me.

I'm using 1.4.14 - not sure if it's fixed in 2.x

**Comment by jpic** [comment]
Merged and release long ago.
