### ISSUE TITLE
How to use with requirejs jquery?

### ISSUE THREAD

**Issue by pcompassion** [yourlabs/django-autocomplete-light#346]
We use require.js to load jquery, and i'd like to use the same jquery version in the admin as well.
Following code won't work because `$ or jQuery` is not defined in the code included by static.html

    {% extends "admin/base.html" %}

     {% block extrahead %}
     <script src='{% static "site_common/bower_components/requirejs/require.js" %}'></script>

     <script>
      require(["site_common/js/config"], function () {
        require(['infrastructure'], function () {

          require([
            'jquery',
           ], function($) {
          });
        });

      });

     </script>
     {% include 'autocomplete_light/static.html' %}

     {% endblock %}`

**Comment by jpic** [comment]
Load the JS how you'd like instead of including `autocomplete_light/templates/autocomplete_light/static.html`.
