### ISSUE TITLE
Results only from the start of words

### ISSUE THREAD

**Issue by petedrennan** [yourlabs/django-autocomplete-light#348]
I am trying to get results where the search term only matches from the start of the word

eg a search for 'san'

finds 'Busan' and 'San Francisco'.

I'd like only 'San Francisco' to be found, or at least appear first...

**Comment by jpic** [comment]
You can configure it in search_fields using ^ prefix

http://django-autocomplete-light.readthedocs.org/en/stable-2.x.x/api.html#autocomplete_light.autocomplete.model.AutocompleteModel.search_fields

On Thu, Jan 1, 2015 at 6:17 AM, petedrennan <notifications@github.com>
wrote:

> I am trying to get results where the search term only matches from the
> start of the word
>
> eg a search for 'san'
>
> finds 'Busan' and 'San Francisco'.
>
> I'd like only 'San Francisco' to be found, or at least appear first...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yourlabs/django-autocomplete-light/issues/348>.
>



-- 
http://yourlabs.org <http://blog.yourlabs.org>
Customer is king - Le client est roi - El cliente es rey.

**Comment by petedrennan** [comment]
Ah great, thanks for the reference, didn't know Django had that!

Thanks!

**Comment by jpic** [comment]
On Thu, Jan 1, 2015 at 10:44 PM, petedrennan <notifications@github.com>
wrote:

> didn't know Django had that!


Django-autocomplete-light's model autocomplete replicates this feature from
django.contrib.admin.

**Comment by davideghz** [comment]
Can you pls add a reference to the new doc? I have the opposite problem: my select match only for initial words and I'd like it to match all the entries: `IDE` should match both `IDEa` and `davIDE`

**Comment by jpic** [comment]
Could you open a new issue please ? This one is from 2015, it has changed a lot since then.

Please also provide your autocomplete view source code.

**Comment by davideghz** [comment]
yep, actually it was enough to change the query from:

`filter(name__istartswith=self.q)`

to:

`filter(name__icontains=self.q)`
