### ISSUE TITLE
Re-add master branch instead of stable/2.x.x

### ISSUE THREAD

**Issue by blueyed** [yourlabs/django-autocomplete-light#349]
I suggest re-adding the `master` branch, and use it instead of the stable/2.x.x branch.

It's good to have `stable/1.x.x`, but it is confusing to have a "stable" branch for the current stable / development version.

Or do you plan to have something like `develop`, seeing that there's a "BC break - for 3.0" issue label?
But then I'd still use "master" for current/development, and stable/2.x.x for backporting fixes.

**Comment by jpic** [comment]
Agreed, it'll take some setting change in rtfd and github at least, I'll
take care of that.

-- 
http://yourlabs.org <http://blog.yourlabs.org>
Customer is king - Le client est roi - El cliente es rey.

**Comment by jpic** [comment]
But that's going to close the pull requests though, so we might want to merge them first.

**Comment by jpic** [comment]
I'm kind of blocked on #345, the PR sounds useful but I don't quite understand it (yet).

**Comment by blueyed** [comment]
> I'm kind of blocked on #345, the PR sounds useful but I don't quite understand it (yet).

Are you trying to reproduce it?
It sounds like some offset error, that might only have affected 1.x somehow, and might be even caused by something outside of autocomplete-light.
Let's take the discussion there anyway.

Apart from that, it would be easy enough to rebase/cherry-pick anyway - even with the base branch being deleted/renamed.

**Comment by jpic** [comment]
Fixed ! Keeping stable/2.x.x branch to not drop pull requests.
