### ISSUE TITLE
list.py doesn't allow for empty choices list

### ISSUE THREAD

**Issue by dmosberger** [yourlabs/django-autocomplete-light#354]
Please consider applying this patch so there is no error message when self.choices is an empty list (no completions).

Thanks,

  --david

    --- autocomplete/list.py~	2015-01-13 19:38:55.000000000 -0700
    +++ autocomplete/list.py	2015-01-17 22:10:40.011270465 -0700
    @@ -48,7 +48,7 @@
             Return any :py:attr:`choices` that contains the search string. It is
             case insensitive and ignores spaces.
             """
    -        assert self.choices, 'autocomplete.choices is not set'
    +        assert self.choices is not None, 'autocomplete.choices is not set'
     
             requests_choices = []
             q = self.request.GET.get('q', '').lower().strip()

**Comment by blueyed** [comment]
Thanks for the patch, I've committed it.

FWIW, the assertion there was quite old already..

**Comment by dmosberger** [comment]
that was quick so thanks!

On Sun, Jan 18, 2015 at 3:24 PM, Daniel Hahler <notifications@github.com>
wrote:

> Thanks for the patch, I've committed it.
>
> FWIW, the assertion there was quite old already..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yourlabs/django-autocomplete-light/issues/354#issuecomment-70429332>
> .
>



-- 
eGauge Systems LLC, http://egauge.net/, 1.877-EGAUGE1, fax 720.545.9768
