### ISSUE TITLE
js name space

### ISSUE THREAD

**Issue by steeeveb** [yourlabs/django-autocomplete-light#355]
Hi,
I have a problem with the js namespace and, while debugging, I saw that the jquery plugins are defined directly referencing window.jQuery (text_widget.js) and window.$(in all other files).

It would be better, for managing collisions, with other js plugins, put all the definitions inside a classic

(function($){ 
    $.fn.yourlabsRegistry = function(key, value) {...} 
}(yourlabs.jQuery))

or something like this.

I can write a patch, if needed.
Thank you for your work.

**Comment by blueyed** [comment]
Agreed.
A pull request for this would be great!

**Comment by jpic** [comment]
+1 !

**Comment by jpic** [comment]
+1 !

I think you can submit patches easy on GitHub ie. on https://github.com/yourlabs/django-autocomplete-light/edit/master/autocomplete_light/static/autocomplete_light/addanother.js

Then travis will test it for you ;)

Nice JS skills BTW B)

**Comment by jpic** [comment]
Hi ! Next release will be issued in ~2-3 weeks, so you still have time to get your patch in if you want to benefit from updates.

**Comment by steeeveb** [comment]
Hi!
I was moved to another project and I have no time to work on it... I'm
sorry!

**Comment by blueyed** [comment]
Thanks @steeeveb for reporting back and the initial idea, which still makes sense.

I'll reopen it therefore.

**Comment by jpic** [comment]
Moved to jquery-autocomplete-light#2
