### ISSUE TITLE
Add_another_url without autocomplete

### ISSUE THREAD

**Issue by random-one** [yourlabs/django-autocomplete-light#382]
Hello,
I wanted to know is it possible to use the add_another_url outside the admin functionality without actually having an autocomplete for a particular ModelForm field?

If so, can you give me a clue how to do it, because I didn't see such example.

**Comment by jpic** [comment]
Note sure but check our blog for the post with implementation details

**Comment by random-one** [comment]
Sorry, I did not understand which blog post should I check or the blog in general should contain details about my question?

What I'm asking is quite simple, but I didn't see it in the docs.

**Comment by jpic** [comment]
Here's are technical details about add-another:
http://blog.yourlabs.org/post/20001556462/howto-javascript-popup-form-returning-value-for

My answer was vague because your question was pretty vague. Here's
documentation about asking for help:
http://django-autocomplete-light.readthedocs.org/en/stable-2.x.x/faq.html#how-to-ask-for-help

**Comment by random-one** [comment]
Sorry for my vague question... I did not see the point to fork the project and create an example app to show what I intended. My point was that I wanted to use this feature:
```
attrs= add_another_url_name='contacts:emailaddress-create')
```
and show all available options, instead of autocompleting the user input. Digging in javascript functions as in the article you gave me wasn't going to do the job as I plan to use this a lot in my project.

However I found a workaround, by just adding:
```
'data-autocomplete-minimum-characters': 0
```
to my ```attrs``` and now I see all available options.

Sorry once again to bother you with my question.

**Comment by jpic** [comment]
So you weren't trying to create a new choice and select it via a popup,
more like raw_id_fields in Django ?

No problem, I'm glad you worked it out,
data-autocomplete-mininum-characters: 0 is a classic. It's not defaulted to
0 because that could lead to poor performance in some cases.

**Comment by random-one** [comment]
No I wasn't reinventing the wheel. I just wanted to see the good old select widget(with its options) and still have the add_another button next to it, like in the admin.

And yes, I understand the risk of poor performance. I will use it for fields with very few options (less than 5 for example) and I assume it will do no harm.

**Comment by jpic** [comment]
It should be pretty easy, I've dissected the add-another system used by django here: http://blog.yourlabs.org/post/20001556462/howto-javascript-popup-form-returning-value-for
