### ISSUE TITLE
Django 1.8 warnings and 1.9 pending incompatibilities

### ISSUE THREAD

**Issue by puterleat** [yourlabs/django-autocomplete-light#390]
These errors get thrown when using django 1.8:

    /autocomplete_light/widgets.py:19: RemovedInDjango19Warning: The django.forms.util module has been renamed. Use django.forms.utils instead from django.forms.util import flatatt

    autocomplete_light/fields.py:8: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes. from django.contrib.contenttypes.generic import GenericForeignKey

**Comment by jpic** [comment]
Thanks, 1.8 support is under active development in the dj18 branch.

**Comment by jpic** [comment]
Could you try with 2.2.0rc1 which was [released yesterday](http://blog.yourlabs.org/post/119860038918/django-autocomplete-light-2-2-0rc1-release-notes) ? 

Thanks.
