### ISSUE TITLE
Autocompletes on Admin

### ISSUE THREAD

**Issue by joshglenn** [yourlabs/django-autocomplete-light#406]
I'm trying to get django-autocomplete-light to work on my site. Nothing I do seems to be working as far as the client side goes. Nothing in the admin ever autocompletes for me. But the autocomplete urls do function. I have been able to get the demo app (partially) working. But that doesn't help me with my application. All I know is it shouldn't be this difficult or time consuming to get started with this.

What are the exact steps to getting autocompletes to work in the admin. I've been trying for two days straight. I have made progress. But I'm still not there. Any suggestions?

**Comment by jpic** [comment]
We could not reproduce your issue. If it's still a problem for you, please
respond to this issue using the following template:


    OS Version:
    Python version:
    Django version:
    App version:
    Database version (if appliable):
    Database driver version (if appliable):
    Browser version (if appliable):

    Traceback (please paste the COMPLETE traceback here):



    Forms (only paste relevant section):



    Models (only paste relevant section):



    autocomplete_light_registry (only paste relevant section):



    javascript / html if relevant:



    How to reproduce this bug:

    -
    -
    -

    Excepted result:



    Actual result:



If you want a almost garanteed fast answer, then instead of pasting
Models/autocomplete_light_registry/javascript/html above, you could:

- fork the repo,
- reproduct your issue in a new, simple app in `autocomplete_light/example_apps`
- it should be reproducible in `test_project/manage.py runserver`.

See details in community documentation: http://docs.yourlabs.org

Thanks a lot for helping django-autocomplete-light better.

Sincerely

YourLabs core-dev team

**Comment by joshglenn** [comment]
Ok. I'll get that to you. In the meantime, what version of django are you guys typically using right now? Should I be using 1.8?

**Comment by blueyed** [comment]
1.8 would be good, but 1.7 also.

**Comment by joshglenn** [comment]
James, I tried doing what you said. I cloned the repo. Took one of the example_apps and made another similar to it, but using a simple model of my own design. When I tried to run the server, it says that the application cannot be found (likely because it is not looking in my clone of the repo, but in the autocomplete_light as installed by pip. How do I "install" from the cloned repo so my new example app will become available for use?

**Comment by blueyed** [comment]
`pip install -e .` maybe? - assuming you are using a separate virtualenv for this to test.

**Comment by joshglenn** [comment]
Okay. That did it. I was able to install it using that.

Now I get an error saying "Improperly configured" (see traceback below)

I assume this means it cannot find the template with which to render the page. I don't know how I should name the template. This app is based on the non_admin_add_another example, but I changed the name to words. How does the CreateView function (which is in the URL definition to render the page) know what template to look for and where?

```
    url(r'$', autocomplete_light.CreateView.as_view(
        model=TranslationModelForm, form_class=TranslationModelForm),
        name='translation_model_create'),
```



```
Environment:


Request Method: GET
Request URL: http://localhost:8000/words/

Django Version: 1.8
Python Version: 2.7.5
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'autocomplete_light',
 'django.contrib.admin',
 'cities_light',
 'autocomplete_light.example_apps.basic',
 'autocomplete_light.example_apps.music',
 'autocomplete_light.example_apps.autocomplete_test_case_app',
 'autocomplete_light.example_apps.security_test',
 'autocomplete_light.example_apps.dependant_autocomplete',
 'autocomplete_light.example_apps.non_admin_add_another',
 'autocomplete_light.example_apps.create_choice_on_the_fly',
 'autocomplete_light.example_apps.words',
 'navigation_autocomplete',
 'autocomplete_light.example_apps.app_config_with_registry_file',
 'autocomplete_light.example_apps.app_config_without_registry_file.apps.AppConfigWithoutRegistryFile',
 'autocomplete_light.example_apps.unuseable_virtualfield')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware')


Traceback:
File "/Users/josh/.virtualenvs/testaclite/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/Users/josh/.virtualenvs/testaclite/lib/python2.7/site-packages/django/views/generic/base.py" in view
  71.             return self.dispatch(request, *args, **kwargs)
File "/Users/josh/.virtualenvs/testaclite/lib/python2.7/site-packages/django/views/generic/base.py" in dispatch
  89.         return handler(request, *args, **kwargs)
File "/Users/josh/.virtualenvs/testaclite/lib/python2.7/site-packages/django/views/generic/edit.py" in get
  245.         return super(BaseCreateView, self).get(request, *args, **kwargs)
File "/Users/josh/.virtualenvs/testaclite/lib/python2.7/site-packages/django/views/generic/edit.py" in get
  206.         return self.render_to_response(self.get_context_data(form=form))
File "/Users/josh/.virtualenvs/testaclite/lib/python2.7/site-packages/django/views/generic/base.py" in render_to_response
  133.             template=self.get_template_names(),
File "/Users/josh/.virtualenvs/testaclite/lib/python2.7/site-packages/django/views/generic/detail.py" in get_template_names
  135.             names = super(SingleObjectTemplateResponseMixin, self).get_template_names()
File "/Users/josh/.virtualenvs/testaclite/lib/python2.7/site-packages/django/views/generic/base.py" in get_template_names
  146.                 "TemplateResponseMixin requires either a definition of "

Exception Type: ImproperlyConfigured at /words/
Exception Value: TemplateResponseMixin requires either a definition of 'template_name' or an implementation of 'get_template_names()'
```

**Comment by blueyed** [comment]
It should be named according to `templates/non_admin_add_another/nonadminaddanothermodel_form.html` in the example app.

Try `templates/words/translationmodelform_form.html`, based on your `model=TranslationModelForm` - which should be maybe only `model=TranslationModel` (then you need to remove `form` from the template name, too.

You can also try passing in `template_name` directly (to the `as_view`).

**Comment by joshglenn** [comment]
Okay. Thanks very much. I'll try that.

**Comment by joshglenn** [comment]
Well, it looks like the `model=TranslationModelForm` was the culprit. I can't be totally certain, but I think changing that to `model=TranslationModel` is what finally got me up-and-running. I have now migrated that into my project and got autocomplete-light working in my own app. That is huge progress after struggling this for some time. Thanks for your help with this, jpic and blueyed

**Comment by blueyed** [comment]
Cool!

It would be nice if we could get something out of this, which would improve the error reporting in the future for that case.

We could maybe type-check and validate some inputs somewhere (in autocomplete_light.CreateView?).

@joshglenn 
Did you have a ImproperlyConfigured error from the beginning, or something else?
Probably a mixture of everything? :)

**Comment by jpic** [comment]
@blueyed Actually we inherit from Django for that part in this class: https://github.com/yourlabs/django-autocomplete-light/blob/master/autocomplete_light/views.py#L74

We could maybe open a ticket in Django for that then ?

BTW, awesome work guys, I'm impressed B)

**Comment by blueyed** [comment]
> We could maybe open a ticket in Django for that then ?

What do you mean exactly?
Improving the error message there?

> Exception Value: TemplateResponseMixin requires either a definition of 'template_name' or an implementation of 'get_template_names()'

**Comment by jpic** [comment]
That's pretty clear when you're a bit used to Python. In PHP/Java we'd hard code type checking but it seems like @joshglenn has been bitten by duck typing.

**Comment by joshglenn** [comment]
Don't know what the problem was with this in the beginning when I first started using django-autocomplete-light, but I haven't been having this issue anymore. Maybe I was just having django newbie issues. Closing now.
