### ISSUE TITLE
Firefox on Android compatibility

### ISSUE THREAD

**Issue by lucky-user** [yourlabs/django-autocomplete-light#411]
Autocomplete doesn't work on Firefox on Android (tested on v. 37.0.2). It sends input event instead of keyup so typing doesn't trigger completion. It would be nice if input event will trigger completion the same way as keyup.

**Comment by jpic** [comment]
Closing because there's a PR, please follow #418

**Comment by jpic** [comment]
Could you try with 2.2.0rc1 which was [released yesterday](http://blog.yourlabs.org/post/119860038918/django-autocomplete-light-2-2-0rc1-release-notes) ? 

Thanks.

**Comment by lucky-user** [comment]
This particular issue is fixed in 2.2.0rc1. Thank you for the fix.
But I see more strange issues with this update:
First of all completion is broken because of undefined variables isOpera and isIE in autocomplete.js
[Lines 82 and 86](https://github.com/yourlabs/django-autocomplete-light/blob/master/autocomplete_light/static/autocomplete_light/autocomplete.js#L82-L86)
The second thing is when I use autocomplete input with bootstrap modal dialog, choices are displayed behind it.

**Comment by blueyed** [comment]
For reference, the `isIE` stuff has been added in 61e54ee.

**Comment by blueyed** [comment]
@lucky-user 
Can you please create new, separate issues for what you've discovered?
Thanks.

**Comment by jpic** [comment]
This needs to be backported from django admin I'm in the car going to
openzfs meet-up right now so I can't right now

**Comment by lucky-user** [comment]
I created new issues, please follow #425, #426
