### ISSUE TITLE
Incorrect case sql expression in 2.1.1 in postgresql

### ISSUE THREAD

**Issue by vikagalkina** [yourlabs/django-autocomplete-light#420]
In autocomplete_light.autocomplete.model.AutocompleteModel.order_choices incorrect sql 
'WHEN %s="%s" THEN %s' because postgresql in expression like 'when id="123"' parse "123" like a column and raise exception that column "123" not found.

**Comment by jpic** [comment]
Duplicate of #419

**Comment by jpic** [comment]
Could you try with 2.2.0rc1 which was [released yesterday](http://blog.yourlabs.org/post/119860038918/django-autocomplete-light-2-2-0rc1-release-notes) ? 

Thanks.
