### ISSUE TITLE
ForeignKey without auto_field

### ISSUE THREAD

**Issue by perthvader** [yourlabs/django-autocomplete-light#424]
class Item(models.Model):
        id = models.CharField(primary_key=True)

    class MyInlineForm(forms.ModelForm):
        item = autocomplete_light.ModelChoiceField('ItemAutocomplete', label=_(u"Item"))

Fails on line 165: autocomplete_light/widgets.py in render

Is there a builtin solution for non-integer primary keys or should I rewrite the methods within the item's registry module?

**Comment by jpic** [comment]
> Fails on line 165: autocomplete_light/widgets.py in render

Please paste the full traceback.

Could you try with 2.2.0rc1 which was [released yesterday](http://blog.yourlabs.org/post/119860038918/django-autocomplete-light-2-2-0rc1-release-notes) ? It fixes #413 with #417. Should work for you.

Thanks

**Comment by perthvader** [comment]
fixed
