### ISSUE TITLE
[2.2.0rc1] undefined isOpera and isIE

### ISSUE THREAD

**Issue by lucky-user** [yourlabs/django-autocomplete-light#425]
Autocomplete is boken in 2.2.0rc1 since 61e54ee because of undefined variables isOpera and isIE in autocomplete.js
[Lines 63 and 67](https://github.com/yourlabs/django-autocomplete-light/blob/0f58157c86b8a0d9ee4008851f34d375d9eec447/autocomplete_light/static/autocomplete_light/autocomplete.js#L62-L68)
[Lines 82 and 86](https://github.com/yourlabs/django-autocomplete-light/blob/master/autocomplete_light/static/autocomplete_light/autocomplete.js#L82-L86)

As @jpic said it should be backported from django admin, probably [from here](https://github.com/django/django/blob/25e06bca57c068d4b9e9b4221b16a667ccb0d38e/django/contrib/admin/static/admin/js/core.js#L4-L5)

**Comment by jpic** [comment]
Yep undef variable are easy to fix if you make a PR it will get in

**Comment by blueyed** [comment]
FWIW, we should have test coverage for JS that would happen.
See e.g. http://stackoverflow.com/questions/4189312/capturing-javascript-error-in-selenium.

**Comment by jpic** [comment]
I know that is why we should release our js as standalone jq plug-in

**Comment by jpic** [comment]
This **should** be fixed in 2.2.0rc2

**Comment by jpic** [comment]
Could you confirm this is fixed in current rc and close the issue ?

Thanks a lot @lucky-user

**Comment by lucky-user** [comment]
Closing as it's fixed in e61e8f0f9d9c1ee59869f814c52808e6083d9a40
