### ISSUE TITLE
Do not hide autocomplete on scroll in Firefox

### ISSUE THREAD

**Issue by jpic** [yourlabs/django-autocomplete-light#438]
Last issue from #431: it has been reported that scrolling with an open autocomplete doesn't work well in windows.

Good news is that I contact BrowserStack support and they said they'd enable our tests on their awesome infra for free ... Because guess what: I don't have Windows so I can't reproduce ^^

**Comment by lucky-user** [comment]
Ok, I did some tests with rc8. The problem not just in Windows but in Firefox.
I have Firefox 37.0.1 on Linux Mint, 38.0.1 on Windows 7 and 38.0.1 on Android 4.3 and they all act the same way. If window height is small and we use my **favourite** bootstrap modal dialog scrolling down before typing breaks choices positioning. So the steps are:
1. Open bootstrap modal dialog
2. Scroll down to the input
3. Start typing
The choices are rendered above the input.

**Comment by jpic** [comment]
I see, you've got to scroll first before you open the AC and you can see the bug.

**Comment by jpic** [comment]
It seems like this happens on Firefox but not chrome, could you confirm
that ?

Since I can reproduce it I ll be able to show it to a front-end dev and if
there is not proper fix then we'll leave both positioning methods in 2.2.0.

**Comment by lucky-user** [comment]
Yes, it's just Firefox. Chrome, Opera and IE don't have this issue AFAIK.

**Comment by jpic** [comment]
Ok, the purpose of having scroll working was for small devices, which are mostly under webkit or ie. Firefox being AFAIK mostly used on desktops, scroll support isn't bloquant.

So I'm going to hide the autocomplete on scroll on firefox and release 2.2.0 today. One of my roommates at djangocon said he'll help fixing that but that "this bug sucks so I'm going to really have to take time", so we'll hopefully have that fixed in 2.2.1.

Does that sound ok to you ?

**Comment by lucky-user** [comment]
I think this issue can wait till 2.2.1 for sure and I'll be glad if someone will fix that. Please let me know when there are any changes so I can help with testing.

**Comment by jpic** [comment]
I've been told by a Mozilla employee that we should report it on their bug tracker anyway because it's firefox-specific. Pretty awesome B)

**Comment by jpic** [comment]
The solution we've had works well enough. Please reopen if you have any question.

**Comment by SummerSeaSun** [comment]
Hi,
we're experiencing the same problem, can you please post the firefox bug tracker reference?
It works even right even with Edge, is there any chance to get it working on Firefox?
Thanks, BR
