### ISSUE TITLE
readthedocs rotten

### ISSUE THREAD

**Issue by kvlahromei** [yourlabs/django-autocomplete-light#446]
Hi, sorry for the harsh words, but sadly your docs [over at readthedocs](https://django-autocomplete-light.readthedocs.org/en/stable-2.x.x/) doesn't really look good, while your project itself does :-/

* 1.xx chapter persists while this version is outdated and shouldn't been promoted
* badge links are broken
* TOC doesn't gives an overview
* demo links are broken

It would be great for newbies and to attract new users if you might spend some time to cleanup / restructure it, so people are able to see how easy you can use this autocomplete app :-)

**Comment by jpic** [comment]
I know, we've been sprinting mainly with @blueyed to fix known issues with the code during this semester thought. I've just put the demo server up again, and we surely want the docs and video tutorial to be updated ... And there is still some work to do to have jquery-autocomplete-light unit-tested.

So, yeah, PRs are definitely more appreciated than issues ;)

**Comment by kvlahromei** [comment]
As said, it's nothing to blame anybody ;-) But good docs make a project feel cool/professional to everybody whos just jumping in from google :+1:

**Comment by jpic** [comment]
Closing this unproductive issue.

When someone opens a PR to improve the doc we'll review it.
