### ISSUE TITLE
[bug] Wrong pk_name on subclasses (Error: Unknown column in 'field list')

### ISSUE THREAD

**Issue by alepn** [yourlabs/django-autocomplete-light#447]
Take as an example:

# in registers.models

class Person(AbstractBaseUser):
	Name =  models.CharField('Name',max_length=255)
	email = models.EmailField('Email',max_length=100)

class Employee(Person):
	class Meta:
		verbose_name = "Employee"
		verbose_name_plural = "Employees"

	def __unicode__(self):
		return "%s" % (self.Name)

# in departments.models

class Department(models.Model):

	Name = models.CharField('Department Name',max_length=60)
	Manager = models.ForeignKey('registers.Employee',verbose_name='Department Manager')

	class Meta:
		verbose_name = "Department"
		verbose_name_plural = "Departments"

	def __unicode__(self):
		return "%s" % (self.Name)

In Database the table registers_person has the pk name as "id" and registers_employee has the pk colunm name as "person_ptr_id".

When I try to edit a Department I have this error: "Unknown column 'registers_employee.person_ptr' in 'field list'".

So I changed in automplete/model.py (line 73) "choices.model._meta.pk.name" to "choices.model._meta.pk.attname".

BEFORE:

pk_name = ('id' if not getattr(choices.model._meta, 'pk', None)
                    else choices.model._meta.pk.name)

AFTER:

pk_name = ('id' if not getattr(choices.model._meta, 'pk', None)
                    else choices.model._meta.pk.attname)

So the bug was fixed.

**Comment by jpic** [comment]
Thanks a lot for your feedback !

Closing in favor of PR #448

**Comment by jpic** [comment]
Fixed in 2.2.3 release.

Thanks again for your detailled report.

**Comment by alepn** [comment]
Very nice. Congratulations for your job. Thanks.
