### ISSUE TITLE
Auto Complete not working

### ISSUE THREAD

**Issue by TheDrifter254** [yourlabs/django-autocomplete-light#451]
Hi,
I'm doing improvements for a site and found they used django autocomplete version 2.0.0 and Django 1.5.5 

The admin has autocomplete but adding it to another model has proved to be challenging. I've read the docs and looked and gone through how it's done. I'd appreciate assistance in figuring out why.

Here's the autocomplete_light_registry code:

    import autocomplete_light

    from models import *

    autocomplete_light.register(Article, search_fields=('name',),
        autocomplete_js_attributes={'placeholder': 'article name ..'})

The admin 

    class ArticleAdmin(CommonAdmin):
        form = autocomplete_light.modelform_factory(Article)
        list_display = [
            'name',
            'categories_display',
            'tags_display',
            'modified_by',
            'created_by',
            'modified',
            'created',
            'visible',
        ]
        list_editable = ['visible']
        filter_horizontal = ('tags',)
        #list_filter = ('categories',)
        excludes = ['sortorder',]
        inlines = [
            HotItemInline,
            ArticleImageInline,
            ArticleYoutubeVideoInline,
            #RelatedArticleInline
        ]

and the model

    class Tag(BaseItemMPTTModel):
        
        class Meta:
            ordering = ['name',]

        def __unicode__(self):
            return self.name
        

    class Article(BaseItemModel):
        area = TreeForeignKey(Area, blank=True, null=True,)
        categories = TreeManyToManyField(Category)
        tags = TreeManyToManyField(Tag, blank=True, null=True)
        author = models.CharField(max_length=255, blank=True,)
        html = RichTextField(blank=True, null=True,)
        
        def tags_display(self, separator='<br />'):
            return separator.join([s.name for s in self.pages.all()])
        tags_display.allow_tags = True
        tags_display.short_description = 'tags'

        def share_content(self):
            html = self.html
            if not html:
                html = self.content
            return html.replace('"', "'").strip()

        @models.permalink
        def get_absolute_url(self):
            return ('article_detail', (), {'slug': self.slug})

**Comment by jpic** [comment]
That's not supposed to do anything, unless Article has a relation to Article:

```
autocomplete_light.register(Article, search_fields=('name',),
    autocomplete_js_attributes={'placeholder': 'article name ..'})

class ArticleAdmin(CommonAdmin):
    form = autocomplete_light.modelform_factory(Article)
```

You'd have to register `Aera` if you wanted autocompletion on the Aera relation in the Article ModelForm, and so on.

**Comment by jpic** [comment]
The answer above should be satisfying, please reopen if you have any question.
