### ISSUE TITLE
choices.filter non-keyword arg after keyword arg

### ISSUE THREAD

**Issue by workino** [yourlabs/django-autocomplete-light#453]
Hello,
after upgrade i got these error:

``` 
 File ".../autocomplete_light_registry.py", line 30
    choices = choices.filter(country_code=country_iso[0]['iso'],  (Q(feature_code="PPLA")|Q(feature_code="PPLA3")))
SyntaxError: non-keyword arg after keyword arg
```

**Comment by jpic** [comment]
Not related to autocomplete light, in Python non-keyword arguments like the `(Q()|Q())` one must be before the keyword argument `country_code=..`. Try maybe chaining another filter call ie. `filter(country_code=..).filter(Q(..)|Q(..))`.
