### ISSUE TITLE
Can I put 400 controls on one page?

### ISSUE THREAD

**Issue by Kit-Fisto** [yourlabs/django-autocomplete-light#461]
I have an application that requires a control like this within a grid. There are up 400 controls on one page. The control I am currently using sends an ajax request during the inital load which makes displaying the page awfully slow.
Can django-autocomplete-light help me with this?

Thanks
Peter

(I would have preferred to label this a question, but it seem like I cannot do that?)

**Comment by jpic** [comment]
Could you define the controls you're talking about ?

**Comment by Kit-Fisto** [comment]
I am currently using another django autocomplete control and I am wondering whether django-autocomplete-light would solve my problem.

**Comment by jpic** [comment]
Well, who could know, maybe someone with information about both your
software and django-autocomplete-light ? Try and see ;)

**Comment by Kit-Fisto** [comment]
Seems my question is not clear enough.

Is there any experience in terms of performance with many django-autocomplete-light controls on one page? I need to put 400 controls on a page and expect loading times of the page in the range of two or three seconds.

**Comment by jpic** [comment]
On Sun, Jul 12, 2015 at 3:12 PM, Kit-Fisto <notifications@github.com> wrote:

> Is there any experience in terms of performance with many
> django-autocomplete-light controls on one page? I need to put 400 controls
> on a page and expect loading times of the page in the range of two or three
> seconds.
>
I'd love to know ;) I know we've been through optimisations to support
displaying autocompletes for many generic autocompletes on the same page
but I haven't yet tried to load 400 autocompletes at once. Please let us
know how it goes and please do a PR if you find any optimisation to make ;)

-- 
http://yourlabs.org <http://blog.yourlabs.org>
Customer is king - Le client est roi - El cliente es rey.

**Comment by jpic** [comment]
Closing until feedback.
