### ISSUE TITLE
Dependant Autocomplete City

### ISSUE THREAD

**Issue by pfremp** [yourlabs/django-autocomplete-light#468]
Hello, 

I have your example of the dependant autocomplete working (between the country and the region fields).

How can I extend this to work with the city field as well?

Do I need to edit the autocomplete_light_registry or is the JS file or both?

Many thanks

**Comment by jpic** [comment]
You would have to vary on the JS code : http://django-autocomplete-light.readthedocs.org/en/master/dependant.html

Please reopen if you have any more question.
