### ISSUE TITLE
Issue with no ascii characters

### ISSUE THREAD

**Issue by fabiorsce** [yourlabs/django-autocomplete-light#470]
I have an autocomplete for a model that has a title field and this field is the __str__()

class Entity(models.Model):
    wiki_id = models.CharField(max_length=20, blank=True)
    description = models.CharField(max_length=700, blank=True)
    title = models.CharField(max_length=500, blank=True, db_index=True)
    slug = models.SlugField(max_length=500,null=True, db_index=True)

    def __str__(self): 
        return self.title

class EntityAutocomplete(autocomplete_light.AutocompleteModelBase):
    search_fields = ['^title']
autocomplete_light.register(Entity, EntityAutocomplete)

The problem is because title could have special characters (utf-8) and the autocomplete only accepts ascii characters. For example, the title Žydrūnas Savickas is never returned.

I would like to type "Žydr" and get the option "Žydrūnas Savickas" in the list of options.

**Comment by jpic** [comment]
We should have a test for that, could you add one in
autocomplete_light/tests/autocomplete/test_model.py please ?

Thanks !

**Comment by jpic** [comment]
I tested here: http://jpic.pythonanywhere.com/admin/basic/fkmodel/add/

By pasting Žydr, and it worked as expected: http://jpic.pythonanywhere.com/admin/basic/fkmodel/41/change/

Please reopen if you still have this issue and provide more details.

Thanks !
