### ISSUE TITLE
Responsiveness / delay while typing

### ISSUE THREAD

**Issue by aidanlister** [yourlabs/django-autocomplete-light#479]
Most autocomplete's I've used have some sort of delay setting where you can prevent requests from being initiated while the user is typing, until there is a pause of n milliseconds.

See typeahead/bloodhound as an example, with rate limiting set to debounce and eg. a 500ms delay:
https://github.com/twitter/typeahead.js/blob/master/doc/bloodhound.md#remote

Does something like this exist for django-autocomplete?

The reason why I'd like to see this is we're using this in a high volume environment, and we see literally tens of thousands of "request aborted" or "connection interrupted" errors per day. We've tracked this down to the autocomplete widget.

**Comment by jpic** [comment]
[yourlabs.Autocomplete.xhrWait](http://django-autocomplete-light.readthedocs.org/en/master/_static/autocomplete.html#section-13) maybe ?

**Comment by nym** [comment]
Yeah, that looks correct @jpic

**Comment by jpic** [comment]
Also, this might fix it: https://github.com/yourlabs/jquery-autocomplete-light/pull/11

I'm releasing it right now.

**Comment by jpic** [comment]
Running integration tests one last time because of the jquery upgrade.

**Comment by thongly** [comment]
Just adding a comment for people looking into this with recent versions of select2 and DAL. The attribute to use is `delay`, and the way to pass this through from DAL to select2 is via the [data attributes](https://django-autocomplete-light.readthedocs.io/en/master/tutorial.html#passing-options-to-select2) (such as via the widgets in the class meta - [see docs](https://django-autocomplete-light.readthedocs.io/en/master/tutorial.html#displaying-results-using-custom-html))

For example.

```
                attrs={
                    "data-ajax--delay": "700" // <-- NOTICE THE DOUBLE (i.e. "--") SEPARATOR HERE!!!
                }
```
