### ISSUE TITLE
delete a prev choice in dependant autocomplete

### ISSUE THREAD

**Issue by sandroden** [yourlabs/django-autocomplete-light#481]
What's the better/simpler solution to delete a choice when dependant autocomplete is used?
Just to stick to the example in the docs if I have country and city both with autocomplete. I select both, then I delete selection of country. Clearly I need to invalidate selection of city, what's the suggested way to go?

thanks
*:-)

**Comment by jpic** [comment]
Could you use another on() callback on the city field maybe ?

**Comment by sandroden** [comment]
Supposed I'm already in the functions triggered by the change in the select of the country, my question is what should I do to "undo" the previous selection of the "city". I guess I should reset the input that holds the choice, but I should also make it visible again and I should delete the span that holds the result... How an I do programmatically what is triggered by the click on the X, is there a function on the autocomplete that I wasn't able to find??

thanks 
sandro
*:-)

**Comment by sandroden** [comment]
found: widget.deselectChoice(choice)

*;-)

**Comment by davidshumway** [comment]
Is this still the preferred action to take?

**Comment by jpic** [comment]
Basically yes
