### ISSUE TITLE
Attribute AutocompleteBase to limit SELECT field from database

### ISSUE THREAD

**Issue by ad-m** [yourlabs/django-autocomplete-light#484]
Hello,

I am would like disqus to modify ```AutocompleteBase``` to provide this kind hook:
```python
class InstitutionAutocomplete(autocomplete_light.AutocompleteModelBase):
    search_fields = ['name']
    list_fields = ('id', 'name')
    def choices_for_request(self, *args, **kwargs):
        qs = super(InstitutionAutocomplete, self).choices_for_request(*args, **kwargs)
        return qs.only(**self.list_fields) if self.list_fields else qs
```
I am think in mosts cases autocomplete don't require a lot of data, so this is a good idea to provide attribute to limit fields fetched by database. Django by default fetch all fields, long text fields too.

Greetings,

**Comment by jpic** [comment]
That's sane for the DB.
