### ISSUE TITLE
Setting up autocomplete fields for admin forms with StackedInline

### ISSUE THREAD

**Issue by hheimbuerger** [yourlabs/django-autocomplete-light#485]
I'm mostly wondering if this is a supported use case and whether I'm going the right approach.

We have a 1-to-1 connection of Django's `User` model to an internal `Profile` model to enhance it. In the admin, this is shown as a `StackedInline` admin form addition to the User admin. The `Profile` model itself has a simple `ForeignKey` to a third model, which I'm trying to add an autocomplete field for.

Here's an excerpt from the (current, non-autocomplete) admin configuration:

    class ProfileInline(django.contrib.admin.StackedInline):
        model = myapp.models.Profile
        # ...

    admin.site.unregister(User)   # we want to replace the predefined User admin, so we have to unregister first
    @admin.register(User)
    class UserAdmin(django.contrib.auth.admin.UserAdmin):
        inlines = (ProfileInline, )

Now I've set up django-autocomplete-light, I've extended the `base_site.html` and I have confirmed that jQuery and scripts are being loaded.

My attempt was to extend the `UserAdmin` class to the following:

    class UserAdmin(django.contrib.auth.admin.UserAdmin):
        inlines = (ProfileInline, )
        form = autocomplete_light.modelform_factory(User, fields='__all__')

I got autocomplete fields working for ForeignKeys to the same target model from other admin pages (which are not using the `StackedInline`) so I suspect it has something to do with that.

I guess part of the problem is that `modelform_factory` only allows to pass in one models, but my admin with the stacked inline extension actually displays two models at once?

**Comment by jpic** [comment]
Did you try using autocomplete modelform in ProfileInline.form ?

That would enable autocomplete fields in the ProfileInline form ;)

**Comment by hheimbuerger** [comment]
@jpic Thanks, that solved it for me!

Here's the code I'm using now:

```python
class ProfileInline(admin.StackedInline):
    model = myapp.models.Profile
    form = autocomplete_light.modelform_factory(myapp.models.Profile, fields='__all__')
```

No need to create an admin for the inlined model!
