### ISSUE TITLE
Something abnormal in admin site.

### ISSUE THREAD

**Issue by albus12138** [yourlabs/django-autocomplete-light#486]
I modify my project as the document say(pip, add INSTALL_APPS, include urls, modify "admin/base_site.html")But after these, I still not get the excepted widgets.What should I do?

**Comment by jpic** [comment]
Follow the tutorial at least.

**Comment by albus12138** [comment]
BTW, Your live demo seems not available.When I write some values in the input, it won't show the correct item(In fact, nothing).Then I write the correct name of item into the field and save, it didn't save anything.

**Comment by albus12138** [comment]
I follow the tutorial just now, but it's no use.(calls resgiter(MyModel) in my "autocomplete_light_registry.py" & calls modelform_factory(MyModel, exclude=[]) in "admin.py" to generate a form)

**Comment by jpic** [comment]
Demo works for me: http://jpic.pythonanywhere.com/

Your description of your situation and problem is too vague, so there's not much I can do, sorry. Maybe read these:
http://docs.yourlabs.org/en/latest/guidelines.html
http://django-autocomplete-light.readthedocs.org/en/master/faq.html#how-to-report-a-bug-effectively

**Comment by albus12138** [comment]
Here is my code:
admin.py
  from .models import Foo
  import django_autocomplete_light
  class FooAdmin(admin.ModelAdmin):
      form = django_autocomplete_light.modelform_factory(Foo, exclude=[])
  admin.site.register(Foo, FooAdmin)

autocomplete_light_registry.py
  import django_autocomplete_light
  from .models import Foo
  
django_autocomplete_light.regsiter(Foo)

models.py
  class Foo(models.Model):
      bar = Foreignkey(Bar)
  class Bar(models.Model):
      a = models.CharField(max_length=10)

What's wrong?

**Comment by jpic** [comment]
Register Bar instead of Foo.

**Comment by albus12138** [comment]
It displays correctly, but when I input something, it didn't show the items match the string I input. Why?
Here is the screenshot.
![qq 20150830220300](https://cloud.githubusercontent.com/assets/9742081/9567571/f88d93b6-4f62-11e5-94bd-11cb8d70c0bf.png)

**Comment by jpic** [comment]
Honestly I don't know because I never did website with a non-latin
language, try to reproduce it in a test app as described in the first batch
of links i posted so that i can try to debug the display issue, I'd really
like to have a take on this ;)

**Comment by albus12138** [comment]
Sorry, It's my fault.I use the wrong jquery.js(I just copy the file from "test_grappelli")…Not language problem, it works well in non-latin language.I have solved it just now.Thank you very much.^_^
