### ISSUE TITLE
How to make example_apps work

### ISSUE THREAD

**Issue by proph73** [yourlabs/django-autocomplete-light#487]
Hello
I have tried to pull the whole project from git. I have put navigation_autocomplete in its own project. I have taken the db.sqlite but now it also needs the url auth_user_change. I don't know where is the urls.py defining it.  Well, basically I can't make the example app "navigation_autocomplete" work.
What files must I gather in a projet in order to see it work ?
Thanks a lot.
BG

**Comment by jpic** [comment]
There is a topic about it in the docs have you seen it ? It drives you
through the needed files etc

**Comment by proph73** [comment]
Yes, in two parts, I've seen it. Thanks. I wanted to compare my implementation with yours to understand it finely. I discovered that I was not using the javascript like I should. But thanks to the working live demo hosted by PythonAnywhere and the project code, I succeeded.
There are a tiny error in the doc in "<a class="block choice" href="{{ artist.get_absolute_url }">{{ artist }}</a>", there is a '}' missing.

**Comment by proph73** [comment]
Sorry :
in <a class="block choice" href="{{ artist.get_absolute_url }">{{ artist }}</a>

**Comment by jpic** [comment]
Cool, could you please make a PR ?

Thanks !
