### ISSUE TITLE
Edit/Change related button popup

### ISSUE THREAD

**Issue by nwaxiomatic** [yourlabs/django-autocomplete-light#488]
Is there a way to add a Edit/Change button next to a model when overriding the field, just as with the add button there is the "add_another_url_name" parameter?

Would it be too difficult to add this functionality similar to this block
```
{% block add_another %}
    {# A link to add a new choice using a popup #}
    {% if autocomplete.add_another_url_name %}
    <a href="{% block add_another_href %}{{ autocomplete.get_add_another_url }}{% endblock %}" class="autocomplete-add-another" id="add_{{ widget.html_id }}" style="display:none;">
        <img src="{% static 'admin/img/icon_addlink.gif' %}" width="10" height="10" alt="{% trans 'Add another' %}" />
    </a>
    {% endif %}
{% endblock %}
```

**Comment by jpic** [comment]
There would be several ways, did you read the documentation about [styling autocompletes](http://django-autocomplete-light.readthedocs.org/en/master/template.html) ?

**Comment by jpic** [comment]
Did you sort it out ? Can we close this ?

**Comment by ezawadzki** [comment]
Hello,
The link @jpic you write doesn't exists anymore. What would you advice to do for adding an edition link near to the current select button with last version of DAL. It would be usefull for OneToOneField() as well as for GenericForeignKey().
Thanks

**Comment by jpic** [comment]
Did you try https://github.com/jonashaag/django-addanother ?

**Comment by dwasyl** [comment]
I hate to ask in this existing thread, but @jpic any chance you could provide some input on how to integrate django-addanother with dal v3 using their `ModelSelect2EditSelected` instead of DAL's `ModelSelect2`? Specifically, I'm trying to get an Edit button on my DAL select2 widgets. But, the docs of addanother seem to be based on the stock django-select2 widgets...

**Comment by jpic** [comment]
I think every wrapper class works the same:

https://github.com/jonashaag/django-addanother/blob/master/django_addanother/widgets.py#L93-L114

You can use any of them around your own widget instance, it just needs the url to use for the buttons:

https://github.com/jonashaag/django-addanother/blob/master/docs/usage.rst
https://github.com/jonashaag/django-addanother/blob/master/docs/edit-related.rst#id1
