### ISSUE TITLE
Box placement issue

### ISSUE THREAD

**Issue by kviktor** [yourlabs/django-autocomplete-light#489]
With version 2.2.0 (and 2.2.5)

![image](https://cloud.githubusercontent.com/assets/1112058/9681638/e6e3f2c2-52ff-11e5-808b-fb24032efeb1.png)

With version 2.1.1
![image](https://cloud.githubusercontent.com/assets/1112058/9681653/03efb0d6-5300-11e5-81d9-60bef1a587c0.png)

Any idea what broke/changed between the versions?

I'm using Bootstrap 3 and Crispy forms too.

With the Javascript snippet mentioned in #253  I get [this](http://i.imgur.com/IboXCDv.png).

**Comment by jpic** [comment]
Could you try with
https://github.com/yourlabs/jquery-autocomplete-light/pull/8 ?​

**Comment by kviktor** [comment]
Yes, that fixes the issue, thank you. Looking forward the merge.

**Comment by jpic** [comment]
As soon as I m done workin
