### ISSUE TITLE
Autocomplete should be able to return field value

### ISSUE THREAD

**Issue by hamzagul** [yourlabs/django-autocomplete-light#490]
Currently if any of search fields matches with typed characters that instance is returned in string/unicode representation. I have a use case in which i want autocomplete to return that field value which was matched. 

For example in Enployee model if my search field was country and i typed 'United' it should return 'United Kingdom' or 'United States' instead of employee model string/unicode representation. 

I am not sure whether this is possible to do with current code base, if it is then please help me.

**Comment by jpic** [comment]
What have you tried.

On Sun, Sep 13, 2015 at 10:00 PM, hamzagul <notifications@github.com> wrote:

> Currently if any of search fields matches with typed characters that
> instance is returned in string/unicode representation. I have a use case in
> which i want autocomplete to return that field value which was matched.
>
> For example in Enployee model if my search field was country and i typed
> 'United' it should return 'United Kingdom' or 'United States' instead of
> employee model string/unicode representation.
>
> I am not sure whether this is possible to do with current code base, if it
> is then please help me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yourlabs/django-autocomplete-light/issues/490>.
>



-- 
http://yourlabs.org <http://blog.yourlabs.org>
Customer is king - Le client est roi - El cliente es rey.

**Comment by hamzagul** [comment]
i went through the documentation didn't find a way to do it. its a pretty straight forward scenerio i guess. i have 10 text inputs in a form with 10 search fields set for autocomplete. i just intend to fill those text inputs with field value,which autocomplete has already matched.

**Comment by jpic** [comment]
I'm not aware of any option that you could enable to implement your
specifications :)

> autocomplete to return that field value which was matched.

What does that even mean ?

Have you read the JS API documentation ? Would definitely help

**Comment by hamzagul** [comment]
thank you for clarification :)

what i meant was something like this:

For Employee model,
search_field=['nationality',]

In autocomplete textwidget when i type 'United', it should return matched nationalities from all employee instances like 'United Kingdom', 'United States'. Right now it returns Employee model's string representation.

**Comment by jpic** [comment]
Did you try overriding the autocomplete class ?

Could you define "return" ?

**Comment by jpic** [comment]
Have you seen this one ?
http://django-autocomplete-light.readthedocs.org/en/master/template.html

**Comment by hamzagul** [comment]
That is exactly what I was trying to do. Thank you so much for your assistance :+1:
