### ISSUE TITLE
Bleeding edge Django

### ISSUE THREAD

**Issue by arnists** [yourlabs/django-autocomplete-light#496]
Is there a reason you want different things exposed to those of us using 1.9?

**Comment by jpic** [comment]
Not really, actually I'd like to keep the existing codebase as stable as possible, it is to my knowledge feature complete and even some feature creep made its way in which caused many many pain (`AutocompleteModel.choices_for_values()`).

Do you want to elaborate and tell us what you are talking about exactly BTW ?

Thanks !

**Comment by arnists** [comment]
Sure, and hi again James, you going to DUTH this year?

I'm running into the documentation not working out in small ways (mostly).

AutocompleteModelBase is not a child of autocomplete_light, had to change the __init__.py to import it especially.  register now has to be called from al.registry.register.  Small stuff really, but a bit irritating having to go digging.

**Comment by jpic** [comment]
I see, no that's just a requirement for django 1.9 support because it changed the way apps are loaded, not a design decision.

**Comment by jpic** [comment]
What's DUTH ?

**Comment by arnists** [comment]
Django Under The Hood, Amsterdam, Nov. 5-7.

**Comment by arnists** [comment]
I think they are sold out now but you might get lucky and get a cancellation ticket.

**Comment by jpic** [comment]
Yep, thanks, I've put myself on the waiting list !

**Comment by arnists** [comment]
(y) hope to see you there.  What is the post-1.9 way to get at AutocompleteModelBase (and the other things from the older shortcuts)?  I wasn't able to get them easily with several minutes of ipython introspection.

**Comment by jpic** [comment]
from autocomplete_light import shortcuts as autocomplete_light should work
iirc.​

**Comment by jpic** [comment]
I added a note in the readme: d87a3ba8be745ff3e5142d9438f3b8318f4bf547

Please reopen if necessary ;)

**Comment by jpic** [comment]
A bit more detail in the blog post about [django autocomplete light django 1.9 support and imports](http://blog.yourlabs.org/post/130026251348/django-19-support-for-django-autocomplete-light)
