### ISSUE TITLE
Auto complete for GenericForeignKey

### ISSUE THREAD

**Issue by user996015** [yourlabs/django-autocomplete-light#5]
Any chance this could be adapted to work with generic foreign keys?

Some work has been done here.
https://code.djangoproject.com/ticket/9976

**Comment by FoundOne** [comment]
I'm not sure why, but save_m2m don't save any multiple choice fields with generic relations for me. Does anyone else have such issue? I'm using django 1.7 and autocomplete-light 2.2.10

**Comment by jpic** [comment]
Well, it works in CI, could you isolate your issue in a small test project or app ? 

http://django-autocomplete-light.readthedocs.org/en/master/faq.html#how-to-report-a-bug-effectively
