### ISSUE TITLE
Above 1000 relations using 'through', the page takes 5 minutes to load.

### ISSUE THREAD

**Issue by pbassut** [yourlabs/django-autocomplete-light#512]
When I wasn't using through everything was in one field so django didn't create one field for each relation(as of now).

Now that I'm using 'through' to intermediate the relation django tries to create on input for each of them and thus takes forever.

The main purpose of library(as I see) is to remove the need to render a whole list and when in the need to add a new item, it won't need to query the whole database, it will get the ones matching a query which is not very harmful.

Now the problem is back with this rendering problem. Any idea of how I can fix this and make the django admin page load faster?

Here's a pic for clarification:
![image](https://cloud.githubusercontent.com/assets/1500037/10408592/79d4fac4-6ed8-11e5-8ba6-bcedd81be7e6.png)

**Comment by jpic** [comment]
Could you maybe use something like django debug toolbar to see where all
queries are triggered ? Also, check the auto complete URL itself which may
also be affected.
Thanks !

**Comment by pbassut** [comment]
Django is who issues these queries. But that's not what I'm trying to say. Shouldn't everything be on a input field like before? This way would prevent from create a reeaally large DOM and would take less rendering time. Also would be easier to add new stuff.

I Also noticed that you can add duplicates using the 'through'. That's django's "fault" though.

**Comment by pbassut** [comment]
Did you have the time to look at this? I'm sort of holding a release because of this.
Thanks!

**Comment by jpic** [comment]
Have a look at what ? Where's the source code ?

http://django-autocomplete-light.readthedocs.org/en/master/faq.html#how-to-report-a-bug-effectively

**Comment by pbassut** [comment]
Sorry, but did you read my last comment ?

**Comment by jpic** [comment]
Well I recon I'm a bit confused about your last comment :D Of course Django issues those queries, but something in DAL must be making django do them, it would be great to identify what exactly in DAL causes this..

**Comment by pbassut** [comment]
Alright, let me try to explain some other way. 
Look at my screenshot. You will see that, unlike before, django is creating a new input to put my new relation. But I would like everything to be on a single input cause that was would save memory and the browser would have to do less rendering work.

Here's a pic of django debug toolbar:
![image](https://cloud.githubusercontent.com/assets/1500037/10418928/76db8042-703e-11e5-8b2c-e32a8792e822.png)

**Comment by jpic** [comment]
Did you try pre-selecting subject and topic in your choices queryset ?

**Comment by pbassut** [comment]
I'm trying that right now. It will take a bit of the pain away.
But still the DOM loading problem will still occur. Since there's an <input> tag for every relation, it will take forever to load then we have 1 thousand entries. Agree?

**Comment by jpic** [comment]
While it's possible to show a thousand entries on a page, it's not recommended and would be hard to get it to render in a reasonable time I'd say, but that is unrelated to DAL to my knowledge.

**Comment by jpic** [comment]
Could you try changing the `def __unicode__()` or `def __str__()` if on python 3, to return `self.pk` and see if it loads any faster maybe ?

**Comment by pbassut** [comment]
Narrowed down the number of queries from 130 to 70. But still 5 seconds to load(this one does not have a thousand entries, just 60)

**Comment by jpic** [comment]
Are you saying that you went from 5 minutes to 5 seconds ?

70 is still too much, for 60 queries that probably means that you have 10 legitimate queries - which is reasonable - + 1 per entry, again either prefetch_related or select_related would help I recon.

**Comment by pbassut** [comment]
I'm trying to use prefetch_related to my manytomany field with no success so far. While using prefetch_related django is still doing one query to fetch each item, which is giving the bad performance.

Have a look. This is my model:
```python
class CourseTopic(models.Model):
    course = models.ForeignKey("Course")
    topic = models.ForeignKey(Topic)

class Course(models.Model):
    name = models.CharField(max_length=40, verbose_name="Nome")
    topics_required = models.ManyToManyField(Topic, related_name="course", through="CourseTopic")
```

My admin models:
```python
class CourseTopicInline(admin.TabularInline):
    model = CourseTopic
    form = CourseTopicForm

@admin.register(Course)
class CourseAdmin(admin.ModelAdmin):
    inlines = (CourseTopicInline,)
    form = CourseForm
```

My forms:
```python
class TopicAutoComplete(autocomplete_light.AutocompleteModelBase):
    search_fields = ['^name', ]
    choices = Topic.objects.select_related('subject')
    widget_attrs = {
        'data-widget-maximum-values': 4,
        'class': 'modern-style',
    }

class CourseTopicAutoComplete(autocomplete_light.AutocompleteModelBase):
    search_fields = ['^topic__name', ]
    choices = CourseTopic.objects.select_related('topic')
    widget_attrs = {
        'data-widget-maximum-values': 4,
        'class': 'modern-style',
    }

class CourseAutoComplete(autocomplete_light.AutocompleteModelBase):
    search_fields = ['^name', ]
    choices = Course.objects.select_related('topics_required')
    widget_attrs = {
        'data-widget-maximum-values': 4,
        'class': 'modern-style',
    }

autocomplete_light.register(Topic, TopicAutoComplete)
autocomplete_light.register(CourseTopic, CourseTopicAutoComplete)
autocomplete_light.register(Course, CourseAutoComplete)


class CourseTopicForm(autocomplete_light.ModelForm):
    class Meta:
        model = CourseTopic
        exclude = ()


class CourseForm(autocomplete_light.ModelForm):
    class Meta:
        model = Course
        exclude = ()
```

Does that look right to you? What am I missing?

**Comment by pbassut** [comment]
Hey, this issue is not related to DAL a long time ago. I wanted to thank you for your help so far.

**Comment by jpic** [comment]
Let's see, what's the SQL query you've got 60 times with a different parameter like?

**Comment by pbassut** [comment]
```select ... from topic where topic.id in (id_here) order by 'ordering' ASC.```

**Comment by jpic** [comment]
Sorry I forgot about this, did you figure it out ? Can we close this issue ?

**Comment by jpic** [comment]
Unrelated to DAL and debugged anyway

**Comment by djshen-ponddy** [comment]
QuerySetSelectMixin.filter_choices_to_render generates these queries. A new queryset will be created if we call queryset.filter.
Maybe we can reduce queries here.

**Comment by jpic** [comment]
Maybe, it would be nice to see what such a patch would look like.

**Comment by djshen-ponddy** [comment]
https://github.com/djshen-ponddy/autocomplete
The result of filter_choices_to_render is the same as a list of select_related or prefetch_related objects.
And the choices of ModelChoiceField/ModelMultipleChoiceField is not necessary to be ModelChoiceIterator, so I replace the choices with prefetched objects to avoid querying again.

**Comment by jpic** [comment]
I don't even know where to look at in your repo. Could you try to make a more minimal patch please ? Something made "easy to review" would be awesome !
