### ISSUE TITLE
Custom default manager with filters by request/site

### ISSUE THREAD

**Issue by aibon** [yourlabs/django-autocomplete-light#518]
I'm trying to get the following to work: 

M2M Field, filtered by site (determined during request by subdomain). A custom default manager which does all the filtering takes care of that.

Autocomplete's registry picks up the default manager (with wrong filters), so i'm overriding choices_for_request and [clean() will raise a ValidationError]
(https://github.com/yourlabs/django-autocomplete-light/blob/d87a3ba8be745ff3e5142d9438f3b8318f4bf547/docs/source/autocomplete.rst#overriding-the-queryset-of-a-model-autocomplete-to-secure-an-autocomplete).

Is there a place where i can override the queryset used by django for validation? Of course I could change the default manager back and rewrite all relevant parts in my code to use another manager, but that really seems like the wrong way around.

**Comment by jpic** [comment]
I think overriding choices_for_values would help ;)

**Comment by aibon** [comment]
thanks, i have overriden __init__ and simply set self.choices to the right queryset, which also takes care of choices_for_values.  when debugging choices_for_values returns the right values, but still, i get a validationerror. changing back the to default manager works, so there must be some place where django gets the queryset. somewhere during registry? and it seems i can't set it on the field like in djangos's formfield. sorry to bother you, but i can't figure this bugger out..

**Comment by jpic** [comment]
This should be what raises the ValidationError: https://github.com/yourlabs/django-autocomplete-light/blob/master/autocomplete_light/fields.py#L48

Hope this helps !

**Comment by jpic** [comment]
This might be caused by https://github.com/yourlabs/django-autocomplete-light/blob/master/autocomplete_light/fields.py#L54 ... Either make a PR to replace that call with a required check, either set the queryset in the form field constructor...

**Comment by aibon** [comment]
thanks again, but validate() isn't called at all in my debugging session. I'm hitting this Error when saving the Form, perhaps because it's a inline in a Adminform. And it does not matter if i use AutocompleteModelBase and set choices in init or if i add a queryset parameter in the ModelChoiceField Constructor (which should be equal and just another way of registering?)

**Comment by aibon** [comment]
Finally found it, as it's a m2m modelchoice field, i had to define a inline adminform and override the queryset of the through field in init. it's working now like a charm. thanks again for your help and of course this fine package.
