### ISSUE TITLE
Admin demo seems broken

### ISSUE THREAD

**Issue by getup8** [yourlabs/django-autocomplete-light#519]
http://jpic.pythonanywhere.com/admin/

Site matching query does not exist.

**Comment by mpasternak** [comment]
+1

**Comment by jpic** [comment]
I'm going to setup continuous deployment from travis to openshift like i did for political-memory and add a cron to reset the db, thanks for reporting.

**Comment by jpic** [comment]
This is fixed by #524, new demo url: http://dal-yourlabs.rhcloud.com
