### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by Six-wars** [yourlabs/django-autocomplete-light#527]
Hi,
I have django-autocomplete-light==2.0.0a18 with django 1.7 installed I'd like to know if they're compatible since when I run makemigrations I get the following error

/home/kbuzz/lib/python2.7/autocomplete_light/forms.py:266: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form ModelForm needs updating
  attrs)

/home/kbuzz/lib/python2.7/autocomplete_light/forms.py:448: RemovedInDjango18Warning: Calling modelform_factory without defining 'fields' or 'exclude' explicitly is deprecated
  return django_modelform_factory(model, **kwargs)

/home/kbuzz/lib/python2.7/autocomplete_light/forms.py:266: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form CategoryForm needs updating
  attrs)

/home/kbuzz/lib/python2.7/autocomplete_light/forms.py:266: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form AreaForm needs updating
  attrs)

/home/kbuzz/lib/python2.7/autocomplete_light/forms.py:266: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form ArticleForm needs updating
  attrs)

/home/kbuzz/lib/python2.7/autocomplete_light/forms.py:266: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form BannerForm needs updating
  attrs)

/home/kbuzz/lib/python2.7/autocomplete_light/forms.py:266: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form VenueForm needs updating
  attrs)

**Comment by Six-wars** [comment]
I've upgraded it to 2.0.2 it has support for 1.7 but I keep getting the error messages

**Comment by jpic** [comment]
These warnings are fixed in better versions of django-autocomplete-light, can you install latest version please ?

Backward compatibility breaks, if any, **are** documented in CHANGELOG ;)

**Comment by jpic** [comment]
To remove Django 1.8 warnings, you need a version with 1.8 support.

**Comment by jpic** [comment]
BC breaks for upgrading are here: http://blog.yourlabs.org/post/119860038918/django-autocomplete-light-220rc1-release-notes

Please reopen if you have any other question.
