### ISSUE TITLE
widget attribute to not highlight the first choice when autocompleting

### ISSUE THREAD

**Issue by pandabuilder** [yourlabs/django-autocomplete-light#532]
When autocomplete is going on a ChoiceField, it auto highlights the first choice. I would like an option so that the options are highlighted only if using the UP, DOWN keys or by clicking, so that the Field doesn't lose focus.

**Comment by jpic** [comment]
Can't we highlight the first choice and not loose the focus on the input ?

**Comment by blueyed** [comment]
> Can't we highlight the first choice and not loose the focus on the input ?

Then it's maybe confusing what Return/Enter would do?!  Should it submit the existing value (from the input field) or the highlighted entry?
I think highlighting indicates selection somehow, and that's what @pandabuilder wants to avoid.

**Comment by jpic** [comment]
Yep, that was meant as a shortcut, but it's far from the first time we get
complaints about it.

Shouldn't we just remove auto-highlight of first choice ?

**Comment by pandabuilder** [comment]
Sorry, I now know that there's a autoHighlightFirst parameter that I can override from Python, but not setting it as a boolean, but using:

'data-autocomplete-auto-hilight-first': 0

As an integer.

This can be closed.

**Comment by jpic** [comment]
I wonder if we should default to this, what's your take on this ?

**Comment by pandabuilder** [comment]
Defaulting to 0 should be in line with most autocompletes on the web.

**Comment by jpic** [comment]
Cool, would you like to make a pr for that in jquery-autocomplete-light
mate ? ;)

**Comment by pandabuilder** [comment]
Here: yourlabs/jquery-autocomplete-light/pull/14

**Comment by jpic** [comment]
Merged, thanks a heap B)​

**Comment by jpic** [comment]
Released in 2.3.0
