### ISSUE TITLE
Front-end behaviour (CTRL-click, middle-click)

### ISSUE THREAD

**Issue by thebao** [yourlabs/django-autocomplete-light#535]
Thanks for the good work.
I'm having trouble coming up with a way to open search results in a new tab/window.
For example:
- Shift+Click opens results in current window instead of a new window
- Control+Click opens in results in current tab instead of a new tab

The code i'm using is:

    $('.autocomplete').each(function(){
        var i = $(this);

        var autocomplete = $('.autocomplete').yourlabsAutocomplete({
            url: i.attr('data-url'),
            container:$("#search").parent(),
            minimumCharacters: 1,
            autoHilightFirst: false,
            choiceSelector: 'a',
            }).input.bind('selectChoice', function(e, choice, autocomplete) {
            window.location.href = choice.attr('href');
        });
    });

Obvious culprit is binding the 'selectChoice' event to *window.location.href*
I was wondering if anyone had found a workaround.
Thanks and sorry if I missed anything obvious

**Comment by jpic** [comment]
Does it work maybe if you remove that line ?

https://github.com/yourlabs/jquery-autocomplete-light/blob/master/src/autocomplete.js#L360

On Mon, Dec 7, 2015 at 4:00 PM, thebao <notifications@github.com> wrote:

> Thanks for the good work.
> I'm having trouble coming up with a way to open search results in a new
> tab/window.
> For example:
>
>    - Shift+Click opens results in current window instead of a new window
>    - Control+Click opens in results in current tab instead of a new tab
>
> The code i'm using is:
>
> $('.autocomplete').each(function(){
>     var i = $(this);
>
>     var autocomplete = $('.autocomplete').yourlabsAutocomplete({
>         url: i.attr('data-url'),
>         container:$("#search").parent(),
>         minimumCharacters: 1,
>         autoHilightFirst: false,
>         choiceSelector: 'a',
>         }).input.bind('selectChoice', function(e, choice, autocomplete) {
>         window.location.href = choice.attr('href');
>     });
> });
>
> Obvious culprit is binding the 'selectChoice' event to
> *window.location.href*
> I was wondering if anyone had found a workaround.
> Thanks and sorry if I missed anything obvious
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yourlabs/django-autocomplete-light/issues/535>.
>



-- 
http://yourlabs.org <http://blog.yourlabs.org>
Customer is king - Le client est roi - El cliente es rey.

**Comment by thebao** [comment]
Yes! This solves the issue.
Thanks for the prompt reply. Can we hope to see this in a future release?
Thanks again for the good work

**Comment by jpic** [comment]
Niceeeee !

Well, if you decide to make a pr which extracts the bind calls in a
separate method, you'd be able to override it in your project:
http://django-autocomplete-light.readthedocs.org/en/master/faq.html#how-to-override-a-js-method

**Comment by thebao** [comment]
I've created a pull request on https://github.com/yourlabs/jquery-autocomplete-light

**Comment by jpic** [comment]
Merged, keep up the great work !
