### ISSUE TITLE
[question] browse relateds objects

### ISSUE THREAD

**Issue by gilgamezh** [yourlabs/django-autocomplete-light#544]
I would like to browse related objects in addition to search/add-another . like the raw_id_field widget in the admin.

Is it possible with django-autocomplete-light?

Thanks!

**Comment by jpic** [comment]
I have answered that on stackoverlfow.

http://stackoverflow.com/questions/34439777/is-possible-with-django-autocomplete-ligth-to-browse-relateds-objects/34561811#34561811
