### ISSUE TITLE
ForeignKey and GenericKey autocomplete will not be active simultaneously at the same model

### ISSUE THREAD

**Issue by raratiru** [yourlabs/django-autocomplete-light#550]
I have a model with a GenericKey and a ForeignKey.

The autocomplete initiates for the ```content_object``` field but not for the ```foreignkey``` field. 

If I exclude the ```content_object``` field using the ```admin.py```, then the ```foreignkey``` field autocomplete is active.

I would like to have both fields active as autocompletes. Here are the relevant files somehow abbreviated. 

Am I doing something wrong or this is not possible? 

models.py:

    class OneModel(models.Model):
        ...

    class GenericModel(models.Model):
        towards = {'app_label__in': ('myapp',), 'model__in': ('entity', 'contents', ), }
        content_type = models.ForeignKey(ContentType,  limit_choices_to=towards, )
        object_id = models.PositiveIntegerField()
        content_object = GenericForeignKey('content_type', 'object_id')
        ...
        another_foreignkey = models.ForeignKey(OneModel)

    class Entity(models.model):
        ...
        generic_model_reverse = GenericRelation(GenericModel)

    class Contents(models.model):
        ...
        generic_model_reverse = GenericRelation(GenericModel)

autocomplete_light_registry.py:

    class OneModelAutocomplete (autocomplete_light.AutocompleteModelBase):
        search_fields = ['id']
        model = OneModel
        autocomplete_js_attributes = {'placeholder': 'Start Searching', }

    autocomplete_light.register(OneModel, OneModelAutocomplete)    

    class EntityAutocomplete (autocomplete_light.AutocompleteModelBase):
        search_fields = ['id']
        model = Entity
        autocomplete_js_attributes = {'placeholder': 'Start Searching', }

    autocomplete_light.register(Entity, EntityAutocomplete)

    class AutocompleteGeneric(autocomplete_light.AutocompleteGenericBase):
        choices = (
            Entity.objects.all(),
            Contents.objects.all()
        )

        search_fields = (
            ('id', 'barcode', 'title', ),
            ('id', ),
        )

    autocomplete_light.register(AutocompleteGeneric)

admin.py:

    class OneModelAdmin (admin.ModelAdmin):
        form = autocomplete_light.modelform_factory(
            GenericModel,
            autocomplete_names={
                'another_foreignkey': 'OneModelAutocomplete',
            },
            fields='__all__',
        )
        save_as = True

    admin.site.register(OneModel, OneModelAdmin)

**Comment by jpic** [comment]
Interresting, I could reproduce this.

**Comment by jpic** [comment]
Even more interesting, isn't that test case exactly your situation ?

https://github.com/yourlabs/django-autocomplete-light/blob/master/autocomplete_light/tests/test_forms.py#L259-L278

**Comment by jpic** [comment]
Meanwhile, you could create a ModelForm class manually and use the autocomplete fields directly.

**Comment by jpic** [comment]
That's an heisenbug inside the admin.

Workaround seems to be:

```
    class ModelForm(autocomplete_light.ModelForm):
        noise = autocomplete_light.GenericModelChoiceField(required=False)

        class Meta:
            model = model
            exclude = ['object_id', 'contet_type']
            widgets = {
                'relation': autocomplete_light.ChoiceWidget('GfkModelAutocomplete')
            }
```

**Comment by raratiru** [comment]
Answers sorted by difficulty level!

> What version of python and django do you have ?

```Python 3.4.2```
```
$ pip freeze
amqp==1.4.9
anyjson==0.3.3
billiard==3.3.0.22
celery==3.1.19
decorator==4.0.6
diff-match-patch==20121119
Django==1.8.8
django-autocomplete-light==2.2.10
django-autoslug==1.9.3
django-import-export==0.4.2
django-modeltranslation==0.10.2
django-reversion==1.10.0
django-suit==0.2.15
ipdb==0.8.1
ipython==4.0.1
ipython-genutils==0.1.0
kombu==3.0.33
path.py==8.1.2
pexpect==4.0.1
pickleshare==0.5
psycopg2==2.6.1
ptyprocess==0.5
pytz==2015.7
requests==2.9.1
simplegeneric==0.8.1
six==1.10.0
solid-i18n==1.1.1
tablib==0.10.0
traitlets==4.0.0
```
OK! I was about to write that I will try the manual field definition and I saw the new post. I will get to try it!
