### ISSUE TITLE
How to filter choices based on form.instance attributes

### ISSUE THREAD

**Issue by gdsahin** [yourlabs/django-autocomplete-light#552]
This is a dublicate of the following:
http://stackoverflow.com/q/34719568/857314

I start this issue to make sure the question is noticed.
In addition to stackoverflow post, I have tried the choices_for_request method but i could not manage to access form.instance from request object.
No success.
I would appriciate any response.

**Comment by jpic** [comment]
choices_for_request is indeed the method called by the autocomplete view.

you should add the instance id to the request, just add it to $('your-selector-for-the-widget .autocomplete-light-widget').yourlabsWidget().autocomplete.data.

INspiration here: http://django-autocomplete-light.readthedocs.org/en/master/dependant.html#javascript

**Comment by jpic** [comment]
Question has been answered with details, closing.

**Comment by jpic** [comment]
Do you think you could contribute some documentation ? I'm sure it would help a bunch !

**Comment by gdsahin** [comment]
Well, based on your answer on stackoverflow i managed to achieve it and i reported every detail [here](http://stackoverflow.com/questions/34719568/how-can-i-filter-autocomplete-queryset-by-form-instance-attributes)
Thanks again.
And for the documentation it would be great if i can help, have never done it before though!
How does it work?
