### ISSUE TITLE
Better import alias

### ISSUE THREAD

**Issue by lampslave** [yourlabs/django-autocomplete-light#556]
How about `autocomplete` instead of `al`?

```python
import autocomplete_light.shortcuts as autocomplete
```

**Comment by jpic** [comment]
Isn't that what we have in docs already ?

http://django-autocomplete-light.readthedocs.org/en/master/tutorial.html#autocomplete-light-register-shortcut-to-generate-and-register-autocomplete-classes

**Comment by lampslave** [comment]
We have `import autocomplete_light.shortcuts as al` in tutorial and `from autocomplete_light import shortcuts as autocomplete_light` in readme instead of `import autocomplete_light.shortcuts as autocomplete`.

**Comment by jpic** [comment]
Oops, didn't get it ! I'm not against it, @blueyed @luzfcb @mpasternak what do you think ?

**Comment by blueyed** [comment]
:+1:

**Comment by blueyed** [comment]
@lampslave 
Do you want to create a PR for this?

**Comment by jpic** [comment]
Are you sure it's worth the effort ? docs are subject to rewrtting anyway, it's completely different in [v3](https://github.com/yourlabs/django-autocomplete-light/blob/v3/README) which should be released sooner than you think.

**Comment by lampslave** [comment]
@blueyed
Yes, but I'm little busy now. I'll do it in few days.

**Comment by blueyed** [comment]
@jpic 
Good point.  However, that might take a while to be the stable version and then it's good to have in-between.
However, I would not put too much effort in it myself.

@lampslave 
Please create a PR - closing this issue for now.

**Comment by mpasternak** [comment]
I use IDEs and I don't really care how much do I have to type (I use autocomplete features), so I have no opinion here.

**Comment by jpic** [comment]
Thanks for answering @mpasternak 

@blueyed beta release for v3 is half complete (i've removed all code except essentials). We'll still support v2 for like a year or two I guess, but if people hit weird bugs it'll be easier for them to use v3, and easier for us to test the variety of use cases users have come up with - or rather, more straight forward for them to contribute an example app which we can add functional tests in, ie. https://github.com/yourlabs/django-autocomplete-light/blob/v3/test_project/select2_foreign_key/test_functional.py
