### ISSUE TITLE
Memory use in Actionform

### ISSUE THREAD

**Issue by jorisvd** [yourlabs/django-autocomplete-light#561]
I suddenly noticed my Django processes memory use stretching out like a chewing gum on viagra,  using 500 MB each instead of 50 MB before, bringing the whole server down, and some research led to this autocomplete light.

I was using Autocomplete Light in an actionform:

class ArticleActionForm(ActionForm):
	import autocomplete_light
	article_id = autocomplete_light.ChoiceField('ArticleAutocomplete')

I'm not 100% sure that this use is officially supported, but it caused to preload all articles (several million) into memory on process startup (without even viewing the form).

I'd appreciate somemone could comment this is a bug or whether I'm using the thing wrong.

Thanks
Joris

**Comment by jpic** [comment]
Yeah, you're using ChoiceField instead of ModelChoiceField, that's what's wrong.

ChoiceField renders all options :dancer:

**Comment by jpic** [comment]
Perhaps you'd consider this a bug, but that's fixed in v3 already, you might want to backport it: https://github.com/yourlabs/django-autocomplete-light/blob/v3/src/dal/widgets.py#L43-L51

**Comment by jorisvd** [comment]
Great! Thanks for your feedback!
