### ISSUE TITLE
list showing only 20 items.

### ISSUE THREAD

**Issue by sushovan23** [yourlabs/django-autocomplete-light#562]
0
down vote
favorite
I integrated autocomplete light with my django app.

In my registry i'm doing the following:

class HostAutocomplete( autocomplete_light.AutocompleteModelBase ):
    search_fields = [ 'hostname' ]
    choices = Host.objects.all()
In my form i have:

hosts=autocomplete_light.MultipleChoiceField('HostAutocomplete')
Autoocomplete is working fine but the list which i'm getting contains only 20 items. Database has many more entries. What could be the issue?

**Comment by jpic** [comment]
http://django-autocomplete-light.readthedocs.org/en/master/api.html#autocomplete_light.autocomplete.model.AutocompleteModel.limit_choices

**Comment by sushovan23** [comment]
thank you
