### ISSUE TITLE
Many to Many field widget will not work after 2.2.10 up to 2.3.2

### ISSUE THREAD

**Issue by raratiru** [yourlabs/django-autocomplete-light#563]
**Working setup:**

    Python 3.4
    Django 1.8.8
    django-autocomplete-light 2.2.10

Works as expected. In a many to many field:

After autocompleting a value, another field appears which allows the user to enter another value.

**Not working when:**

Upgrading to ```django-autocomplete-light 2.3.2```, the second field appears but it is disabled. 

One, cannot enter any value to the second field.

**Comment by jpic** [comment]
Could you add your use case in an app in the test_project please ?

Thanks !

**Comment by jpic** [comment]
I thought this would have fixed it: https://github.com/yourlabs/jquery-autocomplete-light/commit/eb72ccaf1c2a5b2b8243fa02ed134f061ebb5b0e

**Comment by jpic** [comment]
Was probably introduced by: https://github.com/yourlabs/jquery-autocomplete-light/commit/10b6ca87fa1070aa652a610c24be98b7cc2f9f6e

**Comment by raratiru** [comment]
Thank you, I saw in the changelog that

> 2.3.2 JAL#20 Don't disable multiplechoicewidgets by @JaHicks

and this made me try the older versions. 

I made a pull request of my use case.

**Comment by jpic** [comment]
Could you test the fix in JAL master please ?

**Comment by jpic** [comment]
I think this is fixed in 2.3.3 release, could you try to upgrade please ?
thanks !

**Comment by raratiru** [comment]
Yes, thank you, it works great!

**Comment by jpic** [comment]
:guitar:
