### ISSUE TITLE
test_project can not load static files on Windows

### ISSUE THREAD

**Issue by FaBay89** [yourlabs/django-autocomplete-light#565]
Django server is running, admin site is available, but all static files from 
_/static/collected/autocomplete_light/*_ return _404 Not found error_.

On Ubuntu there is no problem. Also no problem in my own project on Windows.

System:
Windows 8.1
Firefox 44.0
Python 3.4.3
Django 1.9.1
django-autocomplete-light 2.3.3

**Comment by jpic** [comment]
This is a problem you have with django, not with autocomplete light.

See [ensure understanding of staticfiles](http://django-autocomplete-light.readthedocs.org/en/master/install.html#ensure-you-understand-django-contrib-staticfiles) in the install docs.

**Comment by FaBay89** [comment]
Ok found the issue, i used "django-autocomplete-light" as project folder, and the linked folder at 
"django-autocomplete-light/autocomplete_light/static/(autocomplete_light)" does not work on Windows.

My IDE add the project folder to PYTHONPATH. With "test_project" as project folder it works. 

Thank you
