### ISSUE TITLE
Docs use old import paths

### ISSUE THREAD

**Issue by guettli** [yourlabs/django-autocomplete-light#566]
I am confused. The docs sometimes use autocomplete_light.register(), sometimes autocomplete_light.shortcuts.register()

Same for ModelForm: autocomplete_light.ModelForm can't be imported on my system:

```
Django==1.9.1
django-autocomplete-light==2.3.3

```

http://django-autocomplete-light.readthedocs.org/en/master/tutorial.html

**Comment by blueyed** [comment]
See http://django-autocomplete-light.readthedocs.org/en/master/index.html#projects-upgrading-to-django-1-9 (which could be improved).

A PR to fix the documentation would be appreciated.

**Comment by jpic** [comment]
If you're doing a new project, may I suggest you try the v3 branch.

Best

**Comment by jpic** [comment]
This was fixed wasn't it ?

**Comment by guettli** [comment]
yes, "autocomplete_light" seems gone.

Wait .... 

There are still some matches:

https://github.com/yourlabs/django-autocomplete-light/search?utf8=%E2%9C%93&q=autocomplete_light

@jpic can you please check above matches and then close this issue? Thank you

**Comment by jpic** [comment]
I removed test.sh, the rest of the matches seem ok to me.

Thanks !
