### ISSUE TITLE
Autocomplete wont allow me to add more than one value

### ISSUE THREAD

**Issue by Visgean** [yourlabs/django-autocomplete-light#572]
I have following autocomplete:

```python
class AutocompleteSource(autocomplete.AutocompleteModelBase):
    choices = Source.objects.filter(active=True)
    search_fields = ['^name']
    attrs = {
        'placeholder': _('Source'),
        'data-autocomplete-minimum-characters': 1,
    }
```

and following form: 
```python 
class HarvestEditForm(autocomplete_light.ModelForm):
    class Meta:
        model = Harvest
        fields = [
            'scheduled_on',
            'title',
            'target_frequency',
            'custom_seeds',
            'custom_sources',
        ]
```

The harvest has ManyToManyField relation to Source, but when the form is rendered it only allows me to add/edit only one item. How should I change that?

btw you can view the source here: https://github.com/WebArchivCZ/Seeder/blob/master/Seeder/harvests/forms.py#L17

**Comment by jpic** [comment]
>  it only allows me to add/edit only one item. 

What happens when you try ?

Would you like to try with DAL v3 ? I'm sure it would work.

**Comment by Visgean** [comment]
It disables the html element... I will try to upgrade to new version.

**Comment by Visgean** [comment]
Wow migrating from 2x version is a bit more complicated than I thought, I can see why you bumped the version the 3x version. Is there some manual how to to do this properly? Seems that now Autocompletes are custom class based views which I can see is reasonable.

**Comment by Visgean** [comment]
Well wow, the new version is really much better! I really like the idea of not having some custom magical view that can return anything from DB... Also loved how easy was it to set up forwarded autocomplete. Man really good work! Absolutely solved my problems.

**Comment by jpic** [comment]
Glad it worked for you, thanks for the kind words !
