### ISSUE TITLE
Pypi release of 3.0.0 missing .js files

### ISSUE THREAD

**Issue by rory-geoghegan-ecometrica** [yourlabs/django-autocomplete-light#573]
Hi,

I think something is wrong with your MANIFEST.in file for v3 because the .tar.gz on pypi is missing all static files. If I do the following:

curl https://pypi.python.org/packages/source/d/django-autocomplete-light/django-autocomplete-light-3.0.0.tar.gz | tar tf - | grep js

I see nothing.

**Comment by jpic** [comment]
Thanks for reporting !
