### ISSUE TITLE
Creating new tags using django-taggit and dal v3

### ISSUE THREAD

**Issue by Athemis** [yourlabs/django-autocomplete-light#575]
Hi, I'm trying to use fresh dal v3 for adding autocompletion of tags to my project. I was following the tutorial in the documentation (btw. i guess there's an error in the tutorial, see pull request #574). It's working smoothly now, but only for already existing tags. I've not been able to create new tags so far.

Django log output suggests that I somehow need to set a GET variable "create" to "true":
`[04/Feb/2016 20:44:08] "GET /eln/tag-autocomplete/?q=pro&create=false HTTP/1.1" 200 30`

Am I right? Any suggestion how to do that? I haven't found anything in the documentation so far.

Thanks for your efforts! Cheers,
Alex

**Comment by jpic** [comment]
Hi, create will just make the view propose a "Create ..." choice, which select2 in tag mode does for you. To create choices on the fly, it's the [CreateModelMultipleField](http://django-autocomplete-light.readthedocs.org/en/master/creation.html), which is already inherited from on TaggitField.

Are you able to reproduce this on the demo site ?

http://dal-yourlabs.rhcloud.com/admin/select2_taggit/testmodel/add/

What browser are you using ?

**Comment by Athemis** [comment]
It works on the demo site, but it also works in the admin panel of my project. Where it did not work was on any other form outside the admin panel. I was able to solve that problem by including the autocompleted fields in the "fields" list of the Meta class as well:


    class EditForm(autocomplete.FutureModelForm):

        tags = autocomplete.TaggitField(required=False, widget=BootstrapTagSelect2(url='some-url'))

        class Meta:
            model = MyModel
            fields = ['some_field', 'some_other', 'tags']

I was of the opinion that this should not be needed, if I redefine the field? Btw. I used Firefox 44 and Chromium.

Cheers,
Alex

**Comment by jpic** [comment]
Holy cow, it should really not change anything to add the field there in Meta, is there any way you can reproduce it in the test project ?

**Comment by Athemis** [comment]
I'll try to reproduce this issue in the test project asap.

**Comment by jpic** [comment]
Please reopen if you're able to reproduce this issue ;)

**Comment by jpic** [comment]
Also, note that the way tags are supported have slightly changed in 3.1 #609
