### ISSUE TITLE
Select2 placeholder not working

### ISSUE THREAD

**Issue by kliver** [yourlabs/django-autocomplete-light#583]
I've set placeholder in attrs as in any django widget but it not works. Maybe the problem is this:

https://github.com/yourlabs/django-autocomplete-light/compare/master...kliver:patch-1

**Comment by kevin-brown** [comment]
If you are using Select2 with a `<select>`, then the only (valid) way to set the placeholder using an attribute is with the `data-placeholder` attribute. The regular `placeholder` attribute is not valid for a `<select>`.

https://github.com/select2/select2/issues/4059#issuecomment-169036131

**Comment by jpic** [comment]
Thanks @kevin-brown, does that still work in v4 ?

We've got an on-going PR #585 which sets up the placeholder attribute as in select2 v4 [docs](https://select2.github.io/examples.html#placeholders), but if we can use the data-placeholder attribute directly it's even better !

**Comment by jpic** [comment]
My bad, I didn't understand what you were saying exactly, @kliver can we
switch to data-placeholder ?

**Comment by kevin-brown** [comment]
> does that still work in v4 ?

Yup, the `placeholder` attribute used to work in v3 but was dropped when we switched to a `<select>`. The `data-*` attributes are supported [for all options in 4.0](https://select2.github.io/options.html#data-attributes).

> which sets up the placeholder attribute as in select2 v4 docs

Note that the wording in the docs is misleading, we're working on fixing that for the next release.

**Comment by jpic** [comment]
Thanks @kevin-brown ! Need to release the new select2 version soonish :guitar:
