### ISSUE TITLE
DAL works in admin but not in custom forms 

### ISSUE THREAD

**Issue by paxelito** [yourlabs/django-autocomplete-light#588]
I have carefully followed the tutorial and the autocomplete field is correctly rendered in admin but not within the forms in my custom template. The strange thing is that I'm using the same form in both cases. 

```python
class FieldAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        # Don't forget to filter out results depending on the visitor !
        if not self.request.user.is_authenticated():
            return mymodel.objects.none()

        qs = mymodel.objects.all()

        if self.q:
            qs = qs.filter(name__istartswith=self.q)

        return qs
```

then my form is something like 

```
    class Meta:
        model = mymodel
        
        fields = ('__all__')

        widgets = {
          'myfield': autocomplete.ModelSelect2(url='myfield-autocomplete')
        }
```

I use the same form both in admin and in my custom templates, in the former it works perfectly, but in the latter the dropdown menu (without any option) is shown. 

any idea?

thx in advance

**Comment by jpic** [comment]
Maybe check your JS console for errors. There's an [example](http://dal-yourlabs.rhcloud.com/select2_outside_admin/), [template](https://github.com/yourlabs/django-autocomplete-light/blob/master/test_project/templates/select2_outside_admin.html)

**Comment by jpic** [comment]
Turns out that example is not documented, it would be great if you could make a PR with docs for it.

**Comment by jpic** [comment]
#590 documents usage outside the admin.

**Comment by paxelito** [comment]
I confirm that moving form.media after JQuery everything works well also in very complex forms created with inlineformset_factory. Very nice work!!!

**Comment by jpic** [comment]
Awesome, thanks for reporting !!
