### ISSUE TITLE
jQuery and mezzanine 4.1.0 and autocomplete-light 2.3.3 in the same ship

### ISSUE THREAD

**Issue by frague59** [yourlabs/django-autocomplete-light#593]
Hi, 

I'm facing a jQuery dependencies problem with autocomplete 2.3.3. In the admin interface, I uses the mezzanine provided jQuery (1.8.3). It seams to be bound to 

`window.jQuery`

attribute. I'm trying to re-use this jQuery to load the autocomplete stuff with :

`{% include "autocomplete_light/static.html" %}`

I've done many tries with `noConflict`, but none seams to work, loading another version of jQuery (2.1.4) at mezzanine level, reloading jQuery before the include... and I'm still stuck.

Have you an idea on how to make it work ?
I've the message :
`TypeError: $(...).yourlabsWidget is not a function`

Thanks for your great job !

**Comment by boronine** [comment]
I just had to solve a similar error, it may be worthwhile for you to try the following hack.

Add these lines after your JavaScript imports:

```
    <script type="text/javascript">
        django.jQuery.fn.yourlabsWidget = jQuery.fn.yourlabsWidget;
    </script>
```

Not sure if related, just a suspicion.

**Comment by frague59** [comment]
Now I've lost the left menu in my admin ... I'm in hell, really ...

**Comment by frague59** [comment]
I've gone a bit. In fact ; the left menu is hidden : it's created (can see it in sources), but hidden : when I click on left border, the main form space in enlarged, the menu does not appears.

This menu is only hidden when I load page with autocomplete-activated forms, is changelist  views it appears correctly.

I've tryed the sef lines :
`
    <script type="text/javascript">
        django.jQuery.fn.yourlabsWidget = jQuery.fn.yourlabsWidget;
    </script>
`
and event tried at many places in the loading flow, but I've always the 
`TypeError: $(...).yourlabsWidget is not a function` error.


The code chunk : admin/base_site.html
`    
{% block extrahead %}
{# ... copy of mezzanine page  #}

    {% if debug %}
        <script src="{% static "jquery/dist/jquery.js" %}"></script>
    {% else %}
        <script src="{% static "jquery/dist/jquery.min.js" %}"></script>
    {% endif %}
    <script type="application/javascript">
        if (typeof (jQuery) != 'undefined') {
            window.$ = jQuery;
            console.debug('jQuery.fn.jquery = ' + jQuery.fn.jquery);
        }
    </script>
    {% include 'autocomplete_light/static.html' %}
    <script type="text/javascript">
        django.jQuery.fn.yourlabsWidget = jQuery.fn.yourlabsWidget;
    </script>
    
{% block extrahead %}
`

**Comment by jpic** [comment]
Instead, may i suggest that you override admin/jquery.init.js to remove
noConflict(true) perhaps ?

Or set up an example project so that we can try to debug it ?

Otherwise maybe try v3 ?

**Comment by frague59** [comment]
autocomplete works !!

I've put :
`
    {% include 'autocomplete_light/static.html' %}
    <script type="text/javascript">
        django.jQuery.fn.yourlabsWidget = jQuery.fn.yourlabsWidget;
    </script>
`
at the bottom of the **footer** block without any jQ reloading. But my left menu not yet...

**Comment by jpic** [comment]
:guitar: 

Please reopen if needed. The best would be to PR to add test_project/settings/mezzanine.py so we could even add it in CI.
