### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by tieugene** [yourlabs/django-autocomplete-light#596]
[Use the view in a Form widget](http://django-autocomplete-light.readthedocs.org/en/master/tutorial.html#use-the-view-in-a-form-widget):
birth_country = forms.ModelChoiceField(choices=...
ModelChoicesField has no 'choices' attribute: [proof](https://docs.djangoproject.com/en/1.8/ref/forms/fields/#modelchoicefield)

**Comment by jpic** [comment]
Yep, should be queryset, could you submit a PR please ?

**Comment by tieugene** [comment]
What is PR?

**Comment by jpic** [comment]
A Pull-Request of course !

 https://help.github.com/articles/creating-a-pull-request/​

Welcome on GitHub ;)

**Comment by Eraldo** [comment]
I created a patch branch to fix it.
Thank you @tieugene for letting us know. :D

**Comment by jpic** [comment]
Thanks a heap !!

You :guitar:
