### ISSUE TITLE
Incomplete and confusing documentation

### ISSUE THREAD

**Issue by mdemicheli** [yourlabs/django-autocomplete-light#599]
Is http://django-autocomplete-light.readthedocs.org/en/stable/ the official documentation? I tried to take a look at the Live demo but I've found a TemplateDoesNotExist error at "Example using select2 outside the admin".

On the other hand, it says that the project has Python 2.7+, Django 1.8+ complete support, but I've seen in www.djangopackages.com that it appears to have support for Python3.

Also, I've seen this many times (e.g. here http://django-autocomplete-light.readthedocs.org/en/stable/tutorial.html#create-an-autocomplete-view):
```
       qs = Country.objects.all()

        if self.q:
            qs = qs.filter(name__istartswith=self.q)

        return self.q
```

while it should be like this right?:
```
       qs = Country.objects.all()

        if self.q:
            qs = qs.filter(name__istartswith=self.q)

        return qs
```

**Comment by Visgean** [comment]
https://github.com/yourlabs/django-autocomplete-light/pull/580 if you have found some other inconsistencies please PR!

**Comment by jpic** [comment]
> Is http://django-autocomplete-light.readthedocs.org/en/stable/ the official documentation? I tried to take a look at the Live demo but I've found a TemplateDoesNotExist error at "Example using select2 outside the admin".

That was fixed.

**Comment by jpic** [comment]
All fixed, thanks !

**Comment by jpic** [comment]
And thanks a LOT @Visgean for contributing ! you :guitar:
