### ISSUE TITLE
ImportError: No module named autocomplete_light - django 1.9.2 + autocomplete_light=3.0.4

### ISSUE THREAD

**Issue by bemall** [yourlabs/django-autocomplete-light#600]
Djngo 1.9.2 + django_autocomplete_light=3.0.4
Please advise on the below error.. 
File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/bernard/.virtualenvs/hingex/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/username.virtualenvs/project/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/Users/username/.virtualenvs/project/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/username/.virtualenvs/project/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/username/.virtualenvs/project/lib/python2.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named autocomplete_light

**Comment by jpic** [comment]
Yeah v3 is backward compatible.

**Comment by bemall** [comment]
Yes thank you for verifying. Any feedback based on this trace?

**Comment by jpic** [comment]
My bad, I meant **not** backward compatible :)

**Comment by jpic** [comment]
Solution: pin `'django-autocomplete-light>=2.0,<3.0'` in requirements.

**Comment by ezawadzki** [comment]
Not working for me in Django 1.9.7. Still have : `ImportError: No module named 'dal'`

**Comment by jpic** [comment]
@ezawadzki it's working for me:

```
$ virtualenv /tmp/test
Using real prefix '/usr'
New python executable in /tmp/test/bin/python2
Also creating executable in /tmp/test/bin/python
Installing setuptools, pip, wheel...source done.

$ source /tmp/test/bin/activate

$ pip install django-autocomplete-light
Collecting django-autocomplete-light
  Downloading django-autocomplete-light-3.1.8.tar.gz (396kB)
    100% |████████████████████████████████| 397kB 803kB/s 
Building wheels for collected packages: django-autocomplete-light
  Running setup.py bdist_wheel for django-autocomplete-light ... done
  Stored in directory: /home/jpic/.cache/pip/wheels/0c/5b/66/1b93251a98a6a3b1cb6ce30c43ee457cb97d4130bf862dfdcf
Successfully built django-autocomplete-light
Installing collected packages: django-autocomplete-light
Successfully installed django-autocomplete-light-3.1.8
You are using pip version 8.0.0, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

$ python
Python 2.7.12 (default, Jun 28 2016, 08:31:05) 
[GCC 6.1.1 20160602] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import dal
>>> dal.__path__
['/tmp/test/lib/python2.7/site-packages/dal']
```

I suspect you're having another issue.

**Comment by ezawadzki** [comment]
I had to use dev version to make import working.

**Comment by jpic** [comment]
I'm sorry but unless you're able to provide more technical information, ie. virtualenv creation and dal install logs, I'm not able to help any further, because my crystal ball is at the garagist.

**Comment by ezawadzki** [comment]
Thanks for your help. I'm using Docker on Linux.
In requirements.txt, I tried to put
`django-autocomplete-light`
or 
`django-autocomplete-light>=2.2,<3.0`
After that I rebuilt my docker image with `--no-cache` option.
I'm log into docker bash of my app.

Tried to import dal :
```
root@99ae0d68d954:/srv/app# python
Python 3.5.1 (default, Jun  9 2016, 15:37:54) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'dal'
```

But instead putting something into requirements.txt, I tried dev version in requirements-dev.txt :

`-e git+https://github.com/yourlabs/django-autocomplete-light.git#egg=django-autocomplete-light
`
Then import worked. Maybe I've got specific issue with my docker.

**Comment by ezawadzki** [comment]
Here is the full Traceback :

> Traceback (most recent call last):
>   File "manage.py", line 8, in <module>
>     execute_from_command_line(sys.argv)
>   File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
>     utility.execute()
>   File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 327, in execute
>     django.setup()
>   File "/usr/local/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/usr/local/lib/python3.5/site-packages/django/apps/registry.py", line 85, in populate
>     app_config = AppConfig.create(entry)
>   File "/usr/local/lib/python3.5/site-packages/django/apps/config.py", line 90, in create
>     module = import_module(entry)
>   File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
> ImportError: No module named 'dal'
>

**Comment by jpic** [comment]
v2 and v3 are not compatible. v2 uses autocomplete_light module name, and v3 uses dal, to prevent any incompatible code from compiling at all and defering errors for users upgrading.

My question to you is: what version do you want to use ?

Also, what are the install logs ?

**Comment by ezawadzki** [comment]
Sorry, it was related to a script executed while I 'up' my image. We can delete all these useless messages. Thanks for your help.

**Comment by hamza-oua94** [comment]
C:\Users\hamza>pip install django-autocomplete-light==2.3.3
