### ISSUE TITLE
Live demos from pythonanywhere mostly broken

### ISSUE THREAD

**Issue by qrilka** [yourlabs/django-autocomplete-light#605]
I see django debug page for "admin demos" e.g.

**Comment by jpic** [comment]
Yeah, the new demo is at https://dal-yourlabs.rhcloud.com (for which we
have continuous deployment, and I just made a resource grant to be able to
host more demos for more versions).

Where did you find a link to the old demo ?

**Comment by qrilka** [comment]
See my message in #606 :)
And the link itself came from https://habrahabr.ru/post/187312/

**Comment by jpic** [comment]
Right, I should add a redirect there then, thanks for reporting !

**Comment by jpic** [comment]
Updated home page: http://jpic.pythonanywhere.com/

Thanks !
