### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by qrilka** [yourlabs/django-autocomplete-light#606]
Link "Edit on github" is referencing https://github.com/yourlabs/django-autocomplete-light/blob/stable/2.x.x/docs/source/index.rst which gives 404

**Comment by qrilka** [comment]
This and #605 are about http://django-autocomplete-light.readthedocs.org/en/latest/ which differs from http://django-autocomplete-light.readthedocs.org/en/master/ for some reason

**Comment by jpic** [comment]
I don't even see them links.

**Comment by jpic** [comment]
Does this still occur ?

**Comment by qrilka** [comment]
Looks OK now to me

**Comment by jpic** [comment]
Thanks for your feedback :guitar:
