### ISSUE TITLE
ValueError at [...] invalid literal for int() with base 10: 'test78'

### ISSUE THREAD

**Issue by djayp83** [yourlabs/django-autocomplete-light#608]
Hi,
When trying to create a new item, but leaving another mandatory field empty, the following error appears: 
_ValueError at /admin/select2_one_to_one/testmodel/51/change/
invalid literal for int() with base 10: 'test78'_

This is easily reproductible on the demo site:
- Let the field "Name" empty
- Enter a non existing item in test field and select: Create "whatEverDoNotExit"
- Click on the Save button

It looks like this bug [was previously solved](https://github.com/yourlabs/django-autocomplete-light/issues/62), but it occurs again in current version.

Best

**Comment by jpic** [comment]
Very interresting indeed, I think the best solution here is to move the
logic inside CreateModelField* clean() methods inside WidgetMixin's
value_from_datadict(), what do you think ?

**Comment by jpic** [comment]
Could you try with PR #609 please ?

Note that it's not compatible, but fixes the issue for sure.

**Comment by jpic** [comment]
Closing in favor of #609
