### ISSUE TITLE
Black square when renders selected items of a many to many autocomplete

### ISSUE THREAD

**Issue by miqfrontera** [yourlabs/django-autocomplete-light#610]
Hi all,

I'm using version 3.0.4 of **dal** with **django** 1.8.8. I use it for some autocompletes in the admin and for many to many appears a strange black square:

![dal-black-square](https://cloud.githubusercontent.com/assets/1699980/13435479/db5cea22-dfda-11e5-8694-6df53c0ea6a3.png)

It only happens for the  many to many one. I have some normal autocompletes, ModelSelect2, and the black square does not appears. It is rendered on firefox and chrome browsers.

Somebody has experienced the same issue? Any idea of a possible solution?

Kind regards.

**Comment by jpic** [comment]
Hi, could you try with #611 and see if that fixes the problem for you ?

**Comment by miqfrontera** [comment]
Yeah! It worked!

Thank you so much ;-)

**Comment by jpic** [comment]
A bugfix has been submitted upstream: https://github.com/select2/select2/pull/4226

**Comment by jpic** [comment]
Closing in favor of #611.

Release imminent ;)

**Comment by jpic** [comment]
Fix released in 3.1.2

**Comment by miqfrontera** [comment]
I've recently updated my project with the latest release and it works perfect.

Good job ;-)
