### ISSUE TITLE
Sphinx Docs: [next] [prev] buttons missing

### ISSUE THREAD

**Issue by guettli** [yourlabs/django-autocomplete-light#612]
For some strange reason the usual [next] [prev] buttons are missing in the sphinx docs:

http://django-autocomplete-light.readthedocs.org/en/master/install.html

**Comment by jpic** [comment]
Apparently that's because of the template​.

**Comment by jpic** [comment]
Yep, that template is a lot better !

http://django-autocomplete-light.readthedocs.org/en/documentation/

Closing in favor of #616
