### ISSUE TITLE
Docs: typo

### ISSUE THREAD

**Issue by guettli** [yourlabs/django-autocomplete-light#613]
Here is a typo:

> we can use the CreateModelField`` form field, ie:

... there are two back-ticks

http://django-autocomplete-light.readthedocs.org/en/master/creation.html

**Comment by jpic** [comment]
That doc is removed in next release #609​

**Comment by jpic** [comment]
Yep, it's gone, be careful, it has changed in 3.1: http://django-autocomplete-light.readthedocs.org/en/documentation/tutorial.html#creation-of-new-choices-in-the-autocomplete-form (release iminent).
