### ISSUE TITLE
Docs suggestions

### ISSUE THREAD

**Issue by jonashaag** [yourlabs/django-autocomplete-light#615]
> Suppose we have a Country Model which we want to provide a Select2 autocomplete widget for in a form. If a users types an “f” it would propose “Fiji”, “Finland” and “France”

A simple screenshot would explain this with zero words.

**Comment by jonashaag** [comment]
> For more complex filtering, refer to official documentation for the QuerySet API.

These are absolute Django basics and don't need to be taught in a tutorial.

**Comment by jonashaag** [comment]
> Ensure that the url can be reversed, ie: [...]

This goes without saying.

**Comment by jonashaag** [comment]
> We can now use the autocomplete view our Person form, for its birth_country field that’s a ForeignKey

Again, how about a screen shot?

**Comment by jonashaag** [comment]
> One way to do it is by overriding the form field, ie:

I'd stay with one way to do it in a tutorial.

**Comment by jonashaag** [comment]
> If we need the country autocomplete view for a widget used for a ManyToMany relation instead of a ForeignKey, with a model like that:

This should get an extra headline/section.

**Comment by jonashaag** [comment]
Otherwise, nice tutorial!

**Comment by jonashaag** [comment]
(Btw, from what I can tell from reading through the tutorial, v3 feels a LOT more sane than v2 in terms of API/complexity!)

**Comment by jpic** [comment]
Added a bunch of screenshots, and links to examples and demos.

Thanks !

http://django-autocomplete-light.readthedocs.org/en/master/tutorial.html
