### ISSUE TITLE
dal is not zip safe

### ISSUE THREAD

**Issue by guettli** [yourlabs/django-autocomplete-light#618]
First I installed dal indirectly via `python setup.py develop`.

For some strange reason dal gets installed as zipped egg if you install it this way.

This means the python code works, but the static files can't be found and this means the js files don't get found.

I suggest you use zip-safe=False in setup.py.

**Comment by maplemike** [comment]
Going from django-autocomplete-light==3.0.4 to django-autocomplete-light==3.1.0

The 'vendor' folder is missing in dal_select2/static/autocomplete_light/vendor when installed with pip. I'm not sure if this is related or not.

**Comment by gusreyes01** [comment]
@maplemike  I'm having the same Issue. Vendor folder is not present. I've tried pip and `python setup.py install `

**Comment by guettli** [comment]
I think these are two unrelated issues. 

But I was having the same issue with files located in the 'vendor' directory. I created an other issue for this: #620

**Comment by guettli** [comment]
zip_safe=False is already in setup.py. Closing this.
