### ISSUE TITLE
ValueError: "invalid literal for int() with base 10" when submitting an empty form POST

### ISSUE THREAD

**Issue by migajek** [yourlabs/django-autocomplete-light#62]
Hi,
I've started using autocomplete-light today, for autocompletion of ForeignKey on my custom ModelForm.
however when submitting an empty POST request, mentioned in title ValueError is being thrown, pointing to the template ("widget.html") line:
 {% for choice in autocomplete.choices_for_values %}

which leads to the following:
autocomplete/model.py in choices_for_values:

return self.order_choices(self.choices.filter(
            pk__in=self.values or []))

I've debugged that line and believe the problem is that, when empty POST is submitted, self.values contains one value, an EMPTY UNICODE STRING (that is, self.values == [u''])

I don't know autocomplete_light internals well enough to find out why is that

**Comment by blueyed** [comment]
This should be fixed (the PR was merged).
Probably re-opened accidentally.
