### ISSUE TITLE
Unable to set the initial value of a ModelChoiceField that uses ModelSelect2 widget

### ISSUE THREAD

**Issue by senoadiw** [yourlabs/django-autocomplete-light#621]
Greetings,

I have a DAL v3 autocomplete ModelChoiceField in admin that can save the selected value but doesn't preselect it when editing the entry. Here is my code:

**models.py**

    class Manufacturer(models.Model):
        name = models.CharField(max_length=50)
        
        def __unicode__(self):
            return '%s' % self.name

    class Design(models.Model):
        manufacturer = models.ForeignKey(Manufacturer)
        name = models.CharField(max_length=50)
        
        def __unicode__(self):
            return '%s' % self.name
            
    class Order(models.Model):
        manufacturer = models.ForeignKey(Manufacturer)
        option = models.CharField(max_length=50, blank=True)
        
        def __unicode__(self):
            return '%s' % self.pk

**views.py**

    class AutocompleteDesign(autocomplete.Select2QuerySetView):
        def get_queryset(self):
            if not self.request.user.is_authenticated():
                return Design.objects.none()
            qs = Design.objects.all().order_by('name')
            manufacturer = self.forwarded.get('manufacturer', None)
            if manufacturer:
                qs = qs.filter(manufacturer=manufacturer)
            if self.q:
                qs = qs.filter(name__icontains=self.q)
            return qs

**forms.py**

    class OrderForm(forms.ModelForm):
        option = forms.ModelChoiceField(
            required=False,
            queryset=Design.objects.all(),
            widget=autocomplete.ModelSelect2(url='autocomplete_design', forward=['manufacturer']),
        )

On the Order Form, I can select a manufacturer first and then select the associated design provided by the manufacturer. After saving I can see on the Order admin page that option is the selected design name. However when editing the entry I see that the manufacturer is preselected but the option is not (empty). Upon saving the empty option I get an IntegrityError error even though blank=True. I've also tried setting the initial in __init__ but didn't work:

    class OrderForm(forms.ModelForm):
        def __init__(self, *args, **kwargs):
            super(OrderForm, self).__init__(*args, **kwargs)
            self.fields['option'].initial = self.instance.option

I know ideally I should use option = models.ForeignKey(Option) but this would break importing using django-import-export. Also this seems similar to #104 but I don't see how to implement it in v3.

Cheers,

SN

**Comment by jpic** [comment]
I suspect you need to override the form field's to_python method.

That said, I'd rather have a real foreign key here if I were you and fix django-import-export.

**Comment by senoadiw** [comment]
Thanks for the input, I was unable to override ModelChoiceField's to_python() method because somehow it never gets called on Django 1.9.2. Eventually I went with the FK approach and fixed the importing part.
