### ISSUE TITLE
Feature Request: Create new item in choice list with modal dialog

### ISSUE THREAD

**Issue by guettli** [yourlabs/django-autocomplete-light#622]
The `create_field` option is nice. See http://django-autocomplete-light.readthedocs.org/en/master/tutorial.html#creation-of-new-choices-in-the-autocomplete-form

In my case I can't create new items by just one string. I need more input.

It would be very cool to be able to create new items in a dialog pop-up.

Do you have a clue how to implement this?

**Comment by jpic** [comment]
Check out​ https://github.com/yourlabs/django-addanother and
https://github.com/jonashaag/django-addanother (the one on pypi)
work is in progress to merge both repos

**Comment by jpic** [comment]
I forgot to ask, is it really a requirement for you to use a modal dialog instead of a popup ?

Still, in that case, I think modal dialog support should be in the django-addanother app, rather than in django-autocomplete-light.

**Comment by guettli** [comment]
I want the result to be usable by human beings :-)
Modal dialog with JS or old-syle browser popup ... this is not important to my at the moment.

Yes, autocomplete and add-another are two different things. But somehow the belong together: After adding another I want it to be automatically selected by the autocomplete.

I guess I can write the glue-code. But solving this without glue-code would be best.

**Comment by jpic** [comment]
What kind of glue code?

In the admin, add another works.

It should work the same with yourlabs/django-addanother.

**Comment by guettli** [comment]
> What kind of glue code? 

After adding an-other the added instance should be selected in the autocomplete input.

I guess this step is not done by dal or django-addanother. 

Does this answer your question? Please ask if something is not clear.

**Comment by jpic** [comment]
Hi !

Yeah, did django-addanother work for you ?

Best

**Comment by guettli** [comment]
Yes, it works.

I am coding a relay-race registration form for a friend. The code to combine add-another and autocomplete is very simple:

```

class RunnerSelectWidget(AddAnotherWidgetWrapper):
    def __init__(self):
        super(RunnerSelectWidget, self).__init__(autocomplete.ModelSelect2(url='runner-autocomplete'),
                                                 reverse_lazy('runner-add'))

```

 Thank you very much for your patience

**Comment by jpic** [comment]
No problem, I'm glad all kind of widgets (and not only DAL) can now enjoy
add-another feature !

**Comment by teconomix** [comment]
@guettli I would love to do just the same. Could you elaborate a little more on how you did it and maybe show an example of you form code?

Thank you very much!
