### ISSUE TITLE
v.3.1 select2 customize results

### ISSUE THREAD

**Issue by Summer88** [yourlabs/django-autocomplete-light#627]
In v. 2.3.3 I used to customize the results with a template like this in "navigation_autocomplete/autocomplete.html":

```

  {% for finded in results %}
  <tr >
    <td><a class="button"> {{ finded.name }}</a>   </td>
    <td>{{ finded.code  |default:" - " }} </td>

  {% empty %}
  <tr> Nothing found </tr>
   {% endfor %}
```

Now I understand that you use select2, but looking in select2.js I cannot understand where data are rendered. 

I get only the "text" that is returned by the unicode method of the searched model.
What am I missing to customize display of data?

**Comment by jpic** [comment]
Navigation autocompletes ​where actually not a feature from
django-autocomplete-light, but a feature (the purpose of) autocomplete.js
from jquery-autocomplete-light.

Django-autocomplete-light just presented this feature in the doc, but
autocomplete.js has now been extracted in its own repository:
jquery-autocomplete-light.

You can still use jquery-autocomplete-light's autocomplete.js to power your
navigation autocompletes - that's what I'd do of course :D - but that
doesn't even require installing django-autocomplete-light, just
autocomplete.js.

Does this clear any doubt ?
