### ISSUE TITLE
Multiple widget, one selection changes the value of other

### ISSUE THREAD

**Issue by bharathramh92** [yourlabs/django-autocomplete-light#628]
I want to have 2 autocomplete widget in a page. One is ModelSelect2Multiple and other is ModelSelect2.
Following is my form.

class NewBookAuthorForm(forms.ModelForm):

    class Meta:
        model = Author
        fields = ['test', ]
        widgets = {
            'test': autocomplete.ModelSelect2Multiple(url='seller:author-autocomplete')
        }
        labels = {
            'test': "Authors",
        }

class NewBookPublisherForm(forms.ModelForm):

    class Meta:
        model = Publisher
        fields = ['test', ]
        widgets = {
            'test': autocomplete.ModelSelect2(url='seller:publisher-autocomplete')
        }
        labels = {
            'test': "Publisher",
        }

`
In the template, as mentioned in this sample https://github.com/yourlabs/django-autocomplete-light/blob/master/test_project/select2_outside_admin/templates/select2_outside_admin.html , I have mentioned both the media as 

{{authorForm.media}}
{{publisherForm.media}}

in footer block.

Doing this is causing two issues. While selecting one Author, Publisher is getting changed to one value for the first time. Second is, the default validation is throwing a "Enter a list of values." error for the ModelSelect2 field. Is this a bug, or am I missing something?

P.S: I am using version 3.1.1

**Comment by jpic** [comment]
Interresting ! Did you try with only printing one .media ?

**Comment by bharathramh92** [comment]
yes. still getting the same behavior. So, am i missing something in template or form? what should i do if want to have two widgets in the same page?

**Comment by jpic** [comment]
You can have as many widgets as you want in the same page, there's no need
to run the script several times.

Could you fork the project and reproduce the issue in an example app please
?

Thanks !

**Comment by bharathramh92** [comment]
awesome. sounds good. will it fixed in the current version?

**Comment by jpic** [comment]
I see, it seems like there are several elements with the same ID.

To avoid this, instanciate the forms with a prefix:
https://docs.djangoproject.com/en/1.9/ref/forms/api/#django.forms.Form.prefix

**Comment by jpic** [comment]
But there's still something we should do about it in the package

**Comment by bharathramh92** [comment]
changing the prefix is not making any difference as well. btw, why is the form is throwing "Enter a list of values" error?

**Comment by jpic** [comment]
The "List of value" error is because ​the widget ModelSelect2 is not
compatible with ModelChoiceMultiple field, which is generated by default
for ManyToManyField. The same would happen with a simple
django.forms.widgets.Select class.

**Comment by jpic** [comment]
I confirm this fixes the problem for me:

```
--- a/test_project/possiblebug/views.py
+++ b/test_project/possiblebug/views.py
@@ -32,8 +32,8 @@ def add_new_book(request):
     forms = {}
     if request.method == 'POST':
         # create a form instance and populate it with data from the request:
-        authorForm = NewBookAuthorForm(request.POST)
-        publisherForm = NewBookPublisherForm(request.POST)
+        authorForm = NewBookAuthorForm(request.POST, prefix='author')
+        publisherForm = NewBookPublisherForm(request.POST, prefix='publisher')

         forms['authorForm'] = authorForm
         forms['publisherForm'] = publisherForm
@@ -53,6 +53,6 @@ def add_new_book(request):
     # if a GET (or any other method) we'll create a blank form
     else:

-        forms['authorForm'] = NewBookAuthorForm()
-        forms['publisherForm'] = NewBookPublisherForm()
+        forms['authorForm'] = NewBookAuthorForm(prefix='author')
+        forms['publisherForm'] = NewBookPublisherForm(prefix='publisher')
```

Perhaps you didn't set prefix in both constructor calls ?

That doesn't change, that the piece of code we have that's causing the
bug will be patched asap though.

**Comment by jpic** [comment]
I think this should fix it:
https://github.com/yourlabs/django-autocomplete-light/pull/633

However, you shouldn't have two forms with the same field names
without using different prefix, that will cause more errors. See
https://docs.djangoproject.com/en/1.9/ref/forms/api/#django.forms.Form.prefix

**Comment by bharathramh92** [comment]
Now, both selections are independent after defining the prefix constructor.

Also, i fixed the "Enter a list of values" mistake. I accidentally gave ManyToManyField instead of ForeignKey in models.

Thanks for ur help.

**Comment by jpic** [comment]
No problem, I'm trying to provide that feature we have that caused the bug
upstream select2/select2#4249
