### ISSUE TITLE
widget doesn't respect filter specified in ModelChoiceField's queryset

### ISSUE THREAD

**Issue by eskawl** [yourlabs/django-autocomplete-light#630]
I have a choice field as

``` python
    group = forms.ModelChoiceField(
        queryset=AccGroup.objects.filter(can_hold_accounts=True),
        widget=autocomplete.ModelSelect2(url='accgroup-autocomplete')
    )
```

But select2 shows all choices ignoring the filter.  The filter at the autocomplete view however works.

**Comment by jpic** [comment]
How is your AC view get_queryset ?

**Comment by eskawl** [comment]
AC view is 

```python
class AccGroupAutoComplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        if not self.request.user.is_authenticated():
            return AccGroup.objects.none()

        qs = AccGroup.objects.all()

        if self.q:
           qs = qs.filter(name__icontains=self.q).filter(can_hold_accounts=True)

        return qs
```

**Comment by jpic** [comment]
Perhaps this would be a bit better ^^


        qs = AccGroup.objects.filter(can_hold_accounts=True)

        if self.q:
           qs = qs.filter(name__icontains=self.q)

**Comment by eskawl** [comment]
:+1: That works.

**Comment by kamal-el** [comment]
hi, i I'm trying to get autocomplete-light  with Gm2m ,  But autocomplete.GM2MQuerySetSequenceField doesn't shows all choices.

**View.py :**
 def get_queryset(self):
        employees = Employees.objects.all()
        freecontracts = Frecontract.objects.filter(IS_ACTIVE=True)
        freeagencies = Freagencies.objects.filter(IS_ACTIVE=True)
        freelancers = Freelancers.objects.filter(IS_ACTIVE=True)

        if self.q:
            employees = Employees.objects.filter(EMP_FIRST_NAME__icontains=self.q)
            freecontracts = Frecontract.objects.filter(FIRST_NAME__icontains=self.q,
                                                       IS_ACTIVE=True)
            freeagencies = Freagencies.objects.filter(AG_NAME__icontains=self.q,
                                                      IS_ACTIVE=True)
            freelancers = Freelancers.objects.filter(FRE_FIRST_NAME__icontains=self.q,
                                                     IS_ACTIVE=True)
            
        qs = QuerySetSequence(employees, freecontracts, freeagencies, freelancers)

        if self.q:
            # This would apply the filter on all the querysets
            qs = qs.filter(Q(EMP_FIRST_NAME__icontains=self.q)|
                           Q(FIRST_NAME__icontains=self.q)|
                           Q(AG_NAME__icontains=self.q) |
                           Q(FRE_FIRST_NAME__icontains=self.q
                          ))
   ...
 **forms.py : **
 TRANSLATOR = autocomplete.GM2MQuerySetSequenceField(
        queryset=autocomplete.QuerySetSequence(
            Employees.objects.all(),
            Frecontract.objects.all(),
            Freagencies.objects.all(),
            Freelancers.objects.all(),
        ),
        required=False,
        label=_("Traducteur(s)"),
        widget=autocomplete.QuerySetSequenceSelect2Multiple(
            'qm:ressource-autocomplete'),
    )

**Comment by kamal-el** [comment]
i solved it, I delete the line: qs = self.mixup_querysets(qs).
I another questions : for applying  the filter on all the querysets : qs = qs.filter(name__icontain=self.q).
my models have a different fields:
 ** EMP-FIRST-NAME for models Employees, 
** FIRST-NAME for models Freecontracts, 
** AG_NAME for models Freeagencies,
** FRE_FIRST_NAME for models Freelancers
how can i do for applying filter  for qs??

**Comment by kamal-el** [comment]
Can someone help me. please !!!

**Comment by jpic** [comment]
You're applying the same filter again:

**Comment by kamal-el** [comment]
thank you very much for your help.
