### ISSUE TITLE
Change data fields in view response

### ISSUE THREAD

**Issue by Summer88** [yourlabs/django-autocomplete-light#632]
I get this response from a  "Select2QuerySetSequenceView":

`{"pagination": {"more": false}, "results": [{"text": "Mymodel", "id": null, "children": [{"text": "  first_unicode   ", "id": "23-firstmodelfield"}, {"text": "  second_unicode", "id": "23-firstmodelfield"}]}`

I've seen that select2 allow to change id by:

> https://select2.github.io/options.html#my-objects-dont-use-id-for-their-unique-identifiers-what-can-i

I ask you if it is there a way to tell autocomplete to use another value for the id, to have it in the response ? i.e. "id": 23-thirdmodelfield

without acting on the frontend?

I use autocomplete to retrieve values, to be inserted in a field that is a simple text field, no link in any table.
So I'd like to put the id = textvalue so the field result is compiled with only that, no id, no pk.

**Comment by jpic** [comment]
Perhaps in (view.get_result_value)[
http://django-autocomplete-light.readthedocs.org/en/master/api.html#dal.views.BaseQuerySetView.get_result_value​]
?

**Comment by Summer88** [comment]
Thanks for fast reply, I was a little lost, now I get it!  
Thanks again, the docs is good, but searching in it when you have no idea of where to look is a little complex. 
Have a nice day!

**Comment by jpic** [comment]
You're welcome​, thanks for the kind words !
