### ISSUE TITLE
No working in Formset Inline V3

### ISSUE THREAD

**Issue by jacruzsdev** [yourlabs/django-autocomplete-light#639]
Hello.
The autocomplete app it's soo cool in basic form, but in complex form as inlines form, this app has some problems:
First: The fields no was cloned for dynamic formset. The autocomplete fileds no working when add a new inline formset using this JS (jquery.formset.js):

https://searchcode.com/codesearch/view/8174502/

Second: The autocomplete fields with forward no working, well localize the dependence fields for the name's filed, but in inlines formset the names change for each inlines form

PD: The app only working so cool in Admin panel, in the custom templates using formset no working good for the inlines formset manager JS

Please, helpme...

Sorry.. my english is most regular

**Comment by jpic** [comment]
On Fri, Mar 11, 2016 at 9:33 PM, Jesus Andres Cruz Sanabria <
notifications@github.com> wrote:

> First: The fields no was cloned for dynamic formset. The autocomplete
> fileds no working when add a new inline formset using this JS
> (jquery.formset.js):
>
> https://searchcode.com/codesearch/view/8174502/
>
It works with Django's version:
http://dal-yourlabs.rhcloud.com/admin/select2_foreign_key/testmodel/add/

So if another implementation is provided by the community can it be made a
bit more compatible witth Django ? Perhaps make a PR on this repo even to
show an example ^^

> Second: The autocomplete fields with forward no working, well localize the
> dependence fields for the name's filed, but in inlines formset the names
> change for each inlines form
>
Could you explain that ? Sometimes an example code is woth 1000 words.

> PD: The app only working so cool in Admin panel, in the custom templates
> using formset no working good for the inlines formset manager JS
>
Agreed, but how would you like to do this ?

**Comment by jacruzsdev** [comment]
Hello.. sorry for the delay...

Add code for the template and script JS for inline formset. the view, autocomplete and urls it's according for tutorial. In django admin working the inline autocomplete, but in custom template not working.

Create a little repository for codes and screenshot, the link : 

https://github.com/jacruzsdev/FormSet_test_autocomplete

The damage is the JS script, I know, but I unknown repair the damage

help me please.. :(

**Comment by jpic** [comment]
Fixed in a8f89a

**Comment by resakse** [comment]
same here, work great in normal admin, but not working in tabularinline. using django 1.9.7 and autocomplete 3.1.6
error msg is :
`select2.js:25 Uncaught TypeError: $(...).select2 is not a function`
