### ISSUE TITLE
AMD support

### ISSUE THREAD

**Issue by thijstriemstra** [yourlabs/django-autocomplete-light#641]
I can't get django-autocomplete-light to play nice with my AMD-based project. I think this is because the Javscript files in this project don't have an AMD header (or any UMD-compatible header at all). Getting this error:

```
00:14:13.091 Error: Mismatched anonymous define() module: function (jQuery) {
  // This is needed so we can catch the AMD loader configuration and use it
  // The inner file should be wrapped (by `banner.start.js`) in a function that
  // returns the AMD loader references.
  var S2 =
(function () {
  // Restore the Select2 AMD loader so it can be used
  // Needed mostly in the language files, where the loader is not inserted
  if (jQuery && jQuery.fn && jQuery.fn.select2 && jQuery.fn.select2.amd) {
    var S2 = jQuery.fn.select2.amd;
  }
var S2;(function () { if (!S2 || !S2.requirejs) {
if (!S2) { S2 = {}; } else { require = S2; }
/**
 * @license almond 0.3.1 Copyright (c) 2011-2014, The Dojo Foundation All Rights Reserved.
 * Available via the MIT or new BSD license.
 * see: http://github.com/jrburke/almond for details
 */
//Going sloppy to avoid 'use strict' string cost, but strict practices should
//be followed.
/*jslint sloppy: true */
/*global setTimeout: false */

var requirejs, require, defi
makeError() require.js:165
intakeDefines() require.js:1255
localRequire() require.js:1439
requirejs() require.js:1791
<anoniem> add:882
1 require.js:165:17
```

**Comment by jpic** [comment]
Dunno, ​let's wait for someone using AMD to make a pull request.

**Comment by thijstriemstra** [comment]
@jpic Nha, I'd have to switch to a different project, I could wait forever, no?

**Comment by thijstriemstra** [comment]
AMD is the build system for select2 so I think it would make sense to use the same for your .js scripts to ensure full compatibility with select2.

**Comment by jpic** [comment]
No problem, feel free to submit a pull request !

**Comment by kevin-brown** [comment]
> I can't get django-autocomplete-light to play nice with my AMD-based project.

This is actually more of an issue in Select2, not in DAL. Assuming the AMD build tool which you are using follows the require.js/AMD spec, it should be treating Select2 like any other UMD-compatible library.

This might be relevant if you are using r.js: https://select2.github.io/options.html#select2-is-being-placed-before-jquery-in-my-javascript-file

> AMD is the build system for select2 so I think it would make sense to use the same for your .js scripts to ensure full compatibility with select2.

Select2 is designed to work both with and without AMD build systems.

**Comment by jpic** [comment]
Agreed, thx @kevin-brown .
