### ISSUE TITLE
When Django_Debug is false, I lose css on fields

### ISSUE THREAD

**Issue by NDaniel1096** [yourlabs/django-autocomplete-light#643]
What would cause this? I can run with Debug set to True and it is perfect.

Django 1.8.4 
Autocomplete Light = 2.2.10

Image of Issue
![image](https://cloud.githubusercontent.com/assets/14944211/13761344/edaec8d2-ea05-11e5-83bc-6a82a5a5f62f.png)

**Comment by jpic** [comment]
Perhaps run collectstatic again ?

**Comment by NDaniel1096** [comment]
collectstatic did not work. Any other suggestions?

**Comment by jpic** [comment]
Are the autocomplete styles properly loaded ?

**Comment by NDaniel1096** [comment]
Finally figured it out. Django-Compressor. Disabled it and now it is working like a champ.

**Comment by jpic** [comment]
It's probably because of the configuration of compressor, I used this with compressor and had no problem, but perhaps not with the same minifiers.
