### ISSUE TITLE
DAL v3: select form field is populated with "--------"

### ISSUE THREAD

**Issue by thainlnguyen** [yourlabs/django-autocomplete-light#651]
Hello,
I am trying to implement a simple autocomplete with a select form field using the User object model. My select field is empty apart from the dashes and I can't enter anything in it. I fail to link/associate my UsernameForm to the login.html correctly. It should at least populate the select form field. I could really use some pointers to move forward. 
Thank you for your time!

This is what I have so far:
### the localhost/type_ahead/?q
```
{"pagination": {"more": false}, "results": [{"text": "testuser1", "id": 1}, {"text": "testuser2", "id": 2}]}
```
### urls.py
```
from dal import autocomplete
urlpatterns = [
    url(
        r'^type_ahead/$',
        TypeAheadUsers.as_view(),
        name='list_users',
    ),
]
```
### views.py
```
from dal import autocomplete
class TypeAheadUsers(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = User.objects.filter(is_active=True).order_by("id")
        if self.q:            
            qs = qs.filter(username__istartswith=self.q)
        return qs
```
### models.py
```
from dal import autocomplete
class UsernameForm(ModelForm):
    username = forms.ModelChoiceField(
        queryset=User.objects.filter(is_active=True).order_by("id"),
        widget=autocomplete.ModelSelect2(url='list_users'),
    )    
    class Meta:
        model = User
        fields = ('username',)
```
### views.py
a login method that passes a context dictionary c to the login.html file
```
def login(request,invalid_login=None, username=None):
    c = {}
    c.update(csrf(request))

    if(invalid_login):
        c.update({"invalid_login":True})
    else:
        c.update({"invalid_login":False})

    c.update({"username": username if username else None})

    try:
        tmp = UsernameForm()
        logger.debug("show username field: {0}".format(tmp))
        c.update({"ta_username": tmp})
    except Exception as e:
        logException(e)
    return render(request, 'login.html', c)
```
### login.html
```
{% extends "base.html" %}

{% block content %}
<div class="login_main">
  {% load staticfiles %}
  <div class="login_productname2">Super Awesome Product Name Here</div>
  <div id="login_sec" class="login_numpad">

    <form action="/account/auth/" method="post" id="pinForm">
      {% csrf_token %}
      <table class="LoginAccount"> 
        <tr>          
          <td>Username:<span id="userRefresh" class="Refresh" onclick="refreshLoginUserList()"></span></td>
        </tr>
        <tr>
          <td>
            {{ta_username.username}}
          </td>
        </tr>
        <tr>
          <td><label for="passwd">PIN:</label></td>
        </tr>
        <tr>
          <td><input type="password" class="selected" maxLength="4" name="passwd" value="" id="passwd">{% if invalid_login %}<span class="ErrorMsg">Incorrect password</span>{% endif %}</td>
        </tr>
        <tr>
          <td height="1pt" colspan="1">&nbsp;</td>
        </tr>
      </table>
      {% include "NumberPad.html" %}      
    </form>
    <script type="text/javascript" src="{% static 'scripts/jquery.js' %}"></script>
    <div class="login_productname3">Rev. {{ epcRev }}</div>
  </div>
</div>
  
{% endblock content %}
```
### the rendered select form field
```
<select data-autocomplete-light-function="select2" data-autocomplete-light-url="/type_ahead/" id="id_username" name="username">
    <option value="" selected="selected">---------</option>
</select>
```

**Comment by jpic** [comment]
I don't see where it's supposed to be [loading the javascript](http://django-autocomplete-light.readthedocs.org/en/master/tutorial.html#using-autocompletes-outside-the-admin).

**Comment by thainlnguyen** [comment]
Hi @jpic,
Thanks for looking at it! I already load the static files in the base.html which includes the jquery.js file. but for the sake of the discussion I've updated my code sample to include the jquery.js file.

**Comment by jpic** [comment]
I don't see your base.html, nor `{{ form.media }}`, as it should be in http://django-autocomplete-light.readthedocs.org/en/master/tutorial.html#using-autocompletes-outside-the-admin

**Comment by thainlnguyen** [comment]
obviously, i am not very good at following instructions. i don't know why i miss the `{{form.media}}` field, but after putting it in everything is fine. there were some js errors but that was because i didn't copy the static files to my project tree.

it works and thank you!

**Comment by jpic** [comment]
I​ don't think you should copy static files in your static tree:

They should be picked up
by django.contrib.staticfiles.finders.AppDirectoriesFinder.

**Comment by thainlnguyen** [comment]
thank you! i will look into why we have a weird static file location implementation.

**Comment by jpic** [comment]
Perhaps this will help, it helped a lot of SO users:
blog.yourlabs.org/post/30382323418/surviving-djangocontribstaticfiles-or-how-to

**Comment by thainlnguyen** [comment]
having a closer look at the way static file was done in our development i cringed a little. i concluded that boat has sailed. thank you for your support and for creating this great feature! 
i have another question which i will ask in another "issue" :)

**Comment by thainlnguyen** [comment]
Hello Jpic,
I am little embarrassed to ask for more help on this issue. I accidentally deleted my working django-autocomplete with virtual keyboard support and all the whistle and bells that came with it. 

Now I am trying to recreate from scratch, but running into same issue with having an empty Select drop-down box with the "-------" as the default value.  

For now I am loading all the resource files .js/.css manually on the login.html since my static files implementation is SNAFU'ed because when I use {{ form.media }} and do a view source I don't see any of the necessary .js/.css files loaded. 

I suspect somehow that I am not loading the resource files correctly. But through the console debugger on Chrome I was inspecting the Network tab I do see the following .js files loaded:

 1. jquery-1.12.4.min.js
 2. jquery.init.js
 3. autocomplete.init.js
 4. select2.js

I really could use some good pointers as to where to start debugging. Thank you again for your time!
