### ISSUE TITLE
min_length for user-input: Too many AjaxRequests

### ISSUE THREAD

**Issue by guettli** [yourlabs/django-autocomplete-light#653]
In my use case user input with less then 5 characters should not start an AjaxRequests.

I looked in the docs a bit in the code, and could not find a way to configure it.

If is was blind: I am sorry.

If not: Do you have a hint how to get this done?

**Comment by smwise** [comment]
In 2.x this was easy: in your autocomplete definition you can in 'attrs' define an attribute called 'data-autocomplete-minimum-characters' to do exactly this. It defaults to 2. 

I've only briefly glanced at 3.x and it looks to handle widgets and JS completely different, so I can't answer for that version. I also didn't find any obvious documentation.

**Comment by jpic** [comment]
I've only briefly searched the select2 documentation, and found out this
would work:

        widgets = {
            'test': autocomplete.ModelSelect2Multiple(
                'select2_many_to_many_autocomplete',
                attrs={
                    'data-minimum-input-length': 3,
                }
            )
        }

**Comment by jpic** [comment]
Perhaps we should link their docs in ours ?

https://select2.github.io/options.html#data-attributes

Also, some users may miss the beginning of that page:

> This page of the documentation is currently *undergoing a rewrite and may
be incomplete*. If you do not find the answer you are looking for on this
page, you may have better luck looking at the old options page
<https://select2.github.io/options-old.html>.

So perhaps we should link the other page too:

https://select2.github.io/options-old.html

Looking forward to your proposal ;)

**Comment by kevin-brown** [comment]
> So perhaps we should link the other page too !

It'll be gone in version 4.1.0, so I'd personally avoid doing this.

**Comment by jpic** [comment]
Thanks for that, you're an :angel:

**Comment by guettli** [comment]
@kevin-brown `data-minimum-input-length` will be gone in 4.1? Do you more details?

**Comment by jpic** [comment]
Looked like @kevin-brown was replying to the quote about options-old.html.

**Comment by jpic** [comment]
Closing in favor of #662
