### ISSUE TITLE
Attribute "multiple" twice in <select> tag

### ISSUE THREAD

**Issue by guettli** [yourlabs/django-autocomplete-light#654]
The html output I get from the widget looks like this:
```
<select multiple="multiple" data-autocomplete-light-function="select2" data-autocomplete-light-url="/foo/bar/" id="id_to" multiple="multiple" name="barfoo">
</select>
```

The attribute `multiple` exists twice. I tried to find a reason for this, but failed.

This is forms/widget.py from Django==1.8.9. 
```

class SelectMultiple(Select):
    allow_multiple_selected = True

    def render(self, name, value, attrs=None, choices=()):
        if value is None:
            value = []
        final_attrs = self.build_attrs(attrs, name=name)
        output = [format_html('<select multiple="multiple"{}>', flatatt(final_attrs))]

```

The attribute is in the final_attrs and in the format_html().

Is the attribute in your html twice?

I am unsure how to fix it.

Do you have an idea?

**Comment by jpic** [comment]
Pretty interresting, perhaps this comes from something in your JS ?

Could you reproduce this anywhere in the test project ?

I don't see it twice here: http://dal-yourlabs.rhcloud.com/select2_outside_admin/

**Comment by guettli** [comment]
We have a CheckHTMLMiddleware which checks the HTML going from webserver to browser. It must be something in Python.

Since you don't see it, I don't care very much. I will close this. Thank you checking this.
