### ISSUE TITLE
Rendering Issue

### ISSUE THREAD

**Issue by ikcam** [yourlabs/django-autocomplete-light#655]
When I'm rendering the field outside the admin:

<img width="613" alt="captura de pantalla 2016-03-23 a las 10 50 10 a m" src="https://cloud.githubusercontent.com/assets/1041823/13991204/38da95ee-f0e5-11e5-874a-e16b2927084a.png">

`<td>
    {% bootstrap_field field show_label=False size='sm' form_group_class='' %}
</td>
`

The field is rendering using [django-bootstrap3](https://github.com/dyve/django-bootstrap3)

**Comment by jpic** [comment]
That's either a select2 or a django-bootstrap3 problem, or a problem in your layout.

Not sure what we can do here.

**Comment by jpic** [comment]
Thank you brother B)
