### ISSUE TITLE
Using get_queryset with modelForm

### ISSUE THREAD

**Issue by pbassut** [yourlabs/django-autocomplete-light#657]
I'm using ModelAdmin with a form that subclasses autocompletelight's ModelForm.
I having some issues that I need to solve with prefetch_related and select_related to fetch tables in a single batch.
Looks like the problem is with the choices field. So that can't be done using the get_queryset of admin.ModelAdmin.

How can I make the choices field use the right queryset?

**Comment by jpic** [comment]
Did you try overriding get_choices ? (Assuming you are on DAL v2)

**Comment by pbassut** [comment]
I'm on v2, yeah. Precisely: 2.2.5.
I didn't know there was a get_choices. Is it a django ModelForm method? Because I can't find any docs on it.

**Comment by jpic** [comment]
My bad, that would be choices_for_request and choices_for_values:

http://django-autocomplete-light.readthedocs.org/en/2.3.1/api.html#autocompletebase
​
Seems like you might have missed the part about security:

http://django-autocomplete-light.readthedocs.org/en/2.3.1/autocomplete.html#overriding-the-queryset-of-a-model-autocomplete-to-secure-an-autocomplete

**Comment by pbassut** [comment]
So, I can't use this with ```dal.ModelForm```, right?
I have to remove ```dal.ModelForm```(or inherit from django.ModelForm) and work my way through that ```choices_for_request``` method?

Why you say I missed the security part? Mind explaining that?

**Comment by jpic** [comment]
Absolutely not, perhaps it would help if you pasted your code.

**Comment by pbassut** [comment]
These are the models I'm trying to make DAL work with:
```python
class CourseTopic(models.Model):
    course = models.ForeignKey("Course")
    topic = models.ForeignKey(Topic)

class Course(models.Model):
    topics_required = models.ManyToManyField(Topic, related_name="courses", verbose_name=u'Tópicos necessários', through="CourseTopic")
```
My admin models:
```python
class CourseTopicInline(admin.TabularInline):
    model = CourseTopic
    form = CourseTopicForm

@admin.register(Course)
class CourseAdmin(admin.ModelAdmin):
    inlines = (CourseTopicInline,)
```

And this is my model form:
```python
class CourseTopicForm(autocomplete_light.ModelForm):
    class Meta:
        model = CourseTopic
        exclude = ()

class CourseForm(autocomplete_light.ModelForm):
    class Meta:
        model = Course
        exclude = ()
```

**Comment by jpic** [comment]
So, do you have any Autocomplete class registered ?

**Comment by pbassut** [comment]
```python
class CourseAutoComplete(autocomplete_light.AutocompleteModelBase):
    search_fields = ['^name', ]
    choices = Course.objects.none()
    widget_attrs = {
        'data-widget-maximum-values': 4,
        'class': 'modern-style',
    }


class CourseTopicAutoComplete(autocomplete_light.AutocompleteModelBase):
    search_fields = ['^name', ]
    choices = CourseTopic.objects.none()
    widget_attrs = {
        'data-widget-maximum-values': 4,
        'class': 'modern-style',
    }

autocomplete_light.register(Course, CourseAutoComplete)
autocomplete_light.register(CourseTopic, CourseTopicAutoComplete)
```
I set them as none for now just to see if the choices ran faster. But they didn't. Meaning this is being ignored.

**Comment by jpic** [comment]
Could you tell what happens in choices_for_request and choices_for_values please ?

http://django-autocomplete-light.readthedocs.org/en/2.3.1/api.html#autocompletebase

Perhaps you can use a debugger such as pdb.

**Comment by pbassut** [comment]
Sure. What you wanna know?
You want me to return my queryset, there?

**Comment by jpic** [comment]
I'd like to know what happens exactly, line by line, in your case, in choices_for_request, please, because that's the method that's used for rendering of the choices in the autocomplete.

Also, this reminds me that we don't even know where your problem happens, is it in initial form rendering, is it in the autocomplete ajax, is it during validation ... please provide more information and research !

**Comment by pbassut** [comment]
It happens on rendering when calling this line:
```
autocomplete_light/widgets.py in render(165)
  values = [autocomplete.choice_value(c) for c in choices]
```

**Comment by jpic** [comment]
Did you see the line above that ? [Here](https://github.com/yourlabs/django-autocomplete-light/blob/v2/autocomplete_light/widgets.py#L167):

    choices = autocomplete.choices_for_values()

Perhaps all you have to do is override choices_for_values to return the proper queryset then ?

**Comment by pbassut** [comment]
Well, just a follow up on this:
Looks like django's widget class queries one id at a time to build the widget(in that case the DAL widget). 
This stacktrace tells us DAL can't do anything about since it's on django's end. Here, DAL receives the widget's value and builds itself with it. And this is the id of the model. Which makes DAL make one query for each one. Sad, but true story.
```
 /Users/patrickbassut/Programming/logus/lib/python2.7/site-packages/django/forms/forms.py(560)as_widget()
-> return force_text(widget.render(name, self.value(), attrs=attrs))
  /Users/patrickbassut/Programming/logus/lib/python2.7/site-packages/django/contrib/admin/widgets.py(271)render()
-> output = [self.widget.render(name, value, *args, **kwargs)]
  /Users/patrickbassut/Programming/logus/lib/python2.7/site-packages/autocomplete_light/widgets.py(164)render()
-> choices = autocomplete.choices_for_values()
> /Users/patrickbassut/Programming/logus/core/forms.py(31)choices_for_values()
-> assert self.choices is not None, 'choices should be a queryset'
```

Let me know if you have a workaround for this.

**Comment by pbassut** [comment]
So, my problem is that when executing the batch that gets the Course objects, I can't find a way to also get the CourseTopic objects(along with the course and topic, because it's a foreign key through another model) in a single batch.

Any ideias?
I'm on this issue for days now.
If upgrading for v3 will solve my issue, let me know cause I'm willing to make the effort.

**Comment by jpic** [comment]
I don't think the issue is in DAL now, it's just that it doesn't get the right queryset.

Please take this to stackoverflow.
