### ISSUE TITLE
virtual keyboard support

### ISSUE THREAD

**Issue by thainlnguyen** [yourlabs/django-autocomplete-light#659]
Hi JPic again!
Thanks for being very responsive in my other issue! I am trying to integrate this virtual keyboard: https://github.com/Mottie/Keyboard into DALv3 select form field. So nothing is ever straightforward and also javascript is literally a foreign language to me. A quick trial and error produces the following questions:

1. I am trying to associate the virtual-keyb to the search field that is dynamically generated when you click the select form field: `<input class="select2-search__field" type="search">`. So in the javascript console I tried the following after the page finish loading: `$("input[type=search]").keyboard()`. Clearly, it will not work until you place your mouse marker in the select form field and re-execute the js command. The question is how do i capture the event when clicking the select form field and create a hook into the search field to load the virtual-keyb whenever this page finish loading?
2. After manually getting virtual-keyb initialized and displaying; the letters entered with the virtual-keyb is not registered by the DALv3 select form field. Apparently the virtual-keyb is not writing into the same input type as DALv3. Any pointers?

**Comment by jpic** [comment]
It would be pretty cool but shouldn't you contribute this to [Select2](https://select2.github.io/) rather ?

**Comment by thainlnguyen** [comment]
thanks for the reference! i will check it out :+1:
