### ISSUE TITLE
Understand Querysetsequence results

### ISSUE THREAD

**Issue by dovevannoafinireimieigiorni** [yourlabs/django-autocomplete-light#660]
this is the view, that is passed to an url and called from a form:

```
class testautocompleteview(Select2QuerySetSequenceView): 
    def get_queryset(self):
        qs = Mymodel.objects.all()
        if self.q:
            qs = qs.filter(
                Q(descrizione__icontains=self.q.upper())
            )                

        # Aggregate querysets
        qs = QuerySetSequence(qs)
        qs = self.mixup_querysets(qs)
        return qs
    
    def get_result_value(self, result):
        return result.descrizione

```
in forms.py:

  ```
      widgets = {
            'testfield': QuerySetSequenceSelect2(url='linkdb:testautocomplete'),
}
```

with this I get the create object view  that seems to work fine, but, when the object is saved, by overriding the get_result, when triyng to access with an updateview django complains :

`ValueError: need more than 1 value to unpack`

if I remove the get_result method, the field is compiled by the "object.pk-None" and updateview complain:

```
c/.virtualenvs/leore/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 976, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'None'

```

I'm pretty new to dal and surely I'm missing something, thanks for your work!

**Comment by jpic** [comment]
I'm a bit confused, is it possible for you to reproduce this in a test project or in test_project and put up a clear list of steps to follow to reproduce the issue you're facing ?

Thanks !

**Comment by dovevannoafinireimieigiorni** [comment]
In test project if I add  a **view** in 
/tmp/dal_env/src/django-autocomplete-light/test_project/select2_one_to_one/

```
from django.shortcuts import render

# Create your views here.
from dal_select2_queryset_sequence.views import Select2QuerySetSequenceView

from dal import  autocomplete

class testautocompleteview(autocomplete.Select2QuerySetView):
    def get_result_value(self, result):
        """Return the value of a result."""
        return result.name
    

```

then correct the url to:
```

    url(
        'test-autocomplete/$',
        views.testautocompleteview.as_view(
            model=TestModel,
            create_field='name',
        ),
        name='select2_one_to_one_autocomplete',
    ),

```
and now go to admin and edit the field to see the name other than the pk, I get this error:

http://localhost:8000/admin/select2_one_to_one/testmodel/48/change/

> ValueError at /admin/select2_one_to_one/testmodel/48/change/
> invalid literal for int() with base 10: 'peppa pig name'
>

**Comment by jpic** [comment]
Oh I see, perhaps this should help: http://django-autocomplete-light.readthedocs.org/en/master/api.html#dal-contenttypes-genericforeignkey-support
