### ISSUE TITLE
Set tokenSeparators 

### ISSUE THREAD

**Issue by guettli** [yourlabs/django-autocomplete-light#667]
How can I set `tokenSeparators` of select2?

I want to add space to the list of separators.

Related question on StackO: http://stackoverflow.com/a/36201505/633961

**Comment by jpic** [comment]
Did you try data-token-separators ?​

**Comment by guettli** [comment]
Do you know where the magic transformation from CamelCase to data-camel-case happen?
.... wait ...
Ah found a good explanation here:

http://stackoverflow.com/questions/22753629/jquery-get-html-5-data-attributes-with-hyphens-and-case-sensitivity

Unfortunately select2 has a bug, but I hope it gets solved soon. 

https://github.com/select2/select2/issues/3458

Thank you

**Comment by jpic** [comment]
Did you try updating the select2 git submodule to the current master to
have the patch that was commited 8 days ago ?​

**Comment by guettli** [comment]
Yes, I tried it, but now things break. I will wait for the things to settle down. I am not in a hurry here.
