### ISSUE TITLE
[Question] DAL v3 Listening to the "select2-selecting" event in admin

### ISSUE THREAD

**Issue by senoadiw** [yourlabs/django-autocomplete-light#668]
Greetings,

Currently I have a working select2 autocomplete widget in a form. My goal is to run some javascript when an option is selected from the widget like the Event example at http://select2.github.io/select2/. I've tried putting this in my admin form js file but it seems to not fire:

$(document).ready(function() {
  $('#id_mymodel').on("select2-selecting", function(e) {
    console.log('selecting id');
  });
  console.log('bla');
});

Would really appreciate any pointers on how to accomplish this.

Regards,

SN

**Comment by jpic** [comment]
Did you try binding on "change" ?

**Comment by jpic** [comment]
Confirmed, this works:

    $('#id_test').on('change', function() { console.log('hi'); })

On http://dal-yourlabs.rhcloud.com/select2_outside_admin/

**Comment by senoadiw** [comment]
Thanks! It fires now but somehow not returing the new selected value:

$(document).ready(function() {
$('#id_mymodel').on("change", function(e) {
console.log(e);
console.log("change " + JSON.stringify({val:e.val, added:e.added, removed:e.removed}));
});
console.log('bla');
});

It seems like there is no val property in the event object as suggested in the example at http://select2.github.io/select2/ :/

**Comment by jpic** [comment]
Using `$(this).val()` works for me: 

![2016-04-05-153559_978x203_scrot](https://cloud.githubusercontent.com/assets/94636/14283616/56eddb54-fb44-11e5-96a7-7978d6c3ad2a.png)

**Comment by kevin-brown** [comment]
Note that DAL v3 is using the newer version of Select2, you can find the documentation at https://select2.github.io/examples.html

The replacement event for `select2-selecting` is `select2:selecting`. You can see what it now contains in the example at https://select2.github.io/examples.html#programmatic-control

**Comment by senoadiw** [comment]
@jpic @kevin-brown thanks, I managed to get it working with this:

$(document).ready(function() {
  $('#id_mymodel').on("select2:selecting", function(e) {
    var data = e.params.args.data;
    if (data.id && data.text) {
      console.log(data.id);
      console.log(data.text);
    }
  });
});

Cheers!

**Comment by nameisnot** [comment]
@jpic @senoadiw I am facing a similar dilemma ([#1132 posted here](https://github.com/yourlabs/django-autocomplete-light/issues/1132#issue-544204271)).

Is it possible for you to guide me please?

Thanks

**Comment by nikijoe** [comment]
@jpic @kevin-brown could you help me out in changing the value of a dal select2 widget with jquery like $(element).val(data.id).trigger('change'). 
For me getting value with
var value = $(element).val() 
and 
$(element).change(function(){ 
// do something
}); 
working. 
But issue is with 
$(element).val(data.id).trigger('change') not working and not changing selection in dal ModelSelect2 widget. Using dal3.7.0.dev0 version django 3.0.8 python 3.8.0

Thanks

**Comment by jpic** [comment]
@nikijoe Not really sure (I'm not using select2 anymore, using #1170) , does this help ? https://select2.org/programmatic-control/events#triggering-events

**Comment by nikijoe** [comment]
@jpic thanks for your response. But the documentation didn't help. Waiting for dal 4.0 and is it ready for release or what?
