### ISSUE TITLE
UseCase: I want select2, but not autocomplete

### ISSUE THREAD

**Issue by guettli** [yourlabs/django-autocomplete-light#670]
Hi,

does django-autocomplete-light provide a django-widget, which does apply select2-JS-magic to the HTML-select, but does not use an autocomplete?.

My use case: I want a better ManyToMany-Widget, but it should be a drop-in replacement. There are only very few (less then 12) items in the list.

I can live with ctrl-click, but most users don't get it :-)

**Comment by jpic** [comment]
The js bootstraps based on an html attribute, if it is not there then it
won't do anything

**Comment by guettli** [comment]
ok, two things are needed:

- add the html attribute
- include the js files from select2.

I can do both things in my custom code.

I just was curious if you. Maybe you already have such a basic widget in dal.

If not, are you interested in adding it?

**Comment by jpic** [comment]
Yes of course we just need an example app in test project, automatic test
and documentation and it's good to go ;)

**Comment by guettli** [comment]
I looked at the source and the following code does:

1. sets the media class: css and js gets loaded. Nice
1. does initialise the select2() somewhere: nice

Missing: 

- This widget tries ajax and uses the same page as source, adding a ?q=...

```
class ModelSelect2MultipleWithoutAjax(WidgetMixin, forms.SelectMultiple, Select2WidgetMixin):
    pass

```

Do you have a hint how to get a wdiget without ajax implemented?

**Comment by jpic** [comment]
Try this:

    class ModelSelect2MultipleWithoutAjax(WidgetMixin, forms.SelectMultiple, Select2WidgetMixin):
        autocomplete_function = 'your-autocomplete'

Then, register your custom init function, ie:

```
    $(document).on('autocompleteLightInitialize', '[data-autocomplete-light-function=select2]', function() {
        $(this).select2({...})
    });
```

**Comment by jpic** [comment]
I'm not sure, but perhaps trying `autocomplete_function=''` would work in your case too.

**Comment by jpic** [comment]
Note that we have this sort of weird initialization system so that it supports dynamically added elements ;)

**Comment by guettli** [comment]
I am unsure where to store the "custom init function".

I don't want this burden to be done by the widget user. The library should handle this.

**Comment by jpic** [comment]
Are you sure you need any init function ?

I thought it would work if you just specify something that does not exist,
ie. "none".

**Comment by jpic** [comment]
Otherwise, feel free to contribute some more !!

**Comment by jpic** [comment]
Hi ! Do you think PR #691 would be enough for this issue ? Thanks !

**Comment by guettli** [comment]
I skimmed over it. Looks good. I close my issue. Thank you!
