### ISSUE TITLE
context['page_obj'] is None but still checked for number attribute

### ISSUE THREAD

**Issue by zandrmartin** [yourlabs/django-autocomplete-light#671]
I am running to an issue with this line in `dal_select2/views.py`: [if self.create_field and q and context['page_obj'].number == 1:](https://github.com/yourlabs/django-autocomplete-light/blob/a16f0e1c336ee17d3ebf5dc5297252970befbee7/src/dal_select2/views.py#L27)

In my case the `page_obj` is `None` because I am not using a paginator; obviously `None` has no `number` attribute so I'm getting 'The results could not be loaded.' on every search.

I am relatively new to Django so I don't know all the black magic going on under the hood but the docs seem to indicate that `None` is a valid value for `context['page_obj']` if a paginator is not used, so converting to `getattr()` here seems like a good idea:

```python
if self.create_field and q and getattr(context['page_obj'], 'number', 1) == 1:
```

FWIW I am using this on a GM2M field and I just followed the examples in the docs to set it up. I don't think I'm doing anything particularly unusual, but I'm open to the possibility that this is user error on my part.

**Comment by jpic** [comment]
I'm not quite sure how to reproduce this, could you set up an example app in test_project ?

Sorry for the late reply, it's cool to bump up issues when they have had no replies for a while here.

Thanks !

**Comment by zandrmartin** [comment]
No worries, the project changed a bit and so I didn't actually need to use the GM2M functionality. (Instead I'm using this with Taggit, and that is working fine.) I did create a dummy project just to illustrate the problem. https://github.com/zandrmartin/django-autocomplete-light/tree/issue%23671/test_project/testsel

Steps to reproduce:
- clone project, run migrations/setup/etc
- run test server
- go to `localhost:8000/testsel/test`
- type `te` in "tags" input field
- no results found, though there should be results.

Here's the traceback:

```
Internal Server Error: /testsel/tag-autocomplete/
Traceback (most recent call last):
  File "/home/zandr/Code/django-autocomplete-light/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/zandr/Code/django-autocomplete-light/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zandr/Code/django-autocomplete-light/venv/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/zandr/Code/django-autocomplete-light/venv/lib/python3.5/site-packages/dal/views.py", line 30, in dispatch
    return super(ViewMixin, self).dispatch(request, *args, **kwargs)
  File "/home/zandr/Code/django-autocomplete-light/venv/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/zandr/Code/django-autocomplete-light/venv/lib/python3.5/site-packages/django/views/generic/list.py", line 175, in get
    return self.render_to_response(context)
  File "/home/zandr/Code/django-autocomplete-light/venv/lib/python3.5/site-packages/dal_select2/views.py", line 27, in render_to_response
    if self.create_field and q and context['page_obj'].number == 1:
AttributeError: 'NoneType' object has no attribute 'number'
[17/May/2016 21:35:53] "GET /testsel/tag-autocomplete/?q=te HTTP/1.1" 500 17348
```

As I mentioned, it's entirely possible I'm doing something wrong here, so apologies if that is the case.

**Comment by jpic** [comment]
I got a 404 on localhost:8000/testsel/test. So, obviously this code would fail if page_obj is not in context or if it's None. But I don't understand why this would happen, perhaps you could hack an existing app to demonstrate ? Why don't you have a paginator ?

**Comment by zandrmartin** [comment]
I'm not sure why you are getting a 404 on my example; did you clone my whole repo's `issue#671` branch? There are some additions to the base project, for example in `test_project/urls.py`.

Anyway, this appears to be something I'm doing wrong in the view: https://github.com/zandrmartin/django-autocomplete-light/blob/issue%23671/test_project/testsel/views.py

When I just use
```python
url(r'tag-autocomplete/$',
    autocomplete.Select2QuerySetSequenceView.as_view(
        queryset=autocomplete.QuerySetSequence(
            TestModel.objects.all(),
            TestModel2.objects.all(),
        )
    ),
    name='tag-autocomplete'
),
```
instead of 
```python
url(r'tag-autocomplete/$', TagAutocompleteView.as_view(create_field='TestModel'), name='tag-autocomplete'),
```
in my `urls.py` it works fine.

I was following http://django-autocomplete-light.readthedocs.io/en/master/gfk.html#generic-autocomplete-view (referenced from http://django-autocomplete-light.readthedocs.io/en/master/gm2m.html#view-example) when I set up that view so I must have misunderstood how it was supposed to work.

As far as why don't I have a paginator - well, I guess that's the question I'm asking. :smile:

**Comment by jpic** [comment]
Oh no, I think this documentation is a outdated !!

**Comment by jpic** [comment]
Ahhhhh thanks !

I think this would be the issue:

https://github.com/yourlabs/django-autocomplete-light/blob/master/src/dal_queryset_sequence/views.py#L21-L23

**Comment by jpic** [comment]
If you set mixup=False in the view then it works, but I'm not sure that's what you want.

This part should be fairly easy to cover by test cases and fix, so that's pretty good news :)

Thanks a heap for your guidance :guitar:

**Comment by zandrmartin** [comment]
Oh sure! Like I mentioned, I am not actually using this GM2M setup anymore so I haven't worried about it, but nice to know I helped. :smile:

Thanks for the great plugin BTW! I am using the Taggit autocomplete and it works fantastically.

**Comment by jpic** [comment]
I could isolate this in a test case which reproduce the exception, thanks to your kind patience !

To run the test case alone, I found this works:

    DJANGO_SETTINGS_MODULE=settings.base PYTHONPATH=~/env/src/dal/test_project/ py.test tests/test_views.py -s

I need to go to sleep and I'm not sure when I can fix this, perhaps next week. If you're into that kind of sports perhaps you could contribute the fix ? If you want it's all yours, you've got it right from the beginning ^^

Rock'on B)

**Comment by jpic** [comment]
Closing in favor of PR #693 

Please review if you have time

:guitar:
