### ISSUE TITLE
Extra parameters in ajax call

### ISSUE THREAD

**Issue by daniloakamine** [yourlabs/django-autocomplete-light#672]
Hi,
Is it possible to pass extra arguments in ajax request?
I'm passing the `q` parameter normally, but additionally I'd like to pass `another` parameter.

For example: `/q=keyword&ignore=1`

Thanks

**Comment by daniloakamine** [comment]
I put the new parameter **ignore** in my view and it's working.
I overrode `dispatch` and `get_queryset` methods.

```
class ProductAutocomplete(autocomplete.Select2QuerySetView):

    def dispatch(self, request, *args, **kwargs):
        self.ignore = request.GET.getlist('ignore')
        return super(ProductAutocomplete, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        if not self.request.user.is_authenticated():
            return Product.objects.none()

        qs = Product.objects.all()

        if self.q:
            qs = qs.filter(reference__istartswith=self.q)

        if self.ignore:
            qs = qs.exclude(id__in=self.ignore)

        return qs.order_by('name')
```

But now I don't know how to put this new parameter in my component.
Can someone help me?

**Comment by jpic** [comment]
Hi !

Did you see this ?

http://django-autocomplete-light.readthedocs.org/en/master/tutorial.html#filtering-results-based-on-the-value-of-other-fields-in-the-form
​

**Comment by daniloakamine** [comment]
Thanks, I will try!

**Comment by daniloakamine** [comment]
That solution worked, thanks!
My case is not similiar to the tutorial, but after some workarounds it's working now.

I needed to send dynamic data in my new parameter and there wasn't a input field with this information.
So, I created a field empty in forms.py:

`selected_products = forms.MultipleChoiceField()`

and I'm using JQuery to push my data dynamically in this new field.
