### ISSUE TITLE
How to include static files in build process

### ISSUE THREAD

**Issue by aidanlister** [yourlabs/django-autocomplete-light#673]
Is there a good way to include the static files in a build process like webpack or grunt?

It seems like maybe having the static files available via an npm package would be the best option ...

**Comment by jpic** [comment]
Hi !

Thanks for your feedback !

Currently we use versions which have not yet been released on npm. Also, we don't want to add a dependency to npm.

However, you're free to use npm in your project and override the provided static files in one of your STATICFILES_DIRS. But then be aware that you'll be using a version that's not tested.

Best

James
