### ISSUE TITLE
Manually loading css and js files

### ISSUE THREAD

**Issue by hsdhillon** [yourlabs/django-autocomplete-light#674]
My apologies if this has been answered before but I couldn't find this in any of the issues or the documentation.

Is there a way to disable the auto loading of JS and CSS files from Media class. I already have the CSS tags according to my application theme that are needed by select2 but the autocomplete_light css files override them causing the UI issues.

I am using autocomplete.Select2QuerySetView.

**Comment by jpic** [comment]
It's rendered by `{{ form.media }}`, so you just need to override the
template block that has it and remove it ;)
