### ISSUE TITLE
“Select a valid choice” error only on first submission try

### ISSUE THREAD

**Issue by ThomasBraam** [yourlabs/django-autocomplete-light#676]
I have posted a question on StackOverflow regarding your project. I guess the issue is too specific and should be on this forum: [click](http://stackoverflow.com/questions/36532739/select-a-valid-choice-error-only-on-first-submission-try-using-djang-autocompl)

Is this a known problem? Do you have any idea how to resolve it?

Thanks,

**Comment by jpic** [comment]
Follow up on SO !
