### ISSUE TITLE
Forward data not sent when creating object

### ISSUE THREAD

**Issue by CreatixEA** [yourlabs/django-autocomplete-light#677]
When using the forward option, and when there is no result and when we can create an object : the forwarded data are not sent to the creation function

Inside `create_object(self, text)` the `self.forwarded` is always `None`. IMO it should be filled with the forwarded data. It's a JS trick I think in that [dict](https://github.com/yourlabs/django-autocomplete-light/blob/master/src/dal_select2/static/autocomplete_light/select2.js#L82)

Hope it will be implemented and thank you for that wonderfull tool.

Sincerely,

E.

**Comment by jpic** [comment]
Could you make an example app for this please ?

Thanks !

**Comment by toudi** [comment]
I have figured out how to do this, I'll do a PR in a moment.

**Comment by toudi** [comment]
could we please close this one, @jpic ?

**Comment by jpic** [comment]
Do you have permission to close it now ?

**Comment by toudi** [comment]
yep, it works ;) thanks!

**Comment by jpic** [comment]
:guitar:
