### ISSUE TITLE
clean "autocomplete field" if "Forward field" has changed

### ISSUE THREAD

**Issue by luzfcb** [yourlabs/django-autocomplete-light#678]
Hello, I have the following use case (is a variation of http://django-autocomplete-light.readthedocs.org/en/master/tutorial.html#filtering-results-based-on-the-value-of-other-fields-in-the-form )

if a "Forward field" has changed, the "autocomplete field" should be cleaned. 
this would avoid the user to select options incompatible with the currently selected filter.

currently I'm using this little code snippet that I insert on https://github.com/yourlabs/django-autocomplete-light/blob/3.1.5/src/dal_select2/static/autocomplete_light/select2.js#L7

```javascript
        (function (autocomplete_element) {
            var forward = $(autocomplete_element).attr('data-autocomplete-light-forward');
            if (forward !== undefined) {
                forward = forward.split(',');

                var parts = $(autocomplete_element).attr('name').split('-');
                var prefix = '';

                for (var i in parts) {
                    var test_prefix = parts.slice(0, i).join('-');
                    if (!test_prefix.length) continue;
                    test_prefix += '-';

                    if ($(':input[name=' + test_prefix + forward[0] + ']').length) {
                        var prefix = test_prefix;
                    }
                }

                for (var key in forward) {
                    var name = prefix + forward[key];
                    var element_selector_str = '[name=' + name + ']';
                    // attach change event on "forward fields" to clean
                    // autocomplete_element if "forward field" has changed
                    $('[name=' + name + ']').on('change', function () {
                        // this clean current selection on autocomplete field
                        $(autocomplete_element).empty().trigger('change')
                    });
                }
            }

        })(this);

```

The question is:

1 - This should be the default behavior?
2 - An attribute like as `data-autocomplete-light-clean-if-forward-changed` should be provided to enable/disable this behavior?

What are your thoughts about this?

ps. I did not like this code snippet because it is essentially https://github.com/yourlabs/django-autocomplete-light/blob/3.1.5/src/dal_select2/static/autocomplete_light/select2.js#L26-L53 with few modifications (almost duplicate code).. but it was the best I could do with my current knowledge of javascript ...

I tries to send a pull-request if you want

**Comment by jpic** [comment]
Interresting idea, thanks for your feedback !

If I understand your current implementation correctly, the callbacks to clear the autocomplete are set-up the select2's data callback, which is called when select2 fetches data, typically after user interaction with the autocomplete field. I can see how that works if 0. user loads page 1. user clicks the autocomplete 2. user changes forwarded field. But is that implementation able to clear the autocomplete after 0. user loads the page and 1. user changes a forwarded field ? I don't see how that callback could be registered there. So my advice would be to take that part out of select2.js, it would work better and be cleaner.

This is indeed out of the scope of the forward feature as initially designed. I won't deny how useful it can be to "clear an input if another input changes value" as I've [myself implemented that and a bit more in a standalone engine that does this kind of things back in my early days](https://djangosnippets.org/snippets/1358/). However, this user story, "clear an input another input chages value", doesn't sound like it would make sense to implement in the autocomplete app. As suggested by @munhitsu in the djangosnippets thread, it would make sense to release as a standalone django app, or perhaps even as a standalone jquery plugin.

In the mean time, we could extract part of the logic you need from select2.js, and have a separate function that would return a selector of form fields which are in data-autocomplete-light-forwarded. Then your code would work outside select2.js and look something like:

```
yl.getForwardedFields(autocomplete_element).on('change', function() {
    $(autocomplete_element).empty().trigger('change')
});
```

**Comment by luzfcb** [comment]
@jpic hello. Thanks for the quick response. I implemented an example demonstrating my use case, because I think my explanation of the problem was a little confused, show the code can leave a little clearer. 
perhaps with the practical example, that feature I have proposed make more sense.

my test application is running on: https://linkdata-clear-autocomplete.herokuapp.com
source: https://github.com/luzfcb/linkdata_clear_autocomplete
To test, click into "Create new document from template"

I think maybe this feature would be better named as: "use the forwards field as exclusive filters to autocomplete"

it is basically My javascript + https://github.com/luzfcb/linkdata_clear_autocomplete/blob/master/documents/views.py#L21-L31


a function like your "getForward Redfields" might help my implementation live off django-autocomplete-light

thoughts?

(ps: sorry my english )

**Comment by jpic** [comment]
@luzfcb, your implementation works! I would be interresting to have this in DAL too ... Wouldn't it be better to have this feature "field that clears on change of another field" in a separate app ? Like django-addanother, perhaps with a name like django-forms-clear-on-change, your example would look like:

    document_template = ClearOnChangeWrapper(
        DocumentTemplateModelChoiceField(queryset=Document.objects.all(),
            widget=ModelSelecT2(url='document-autocomplete', forward=('document_type',)),
        ), 
        clear_on_change=['document_type']
   )

ClearOnChange here is a decorator like AddAnotherWidgetWrapper or AdminAddAnotherWidgetWrapper. Could it:

- add an attr for widget.render(),
- clear on change's js would pick it up and register a callback that clears the value of each field with a data-clear-on-change attr or something like that ?

Otherwise would it work to connect python configuration to js with an attribute like WidgeMixin.clear_on_change=[field list] in favor of ForwardExtrasMixin.unselect_if_forward_changed as suggested in the PR ?

Also you have my best regards for your bravura, you'll make it do it ! Feel free to come over on irc, too.

**Comment by luzfcb** [comment]
@jpic thanks again for giving a little of your time to look at this.

I liked `WidgeMixin.clear_on_change=[field list]`,  but also would not mind to use a `ClearOnChangeWrapper`. any of the choices is good for me

about the tests, well, I do not know exactly how to do it.

**Comment by jpic** [comment]
NP @luzfcb actually it took more like a couple of hours ;)

Perhaps you could copy the django-addanother repository, and change it to provide ClearOnChangeWrapper instead of AddAnotherWrapper, would you like to host it on @yourlabs or on your own github account ?

**Comment by jpic** [comment]
This is sort of similar to #684 in the way that it would be useful to have a nice documented hook for project-specific code like this.

**Comment by jpic** [comment]
So I added some nice documented example in PR #690 please let me know if that works for you !

Also, I'm still willing to mentor you if you want to start a new app for this kind of things, but keep in mind it's a lot of work ;)
