### ISSUE TITLE
Autocomplete disappear when active save_as

### ISSUE THREAD

**Issue by jdelcampo** [yourlabs/django-autocomplete-light#680]
When I activate the save_as=True on a field with the autocomplete activated the autocomplete function disappear.

I try it on a M2M field.

**Comment by jpic** [comment]
I don't understand this question, please do a bit of effort, read the FAQ about asking if necessary.

**Comment by jdelcampo** [comment]
I have a field with autocomplete. All work fine.

When I try to enable the [save_as](https://docs.djangoproject.com/es/1.9/ref/contrib/admin/#django.contrib.admin.ModelAdmin.save_as) feature on admin.py for the model that have a field with autocomplete:
```
class ProductAdmin(admin.ModelAdmin):
    save_as=True
    pass
```
The field with dal activated lost the autocomplete feature and become a standard many to many select field.

Do you understand me?

**Comment by toudi** [comment]
I can try to replicate this, but I can't promise on any deadline.

**Comment by jpic** [comment]
Couldn't replicate after adding save_as=True to TestAdmin.

![2016-05-17-203154_1023x658_scrot](https://cloud.githubusercontent.com/assets/94636/15334513/c6eb5260-1c6e-11e6-8bed-fc6b44c01d85.png)

@jdelcampo try without autocomplete at all, your problem will still be there.

Can we close this issue or is there anything else to do ?

**Comment by jpic** [comment]
I'm going to close it to prevent contributors from re-reading it, please reopen when you feel like it.
