### ISSUE TITLE
Django Haystack Autocomplete - Django Admin

### ISSUE THREAD

**Issue by geekashu** [yourlabs/django-autocomplete-light#694]
Hi, 

I am trying to implement django haystack autocomplete with the help of django-autocomplete-light in django admin. I gone through the example given in autocomplete light tutorial and was able to implement it successfully.  Now in order to get results from haystack i need to change the get_queryset code to return the queryset from haystack. I believe this can be achieved by 
qs = SearchQuerySet().models(Location). Am i going into right direction? Any help is highly appreciated.  Thanks.

**Comment by toudi** [comment]
Sure, this should do the trick. You can use the 'q' parameter to do a full-text-search, haystack has an 'content' field (or something similarily named) which you can apply to the SearchQuerySet() object.

**Comment by geekashu** [comment]
Thank for the reply. This is the code i have for Location autocomplete view. 
```
from dal import autocomplete
from haystack.query import SearchQuerySet
from users.models import Location

class LocationAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        if not self.request.user.is_authenticated():
            return SearchQuerySet().none()

        qs = SearchQuerySet().models(Location).all()

        if self.q:
            qs = qs.filter(city_auto=self.q)

        return qs

```
Now the results i am getting is in this format...
`{

    "pagination": 

{

    "more": true

},
"results": 
[

{

    "id": "1",
    "text": "<SearchResult: users.location (pk='1')>"

},
{

    "id": "703",
    "text": "<SearchResult: users.location (pk='703')>"

},
{

    "id": "773",
    "text": "<SearchResult: users.location (pk='773')>"

},
{

    "id": "1180",
    "text": "<SearchResult: users.location (pk='1180')>"

},`

How do i get the location text not result object.

**Comment by toudi** [comment]
I may be mistaken, but I think that it comes from this:

https://github.com/yourlabs/django-autocomplete-light/blob/master/src/dal/views.py#L60

so you would have to inherit the view and then override the method in question to return some other attribute (the default implementation is casting to str, so that's why __repr__ is called).

cheers.

**Comment by geekashu** [comment]
Yes.. It worked.. Thank you for your kind support.

**Comment by jpic** [comment]
Way to go @toudi :guitar:
