### ISSUE TITLE
crsftoken name change

### ISSUE THREAD

**Issue by mb-senanga** [yourlabs/django-autocomplete-light#701]
I have implemented the new autocomplete light and it works perfectly! But we have a deployment server that uses a different cookie name which is set in environment variables. On that server the autocomplete fails with a permission denied because of the cookie name. 

Is there a way to overwrite the cookiename and set it from the environment variables?

**Comment by jpic** [comment]
No such feature has been contributed yet. From where I'm sitting it seems like your options are either:

- override autocomplete.init.js
- contribute the feature

**Comment by mb-senanga** [comment]
Thank you, for now I have loaded my own autocomplete script ;-)

**Comment by jpic** [comment]
Awesome, would you like to paste it here for reference ?
