### ISSUE TITLE
troubleshooting the loading of resource files related to #651

### ISSUE THREAD

**Issue by thainlnguyen** [yourlabs/django-autocomplete-light#707]
Hello Jpic,
I am little embarrassed to ask for more help on this issue. I accidentally deleted my working django-autocomplete with virtual keyboard support and all the whistle and bells that came with it.

Now I am trying to recreate from scratch, but running into same issue with having an empty Select drop-down box with the "-------" as the default value.

For now I am loading all the resource files .js/.css manually on the login.html since my static files implementation is SNAFU'ed because when I use {{ form.media }} and do a view source I don't see any of the necessary .js/.css files loaded.

I suspect that I am not loading the resource files correctly or it doesn't get registered. But through the console debugger on Chrome I was inspecting the Network tab I do see the following .js files loaded:

jquery-1.12.4.min.js
jquery.init.js
autocomplete.init.js
select2.js

I really could use some good pointers as to where to start debugging. Thank you again for your time!

**Comment by jpic** [comment]
Perhaps select2.min.js is missing, if you have cloned the repo, are you
sure submodules are checked out too ?

**Comment by thainlnguyen** [comment]
Hello Jpic,
thanks for the input and it resolved my issue too! 
i wasn't paying attention to the different versions of auto_complete/select2. js vs. the vendor/select2.min.js.
