### ISSUE TITLE
Select2 static files not checked out

### ISSUE THREAD

**Issue by geekashu** [yourlabs/django-autocomplete-light#709]
Hi,

I am trying to use Select2 widget from dal_select2, since it is not in the package available on pypi (v3.1.6) i tried installing it from github. I used following command to install latest code.
` pip install https://github.com/yourlabs/django-autocomplete-light/archive/master.zip`

Now on starting the server i am getting this error.
```
?: (dal_select2.E001) Select2 static files not checked out
	HINT: Run git submodule update --init in DAL (/home/ashish/Env/backend/lib/python3.4/site-packages)
```
Would appreciate if this can be fixed in master.

**Comment by geekashu** [comment]
Any help is highly appreciated.

**Comment by geekashu** [comment]
Please point me in right direction. I have to run `git submodule update --init` every time i recreate my virtual env.

**Comment by jpic** [comment]
Did you try installing from git with pip or doing git clone with
--recursive ?

**Comment by geekashu** [comment]
@jpic Thanks for the input.. i used this command to install and it worked
`pip install git+https://github.com/yourlabs/django-autocomplete-light.git`

Don't know why it was giving that error if i installed like this...
`pip install https://github.com/yourlabs/django-autocomplete-light/archive/master.zip`

**Comment by jpic** [comment]
I know, the​ zip don't include submodules, it's such a pain, happened to me
a few times before i figured it out.

Would you like to contribute a note about this in the install docs ?

**Comment by jpic** [comment]
Thanks for your contribution !

**Comment by raratiru** [comment]
I receive this error, although I have installed autocomplete-light using pip:

```
$pip install django-autocomplete-light --no-cache-dir
Collecting django-autocomplete-light
  Downloading django-autocomplete-light-3.1.7.tar.gz (49kB)
    100% |████████████████████████████████| 51kB 585kB/s 
Installing collected packages: django-autocomplete-light
  Running setup.py install for django-autocomplete-light ... done
Successfully installed django-autocomplete-light-3.1.7

```

```
SystemCheckError: System check identified some issues:

ERRORS:
?: (dal_select2.E001) Select2 static files not checked out
HINT: Run git submodule update --init in DAL (/home/user/.virtualenvs/project/lib/python3.4/site-packages)
```
There is no git repository whatsoever at this path -or any descendant- to execute the git command, although this -even if it worked- it would not be very convenient. Should I use only the git url?

`pip install -e git+https://github.com/yourlabs/django-autocomplete-light.git#egg=django-autocomplete-light`
