### ISSUE TITLE
Selectize support

### ISSUE THREAD

**Issue by litchfield** [yourlabs/django-autocomplete-light#716]
Sometimes Select2 just doesn't quite fit the bill. 

Drop-in Selectize support --
https://github.com/litchfield/django-autocomplete-light-selectize

It's based on dal_select2, so just change dal_select2 to dal_selectize and use the widgets/views therein.

**Comment by jpic** [comment]
Awesome ! Keep up the great work !

**Comment by jpic** [comment]
Do you want to maintain it in your own repo or do you want to maintain it in this repo ?
