### ISSUE TITLE
default value with autocomplete.ModelSelect2

### ISSUE THREAD

**Issue by thainlnguyen** [yourlabs/django-autocomplete-light#717]
Jpic,
Been searching for examples of setting the default value for the Select2 dropdown box through sub-classing the forms.ModelForm class:

```
class UsernameForm(forms.ModelForm):
    myusers = User.objects.filter(is_active=True).order_by("id")
    username = UserModelChoiceField(
        queryset=myusers,
        widget=autocomplete.ModelSelect2(
                url="typeahead",
                attrs={
                    "data-placeholder": "Choose Username",
                    "onChange": "clearPW()",
                    "type":"virtual_keyb"
                },
        ),
    )
    class Meta:
        model = User
        fields = ('username',)
```
Is that the correct place to start with or is this done through jQuery Select2? On a related note the default value for the ```<option>``` tags is the id value.  If I want to change that to something else would I also do that through jQuery Select2? [Been reading this but didn't get any wiser](https://select2.github.io/options.html#data-attributes)

Thanks for reading!
ThaiN

**Comment by jpic** [comment]
Did you try with [initial](https://docs.djangoproject.com/en/1.9/ref/forms/fields/#initial) ?

**Comment by thainlnguyen** [comment]
of course and thank you!
