### ISSUE TITLE
limit results set

### ISSUE THREAD

**Issue by thainlnguyen** [yourlabs/django-autocomplete-light#720]
Hi Jpic,
I remember there was an easy way to set an attribute (limit_choices) to limit the result set displayed in the drop-down select box. Is that functionality still available or has it been taken out?
Thanks,
ThaiN

**Comment by jpic** [comment]
Can you limit it in the view using the list slice notation syntax perhaps ?

**Comment by thainlnguyen** [comment]
Yes, that will most definitely work. The old feature was smart enough to load the next results set when scrolling in the Select drop-down. I am just curious as to why that is no longer supported. Or am I incorrect in assuming that it's no longer available? Anywho, everything is working again. This is just icing on the cake. Thank you again for your prompt responses!
