### ISSUE TITLE
Allowing non-staff users to create entries

### ISSUE THREAD

**Issue by darkaeon10** [yourlabs/django-autocomplete-light#723]
Your docs say "Note that creating objects is only allowed to staff users with add permission by default." 

Is there a way to allow non-staff users to add entries as well?

**Comment by jpic** [comment]
Actually I think the doc is not accurate anymore, the user only needs the
permission now:
https://github.com/yourlabs/django-autocomplete-light/blob/master/src/dal/views.py#L77

You can override the has_add_permission() method to customize.

Would you be able to contribute a fix for the docs please ?

Thanks !
