### ISSUE TITLE
autocomplete.ModelSelect2 does not work, there is no any choice for it

### ISSUE THREAD

**Issue by JohnaXu** [yourlabs/django-autocomplete-light#724]
I am sorry to ask help from you , that is I want to use  django-autocomplete-light for the foreign key in the form. But it returns me the error as follows:
`select2.js:25 Uncaught TypeError: $(...).select2 is not a function(anonymous function) @ select2.js:25jQuery.event.dispatch @ jquery.js:4435elemData.handle @ jquery.js:4121jQuery.event.trigger @ jquery.js:4350(anonymous function) @ jquery.js:4901jQuery.extend.each @ jquery.js:374jQuery.fn.jQuery.each @ jquery.js:139jQuery.fn.extend.trigger @ jquery.js:4900initialize @ autocomplete.init.js:45jQuery.extend.each @ jquery.js:374jQuery.fn.jQuery.each @ jquery.js:139(anonymous function) @ autocomplete.init.js:50fire @ jquery.js:3099self.fireWith @ jquery.js:3211jQuery.extend.ready @ jquery.js:3417completed @ jquery.js:3433`

With the help of this 

> link:http://stackoverflow.com/questions/37143571/django-autocomplete-light-not-working-select2-is-not-a-function/38719460#38719460

I  rearranged the INSTALLED_APPS in the settings.py  as follows:
`INSTALLED_APPS = [
'admin_bootstrapped_plus',
'django_admin_bootstrapped',
'django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.sites',
'django.contrib.messages',
'django.contrib.staticfiles',
'dal',
'dal_select2',
"webui",
"membership",
"hotel",
"transaction",
'django.contrib.admin',
"gunicorn",
]
`
But the error is also there.

According to this link:

> http://stackoverflow.com/questions/20034522/select2-is-not-a-function

the error raises if your js files where you have bounded the select2 with select box is loading before select2 js files. Please make sure files should be in this order like:Jquery, select2 js, your js.

But I do not know how to reorder them.

**Comment by jpic** [comment]
It's in your template.

**Comment by jpic** [comment]
Hi ! Did you figure it out ? Moved on ?

**Comment by JohnaXu** [comment]
Ｉam sorry that I already forget this problem and use other technology solve it

**Comment by jpic** [comment]
Awesome, thanks for the info !

**Comment by crazyzubr** [comment]
I have this problem with Django 1.10.1 and default admin. After upgrade Django to 1.10.3  problem disappeared.
