### ISSUE TITLE
NameError: name 'dal_queryset_sequence' is not defined

### ISSUE THREAD

**Issue by aassdd654** [yourlabs/django-autocomplete-light#725]
code line: location = dal_queryset_sequence.fields.QuerySetSequenceModelField(
NameError: name 'dal_queryset_sequence' is not defined

I copied from following example in my form.py: 
class TestForm(autocomplete.FutureModelForm):
    location = dal_queryset_sequence.fields.QuerySetSequenceModelField(
        queryset=autocomplete.QuerySetSequence(
            Country.objects.all(),
            City.objects.all(),
        ),
        required=False,
        widget=dal_select2_queryset_sequence.widgets.QuerySetSequenceSelect2('location-autocomplete'),
    )

    class Meta:
        model = TestModel

Can you help to check why "NameError: name 'dal_queryset_sequence' is not defined" is happening?

**Comment by jpic** [comment]
You need to import it

**Comment by aassdd654** [comment]
Hi Thanks, I have imported following:

from dal import *
from dal import autocomplete
from dal_select2_queryset_sequence.views import *
from queryset_sequence import *
from dal.widgets import *
from dal.views import *
from dal_queryset_sequence.views import *
from dal_select2 import *
from dal_queryset_sequence import *

is there anything I missed?

Thanks,

**Comment by aassdd654** [comment]
Hi I retarted the file, and the code is working!

Thanks,
