### ISSUE TITLE
'module' object has no attribute 'Select2QuerySetView'

### ISSUE THREAD

**Issue by bennyrock20** [yourlabs/django-autocomplete-light#726]
I have the following problem when running my application:

autocomplete.Select2QuerySetView.as_view(model=Product), AttributeError: 'module' object has no attribute 'Select2QuerySetView'

I installed the library correctly by pip, and I have imported into settings.py.

Thanks for your help,

**Comment by jpic** [comment]
Perhaps you can debug this with pdb.set_trace() at the top of
autocomplete.py ?

**Comment by Kirembu** [comment]
Ran into the same issue:

Adding "dal" and "dal_select2" to the INSTALLED_APPS fixed it:

> Then, let Django find static file we need by adding to INSTALLED_APPS, before django.contrib.admin and grappelli if present:
> 
> 'dal',
> 'dal_select2',
> # 'grappelli',
> 'django.contrib.admin',

https://django-autocomplete-light.readthedocs.io/en/master/install.html#install-in-your-project

**Comment by jpic** [comment]
Awesome, perhaps you could add a FAQ with the exact error message so that people find the solution when they paste it on google ?

**Comment by jpic** [comment]
Please reopen when active !
