### ISSUE TITLE
Installing DAL using pip -without git- results in error: "Select2 static files not checked out"

### ISSUE THREAD

**Issue by raratiru** [yourlabs/django-autocomplete-light#727]
As stated in #709 and the documentation entry #710 using a zip/archive url of the repo will not contain the necessary git submodules.

This seems to be an issue with simple pip install which installs a gziped file to install the package:

```
$pip install django-autocomplete-light --no-cache-dir
Collecting django-autocomplete-light
  Downloading django-autocomplete-light-3.1.7.tar.gz (49kB)
    100% |████████████████████████████████| 51kB 585kB/s 
Installing collected packages: django-autocomplete-light
  Running setup.py install for django-autocomplete-light ... done
Successfully installed django-autocomplete-light-3.1.7
```
```
SystemCheckError: System check identified some issues:

ERRORS:
?: (dal_select2.E001) Select2 static files not checked out
HINT: Run git submodule update --init in DAL (/home/user/.virtualenvs/project/lib/python3.4/site-packages)
```
Using the git repository url, however, everything works as expected:

`pip install -e git+https://github.com/yourlabs/django-autocomplete-light.git#egg=django-autocomplete-light`

**Comment by njoyard** [comment]
This is a regression with version 3.1.7. If you install 3.1.6, everything is fine.

**Comment by jpic** [comment]
Thanks for the report, seems fixed with 3.1.8.

**Comment by raratiru** [comment]
Indeed 1.3.8 works great, thank you!

**Comment by jpic** [comment]
1000 thx for your feedback keep it up!
