### ISSUE TITLE
Wrong initial value when not using external data source URL

### ISSUE THREAD

**Issue by thauk-copperleaf** [yourlabs/django-autocomplete-light#742]
Is the `Select2` widget meant to be used _without_ an external data source `url`?

I ask because I am trying to use a `Select2` widget with a static list of choices that I provide to the field when the form is created. The field is visualizing a model field that has `blank=True` and `null=True` set on it; in other words, it is optional.

Current behaviour: when the page loads, the form shows the autocomplete field, but it always shows the first "choice" (provided at init time) as selected. If I hit the (x) clear button, the field clears correctly... and the field otherwise works as expected (if I start typing, it autocompletes based on the "choices" given at init time).

If I provide an external data source `url` (that provides the same set of choices given at init time), the field correctly shows as empty when the model instance has that field set to null, and correctly shows the appropriate value when the field is not null.

Reading through some of the select2 project's issues list, they suggest adding an empty "placeholder" option (e.g.: `<option></option>`). However, `select2.js` from this library will remove any such blank options:

    // This widget has a clear button
    $(this).find('option[value=""]').remove();

So I'm not sure if I'm doing something wrong, or I've hit a use case that wasn't tried before and this is a bug.

    class AutocompleteUserField(forms.ChoiceField):
        def __init__(self, label, choices):
            widget = autocomplete.Select2(attrs={
                                              "data-placeholder": "Search user by name...",
                                              "data-minimum-input-length": 1
                                          })
            super(AutocompleteUserField, self).__init__(choices=choices,
                                                        required=False,
                                                        widget=widget,
                                                        label=label)

    class MyForm(forms.ModelForm):
        assignee_id = AutocompleteUserField(label="Choose user", choices=[])

        def __init__(self, *args, **kwargs):
            super(MyForm, self).__init__(*args, **kwargs)
            self.fields["assignee_id"].choices = self.get_user_choices()

        def get_user_choices(self):
            #
            # calls a celery task to return a list of tuples...
            #
            return user_choices

**Comment by thauk-copperleaf** [comment]
Proposed fix in #743

**Comment by jpic** [comment]
A feature for list backed autocompletes was just merged: http://django-autocomplete-light.readthedocs.io/en/master/tutorial.html#autocompleting-based-on-a-list-of-strings

But i don't think it fixes your issue, could you please check it out ?

Meanwhile I'm trying to reproduce your issue locally.

**Comment by thauk-copperleaf** [comment]
Thanks for the pointer!

My form is being displayed via the admin, so I'm not using a view, so I'm not sure subclassing `autocomplete.Select2ListView` will work for me.

I was trying to figure out why the `$(this).find('option[value=""]').remove();` bit was introduced. I dug through git history as best I could, and as far as I can tell, it's been in there for years. Was there a bug that line was meant to fix? Especially because the select2 library basically needs an `<option></option>` tag for the placeholder to work. You an also see that by inspecting the HTML on their [examples page](https://select2.github.io/examples.html).

**Comment by thauk-copperleaf** [comment]
Looking at it more, I'm sure `Select2ListView` doesn't help, because it's still using a `url` to fetch data. I don't want to have any external `url` datasource; I am pre-populating the choices list.

**Comment by jpic** [comment]
For `$(this).find('option[value=""]').remove();`, as the comment mentions, the widget has a clear button. So we don't need the empty option, but it doesn't harm.

I'm indeed not fond of the empty option, but can live with it.

**Comment by jpic** [comment]
Fixed in #743
