### ISSUE TITLE
dal.forward doesn't exist in 3.1.8

### ISSUE THREAD

**Issue by LegoStormtroopr** [yourlabs/django-autocomplete-light#747]
This breaks some of the documentation thats on ReadTheDocs.

Was there a reason this was removed?

**Comment by jpic** [comment]
I don't understand.

**Comment by gagarski** [comment]
ReadTheDocs shows docs for `master` branch by default, so it contains documentation for features that have not been released yet. `dal.forward` package is one of them.

BTW, probably new versions (from 3.1.4 to 3.1.8) should be added to the version chooser at the bottom.

**Comment by LegoStormtroopr** [comment]
Yeah my bad, the ReadTheDocs says at the top v3.1.7 so I had assumed that it was the docs for v3.1.7, and then noticed that the module `dal.forward` was missing.

But thanks to @jpic's response I know to not bother reporting bugs or submitting PRs here. I'll try find another library to not bother you again.

**Comment by jpic** [comment]
I wasn't bothered, I just didn't understand.

**Comment by gagarski** [comment]
> I suspect this comes from docs/conf.py. So I'm not sure what we should have in there, perhaps just the branch name ?

Releases are just git tags, right? So there should be `master` for any untagged revision and something like `3.1.x` for tagged which is not very convenient.
