### ISSUE TITLE
"create choices that don't exist yet" results in multiple copies of choices.

### ISSUE THREAD

**Issue by lhsdaniel** [yourlabs/django-autocomplete-light#754]
Thanks for all the help and good work!

![repeat](https://cloud.githubusercontent.com/assets/8784756/19008327/79da1ce2-8738-11e6-994e-5989b382d309.png)

I got this when trying to create this "new" choice. This feature used to work just fine before I made a major change on front-end, putting the model form in a Bootstrap pop-up Modal, without touching models or forms. So I am kind of confused on what could possibly be causing this problem.

https://github.com/lhsdaniel/test

My current repository if by any chance you would like to take a look

**Comment by jpic** [comment]
Seems like a select2 issue doesn't it ?

**Comment by lhsdaniel** [comment]
Actually I figured it out. I had a calendar widget using jquery.min.js 1.8.3 and this is the source of conflict. deleting it solve the problem.
