### ISSUE TITLE
Hard to select items in IE10 Mobile

### ISSUE THREAD

**Issue by vtbassmatt** [yourlabs/django-autocomplete-light#76]
The dropdown menus are really hard to tap in IE10 Mobile (Windows Phone 8). I have to zoom way in to successfully select an item. At the default zoom using Bootstrap's responsive CSS package, most of my taps are recognized as clicking the label of the field below. Works fine on Mobile Safari (iOS 6).

When I get a chance, I'll create an isolated test case, try to debug, and (if I find a solution) submit a patch. Creating a tracking issue for now.

It may be an interaction between this package and Crispy Forms - I haven't tried without Crispy.

**Comment by jpic** [comment]
Hi Matt !

How's IE support these days ?

Did the IE dev team had the chance to take a look ?

Cheers

**Comment by vtbassmatt** [comment]
I never could get them to engage. Luckily, it's working on IE11 which shipped with Phone 8.1. Since I'm the only user of my app and that's the OS I have, we're good :)

I think I broke something because it _stopped_ working on my wife's iPhone 6. But since I haven't needed it, I haven't investigated. And I'm pretty sure it's my fault because it was working on iOS in the past.

Thanks for checking in!

Sent from my Windows Phone

-----Original Message-----

**Comment by jpic** [comment]
Ok Matt it's awesome that the bug is fixed in IE 11 ;)

Can we close this issue now ?

**Comment by vtbassmatt** [comment]
Yes! I forgot it was still open. Thanks.

Sent from my Windows Phone

-----Original Message-----

**Comment by jpic** [comment]
Thanks a heap !
