### ISSUE TITLE
CI Selenium tests are broken

### ISSUE THREAD

**Issue by gagarski** [yourlabs/django-autocomplete-light#761]
See [here](https://travis-ci.org/yourlabs/django-autocomplete-light/jobs/166495794)

All tests produce the following error:

```
WebDriverException: Message: 'geckodriver' executable needs to be in PATH.
```

**Comment by jpic** [comment]
I know I checked it but didn't find a native solution, ​but I think pinning
selenium version to the last one that worked would work.

**Comment by gagarski** [comment]
Whatever it was, I don't think that it's here anymore.
