### ISSUE TITLE
Global navigation search box in v3

### ISSUE THREAD

**Issue by ashishbb** [yourlabs/django-autocomplete-light#762]
In v2, there was a simple method of creating a gllobal navigation search box by overriding js. Is there a similar equivalent in v2?

**Comment by jpic** [comment]
Thanks a lot for asking, the example for v2 actually is still completely valid:

 http://django-autocomplete-light.readthedocs.io/en/v2/navigation.html

However, autocomplete.js has moved from django-autocomplete-light to jquery-autocomplete-light repository:

https://github.com/yourlabs/jquery-autocomplete-light

More exactly here:

https://github.com/yourlabs/jquery-autocomplete-light/blob/master/src/autocomplete.js

Please, can you propose a patch to the documentation where you would have expected to find this information ?

**Comment by ashishbb** [comment]
Thank you very much for the response! So navigation autocomplete does not use select2 like most of the new v3 tutorials?

And I would've expected to find the updated navigation autocomplete tutorial at 

[http://django-autocomplete-light.readthedocs.io/en/3.1.3/install.html](http://django-autocomplete-light.readthedocs.io/en/3.1.3/install.html)
 
as this follows the updated format for all the other v3 tutorials.

I also have some security concerns regarding navigation autocomplete but I assume that would be better sorted out through email?

Thanks again.

**Comment by jpic** [comment]
I'm a bit affraid there's nothing I'll be able to do for you but yeah go ahead and send an email to the security mailing list.
