### ISSUE TITLE
Forward field sending empty dict to AutocompleteView.

### ISSUE THREAD

**Issue by astarrh** [yourlabs/django-autocomplete-light#766]
Forms.py:
```
class PurchaseForm(forms.ModelForm):
    commodity = forms.ChoiceField(
        queryset=Commodity.objects.all(),
        widget=autocomplete.ModelSelect2(url='commodity-autocomplete'),
        required=False,
    )

    class Meta:
        model = Purchase
        fields = [ "variety",]
        widgets = { 'variety': autocomplete.ModelSelect2(url='variety-autocomplete', forward=['commodity']),}
```

Views.py:
```
class VarietyAutocompleteView(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = Variety.objects.all()
        print(self.forwarded)
        commodity = self.forwarded.get('commodity', None)
        if commodity:
            qs = qs.filter(commodity=commodity)

        if self.q:
            qs = qs.filter(name__istartswith=self.q)

        return qs
```

Both widgets work on the page, but nothing is forwarded to the view. `self.forwarded` prints out as an empty dict. Is this because I am using a foreign key relationship or because I'm attempting to forward the results from another autocomplete widget? I feel like I used to be able to do this.

EDIT: The issue persists, even if I remove both the autocomplete widget and the required argument and even if I try to set a constant value with `field.Const()`.

**Comment by gagarski** [comment]
Hi!

Can you please provide a minimalistic example project to reproduce your issue?

**Comment by gagarski** [comment]
Hi!

Can you please provide a minimalistic example project to reproduce your issue (the way your form is rendered into HTML can matter and it's hard to debug anything without it)?

Your form and autocomplete view look fine for me now (except for `ChoiceField` instead of `ModelChoiceField` which is obviously a typo here).

Also make sure that you are using DAL 3.2.1. There were some problems with forward feature in 3.2.0.

**Comment by astarrh** [comment]
Sorry, I ended up having to swap out DAL for a different solution in the interest of time. I will re open if I can circle back around on it in a couple of week.
