### ISSUE TITLE
Autocomplete from input textbox

### ISSUE THREAD

**Issue by ibnbay99** [yourlabs/django-autocomplete-light#780]
How to reproduce Autocomplete from input textbox, specially from PR #749 ...?

Thanks

**Comment by jpic** [comment]
Please try not to open duplicate issues.

Seems like PR #749 is pretty detailed, if you have any question about it please ask it there.

Please try to ask specific questions, not like "why doesn't it work ?", see [reporting bugs howto](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) for details.
