### ISSUE TITLE
search_fields attribute / property

### ISSUE THREAD

**Issue by toudi** [yourlabs/django-autocomplete-light#783]
Hello. I was looking trough the source code and the tutorial / documentation.

Here's the code from documentation, when it comes to registering an autocomplete view:

```
class CountryAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        # Don't forget to filter out results depending on the visitor !
        if not self.request.user.is_authenticated():
            return Country.objects.none()

        qs = Country.objects.all()

        if self.q:
            qs = qs.filter(name__istartswith=self.q)

        return qs
```

However, I was wondering whether we could keep simple things simple. Namely, when we register the autocomplete view, like so:

```
urlpatterns = [
    url(
        r'^country-autocomplete/$',
        CountryAutocomplete.as_view(),
        name='country-autocomplete',
    ),
]
```

could we have a simpler syntax, something like..

```
urlpatterns = [
    url(
        r'^country-autocomplete/$',
        name='country-autocomplete',
        model=Country,
        search_fields=('foo', 'bar__baz'),
    ),
]
```

then of course the underlying logic would construct a Q() object:

```
qs = super( something, self).get_queryset()
if self.q:
    filters = Q()
    for field in self.search_fields:
        filters |= Q(**{'%s__icontains' % field: self.q})
    qs = qs.filter(filters)
```

What I mean is that I totally get the point of doing a generic view when there is complex logic involved (like creating objects, complex / custom filtering, etc, etc, etc). However dal can also be used to very simple tasks and this whole block of code (extending a class) contains a single method to handle simple filtering - seems to be an overkill.

If you would agree to such changeset, I would be more than happy to provide a PR

my kindest regards,

**Comment by jpic** [comment]
Hi Mateusz !

Did you mean to show an example like this ?

```
urlpatterns = [
    url(
        r'^country-autocomplete/$',
        name='country-autocomplete',
        dal.ModelSelect2Autocomplete(
            model=Country,
            search_fields=('foo', 'bar__baz'),
        )
    ),
]
```

I really like this, but I think any kind of search_fields logic should be maintained in a search app rather than in django-autocomplete-light, is there any way we could reuse [django-search-views](https://github.com/inmagik/django-search-views) ? Here's an example in their README which shows they already have some kind of query building logic: 

```
from search_views.search import SearchListView
from search_views.filters import BaseFilter

class ActorsFilter(BaseFilter):
    search_fields = {
        'search_text' : ['name', 'surname'],
        'search_age_exact' : { 'operator' : '__exact', 'fields' : ['age'] },
        'search_age_min' : { 'operator' : '__gte', 'fields' : ['age'] },
        'search_age_max' : { 'operator' : '__lte', 'fields' : ['age'] },            

    }

class ActorsSearchList(SearchListView):
    model = Actor
    paginate_by = 30
    template_name = "actors/actors_list.html"
    form_class = ActorSearchForm
    filter_class = ActorsFilter
```

**Comment by jpic** [comment]
Also note that the whole point of making the user extend the class is security. I don't want any newcomer to have private data leaked because they forgot to secure an autocomplete.

An example measure we can take against this would be to allow only staff users by default, and require users to pass an arg like "insecure=True" to as_view().

**Comment by toudi** [comment]
well, I suppose it depends on where you concider the software bloat to be ;) My whole point was that, if I have to extend a class in order to do a simple search, and the code would be a 99% copy of the one from the documentation, then for me this would be a definition of a software bloat. 

I have absolutely nothing against securing the request by default (As it is secured in the documentation-provided code), I am merely trying to think of a compromise so that one wouldn't have to extend (and do a carbon copy of) the provided code in order to do a simple search.

If you inspect line no. 69 of the dal/views.py you will find that the default search_fields is already there. I just started thinking about it when I was using dal in a following scenario:

```
class Parent( ... ):
    first_name = 
    last_name = 

class Child( ... ):
    first_name = 
```

so I wanted to filter by child first_name or by first or last name of a Parent. The default behaviour of dal is a perfect match for my solution, I merely would need to tweak it a bit, and I don't want to do monkey patching, so I thought that I'd share my insights with thee, o Sire!

kind regards and Merry Christmas! :christmas_tree: :santa:

**Comment by jpic** [comment]
I fully agree with the fact that we shouldn't need to extend the class, and highly appreciate your future contribution, which I'm sure the community will love as well B)

I've just checked [our v2 code](https://github.com/yourlabs/django-autocomplete-light/blob/v2/autocomplete_light/autocomplete/model.py) as well. It's the one that has the best features ... And the community has put a lot of hard work into it, I mean, generating an SQL query to support all databases versions, was indeed a lot of work, but it has the "split_words" option which the users like a lot. If that's indeed the best, forget about my consideration for software bloat, and let's do this.

Your contribution is welcome ! I've been working my ass of the last days to get the tests to pass again, and here I am with only 5 failures left locally hehehe I hope to finish this soonish

My best regards to you and your loved ones dear Mateusz

**Comment by toudi** [comment]
wow, I just looked at the link you pointed and it indeed has all that is required. it seems that I was simply looking in a wrong place. I'll try to dig this some more to see how one can combine the model with a generic view. Then the least I could do would be to document this :D

**Comment by jpic** [comment]
Wait, the code is not in v3 yet, so you'll have the opportunity to be the hero and add this from v2 to v3 !

**Comment by toudi** [comment]
then dal would be the next greatest thing after sliced bread! I'll try to tackle this

**Comment by jpic** [comment]
Thanks for the kind words and for your efforts ! always appreciated !​

Looking forward to read more about it ;)

**Comment by jpic** [comment]
I'm just seeing that tests fail with postgresql because of duplicate key, probably at some point the sequence goes foobar.

However, tests on sqlite have been fixed already.

**Comment by toudi** [comment]
well, I'd say that is one of multiple ways of spending your Christmas morning :D

**Comment by jpic** [comment]
Travis is better available at this time of the year xD

**Comment by toudi** [comment]
sorry, I had a bit of things on my mind but I have just started to work on this feature. So I hope I should be able to finish this in the current decade :calendar:

**Comment by toudi** [comment]
Just managed to find some free time to code today, this feature is not dead yet. So terribly sorry for the delay :(

**Comment by mik-laj** [comment]
I guess it's worth the look to be identical to django.admin, so I just leave the link
https://github.com/django/django/blob/c19b56f633e172b3c02094cbe12d28865ee57772/django/contrib/admin/options.py#L887-L918
