### ISSUE TITLE
Fill two other fields depending on autocomplete selection

### ISSUE THREAD

**Issue by teconomix** [yourlabs/django-autocomplete-light#787]
Hi there,

I would like to fill two other fields automatically depending upon the selection someone makes in an autocomplete field. However, my java script is not that good, so I don't realy know where to start. Any help is very much appreciated.

User submit there publiciced papers. There is a "person" autocomplete field in a formset (its a many to many realation for authors and other people that worked towards the publication). If a user chooses a person, I want that persons name and family name automatically filled in two other fields in that formset, so that users can make changes (also, it is a prerequisite from the data modell). Same if they change or delete the selected person.

![Screenshot](https://dl.dropboxusercontent.com/u/85856/bilder/screenshotPersonName.png)

I thought best would be to have a view for name and a view for family nam in order to retrive those two with the id I could get from the autocomplete field.

However, how do I do the asyncrounos retrival of the names and fill them into the two fields?

Thank you!

Best
Teconomix

**Comment by jpic** [comment]
Perhaps [$.change](https://api.jquery.com/change/) will work ?

**Comment by teconomix** [comment]
I started with adding the data to the autocomplete - result. But how can I now fill it into the other fields on selection? $change seems to be the right  direction. But how can I access the data from the result? Also, it is a formset... I am a bit lost here.

`
class PersonAutocomplete(LoginRequiredMixin, autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = KombiPerson.objects.all().order_by('nachname', 'vorname')
        if self.q:
            qs = qs.filter(Q(vorname__icontains=self.q) | Q(nachname__icontains=self.q))
        return qs

    def get_results(self, context):
        """Return data for the 'results' key of the response."""
        return [
            {
                'id': self.get_result_value(result),
                'text': self.get_result_label(result),
                'vorname': self.get_vorname(result),
                'nachname': self.get_nachname(result),
            } for result in context['object_list']
        ]

    def get_vorname(self, result):
        """Return the value of a result."""
        return result.vorname

    def get_nachname(self, result):
        """Return the value of a result."""
        return result.nachname
`

**Comment by jpic** [comment]
Then perhaps you can use [$.val()[(http://api.jquery.com/val/) to get the new value in your change callback ?

I think first try to fix your problem without dal, with a pure select field, then put dal again and let use know if it doesn't work.

**Comment by jpic** [comment]
Not specific to DAL nor Select2, all advice has already been given, closing.
