### ISSUE TITLE
Using ListSelect2 widget in the admin does not show previously saved values

### ISSUE THREAD

**Issue by ami-fairfly** [yourlabs/django-autocomplete-light#789]
Using these simple definitions:
```
class TestAutocomplete(autocomplete.Select2ListView):
    def get_list(self):
        return ['test1','test2']

class TestForm(forms.ModelForm):
    class Meta:
        model = TestModel
        fields = "__all__"
        widgets = {
            'textual_field': autocomplete.ListSelect2(url='testurl'),
        }
```

The autocomplete box does not show the previously saved value

**Comment by jpic** [comment]
Did you try a django select widget instead of an autocomplete widget ?

**Comment by jpic** [comment]
Sorry but it works for me.

**Comment by ami-fairfly** [comment]
It does :/

Strange, we have autocomplete widgets all over the place but they are all model based. The only thing different here is trying to use a List one

**Comment by jpic** [comment]
Wait, how on earth is the widget supposed to know what choices it has in your example ?!

**Comment by jpic** [comment]
Did you try something like in the documentation ? http://django-autocomplete-light.readthedocs.io/en/master/tutorial.html#autocompleting-based-on-a-list-of-strings
```
def get_choice_list():
    return ['France', 'Fiji', 'Finland', 'Switzerland']


class CountryForm(forms.ModelForm):
    country = autocomplete.Select2ListChoiceField(
        choice_list=get_choice_list,
        widget=autocomplete.ListSelect2(url='country-list-autocomplete')
    )
```

**Comment by alabarga** [comment]
Same problem here, also only with List based fields

**Comment by jpic** [comment]
Try autocomplete.Select2ListChoiceField
