### ISSUE TITLE
ModelSelect2Multiple AttributeError('list' object has no attribute 'queryset')

### ISSUE THREAD

**Issue by asdfkaba** [yourlabs/django-autocomplete-light#790]
Hello, i'm having the same Issue like the guy in the following post.
http://stackoverflow.com/questions/40822373/django-autocomplete-light-error-list-object-has-no-attribute-queryset
Changing to ListSelect2 like suggested(no option for me) in the answer works, commenting out the filter_choices_to_render function also( with ModelSelect2Multiple):

dal/widgets.py
```

class QuerySetSelectMixin(WidgetMixin):
    """QuerySet support for choices."""
    def filter_choices_to_render(self, selected_choices):
        """Filter out un-selected choices if choices is a QuerySet."""
        self.choices.queryset = self.choices.queryset.filter( ...
            pk__in=[c for c in selected_choices if c]
        )
```

Is it a bug or am i doing something wrong? 

It worked before i made some changes, the only relevant seems for me passing as url attribute to ModelSelect2Multiple a url via reverse:
`autocomplete.ModelSelect2Multiple(url=reverse('project:userac', kwargs={"pk": project_id}))
`
https://github.com/yourlabs/django-autocomplete-light/issues/763 didn't work for me

http://dpaste.com/2T06R0Q
if i change:
```
class QuerySetSelectMixin(WidgetMixin):
    """QuerySet support for choices."""

  def filter_choices_to_render(self, selected_choices):
        super.filter_choices_to_render(self, selected_choices)
        """Filter out un-selected choices if choices is a QuerySet."""
        # self.choices.queryset = self.choices.queryset.filter(
        #    pk__in=[c for c in selected_choices if c]
        #)
```

it works

**Comment by Nabu-thinker-ru** [comment]
Greetings!

i've had similar problem. i've solved by using correct field. in my case i accidentally used form.IntegerField instead form.ModelChoiceField... and i almost found solution due to your report and patching around filter_choices_to_render... but lucky me, i've noticed the field

**Comment by asdfkaba** [comment]
I don't get what you mean. I'm using the Widget on a ManyToMany-Field.
Like i said it worked till i needed a pk from the url to filter my queryset. To do that i initialized the form.fields["blablub"].widget in the get_form method in my CreateView to access the kwargs.

`class Issue_Create_View(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Issue
    template_name = 'issue/issue_create_view.html'
    form_class = LimitKanbanForm

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        form = form_class(**self.get_form_kwargs())
    
        project_id = Project.objects.get(id=self.kwargs.get('pk'))

        form.fields['assignee'].widget = autocomplete.ModelSelect2Multiple(
                                    url=reverse_lazy('project:userac', kwargs={"pk": project_id})
                                        )
`

```
class LimitKanbanForm(forms.ModelForm):
    class Meta:
        model = Issue
        fields = ['title', 'kanbancol', 'due_date', 'type', 'assignee',
                  'priority', 'description', 'storypoints', 'dependsOn']
```

```
class UserAutoComplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return get_user_model().objects.none()

        if self.kwargs.get('pk'):
            project_id = self.kwargs.get('pk')
            qs = get_user_model().objects.all().filter(developer=project_id)
        else:
            qs = get_user_model().objects.all()

        if self.q:
            qs = qs.filter(username__istartswith=self.q)

        return qs
```

**Comment by jpic** [comment]
Information is incomplete here, we don't even know what the assigne model field is like.

Can you reproduce it in a new app of the test_project ? I don't think we can help as much as if you give us a reproductible example.

Thanks

**Comment by asdfkaba** [comment]
i'll do when i have time, i'll link it here.
Thanks for your help

**Comment by asdfkaba** [comment]
Soo i created a simple django project do illustrate the error:
https://github.com/asdfkaba/dal_example/tree/master

**Comment by asdfkaba** [comment]
Anybody looked at this and can Teller ne WhatsApp i'm doing wrong.
Ort can somebody can show me a Wirkung example with passing a to the queryset view, e.q. Issue/5/edit

**Comment by jpic** [comment]
Did you try running `manage.py migrate` ?

**Comment by jpic** [comment]
I could reproduce the issue in the test project, should be fixed in #796​
which I'll merge as soon as it passed tests.

**Comment by asdfkaba** [comment]
Okay, super ;) you had a look at my originial problem? I can't imagine nobody had this scenario before.

**Comment by jpic** [comment]
Well, @Nabu-thinker-ru suggested that it could be because you're using an form field that's not compatible with the model field, it doesn't seem like you've answered that, it's a common problem.

Another thing that makes your issue really hard to digest is the pollution created by un-necessary information, such as a bunch of fields in the modelform definition which are completely irrelevant to the issue.

Perhaps if you could try to remove unnecessary things from the code you paste and spotting mistakes will already be easier for a volunteer who's going to try to help ;)

Thanks @asdfkaba

**Comment by asdfkaba** [comment]
Yeah, i posted a link to an example lightweight django application, which also produces this error, but i can also paste the essential snippets here:

urls.py global
`urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^issue/', include('testapp.urls')),
]`

urls.py applicaton
`urlpatterns = [
    url(r'^create/?$', Issue_Create_View.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/edit/?$', Issue_Edit_View.as_view(), name='edit'),
    url(r'^(?P<pk>[0-9]+)?$', Issue_Detail_View.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/ac/?$', get_possible_Issues.as_view(), name='issueac'),
        ]
`
models.py
`class Issue(models.Model):
    title = models.CharField("Title", max_length=100)
    dependsOn = models.ManyToManyField('self',
                                       verbose_name="Depends on",
                                       related_name="dependent",
                                       blank=True,
                                       )
`
forms.py
`class LimitKanbanForm(forms.ModelForm):
    class Meta:
        model = Issue
        fields = ('title', 'dependsOn')`

views.py
`class Issue_Edit_View(UpdateView):
    model = Issue
    template_name = 'issue/issue_edit_view.html'
    form_class = LimitKanbanForm

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        form = form_class(**self.get_form_kwargs())
        form.fields['dependsOn'].widget = autocomplete.ModelSelect2Multiple(url=reverse('issueac', kwargs = { "pk": self.kwargs.get('pk') }))
        return form

    def get_object(self):
        return Issue.objects.get(id = self.kwargs.get('pk'))
`

to make that clear, i'm using a ModelSelect2Multiple widget on a ManyToMany-Field

**Comment by jpic** [comment]
Ok, what URL does it hits according to the server logs ?

**Comment by jpic** [comment]
Where is the lightweight application link you posted please ?

**Comment by jpic** [comment]
Also, it's great when the code you paste is executable, so you can leave the imports in there ;)

**Comment by asdfkaba** [comment]
https://github.com/asdfkaba/dal_example/tree/master

it seems the widget isnt even calling the url, the error occurs before

```
[31/Jan/2017 00:16:54] "GET /issue/create HTTP/1.1" 200 580
[31/Jan/2017 00:17:00] "POST /issue/create HTTP/1.1" 302 0
[31/Jan/2017 00:17:00] "GET /issue/1 HTTP/1.1" 200 79
Not Found: /issue/edit
[31/Jan/2017 00:17:05] "GET /issue/edit HTTP/1.1" 404 2697
Internal Server Error: /issue/1/edit
Traceback (most recent call last):
  File "/home/moritz/dal_example/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/moritz/dal_example/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/moritz/dal_example/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/home/moritz/dal_example/venv/lib/python3.5/site-packages/django/template/response.py", line 109, in render
    self.content = self.rendered_content
  File "/home/moritz/dal_example/venv/lib/python3.5/site-packages/django/template/response.py", line 86, in rendered_content
    content = template.render(context, self._request)
  File "/home/moritz/dal_example/venv/lib/python3.5/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/moritz/dal_example/venv/lib/python3.5/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/home/moritz/dal_example/venv/lib/python3.5/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/moritz/dal_example/venv/lib/python3.5/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/home/moritz/dal_example/venv/lib/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/moritz/dal_example/venv/lib/python3.5/site-packages/django/template/base.py", line 1044, in render
    output = self.filter_expression.resolve(context)
  File "/home/moritz/dal_example/venv/lib/python3.5/site-packages/django/template/base.py", line 711, in resolve
    obj = self.var.resolve(context)
  File "/home/moritz/dal_example/venv/lib/python3.5/site-packages/django/template/base.py", line 852, in resolve
    value = self._resolve_lookup(context)
  File "/home/moritz/dal_example/venv/lib/python3.5/site-packages/django/template/base.py", line 915, in _resolve_lookup
    current = current()
  File "/home/moritz/dal_example/venv/lib/python3.5/site-packages/django/forms/forms.py", line 289, in as_p
    errors_on_separate_row=True)
  File "/home/moritz/dal_example/venv/lib/python3.5/site-packages/django/forms/forms.py", line 226, in _html_output
    'field': six.text_type(bf),
  File "/home/moritz/dal_example/venv/lib/python3.5/site-packages/django/utils/html.py", line 391, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/home/moritz/dal_example/venv/lib/python3.5/site-packages/django/forms/boundfield.py", line 43, in __str__
    return self.as_widget()
  File "/home/moritz/dal_example/venv/lib/python3.5/site-packages/django/forms/boundfield.py", line 101, in as_widget
    return force_text(widget.render(name, self.value(), attrs=attrs))
  File "/home/moritz/dal_example/venv/lib/python3.5/site-packages/dal/widgets.py", line 129, in render
    widget = super(WidgetMixin, self).render(name, value, attrs)
  File "/home/moritz/dal_example/venv/lib/python3.5/site-packages/django/forms/widgets.py", line 617, in render
    options = self.render_options(value)
  File "/home/moritz/dal_example/venv/lib/python3.5/site-packages/dal/widgets.py", line 116, in render_options
    self.filter_choices_to_render(selected_choices)
  File "/home/moritz/dal_example/venv/lib/python3.5/site-packages/dal/widgets.py", line 161, in filter_choices_to_render
    self.choices.queryset = self.choices.queryset.filter(
AttributeError: 'list' object has no attribute 'queryset'
[31/Jan/2017 00:17:10] "GET /issue/1/edit HTTP/1.1" 500 156928
```

**Comment by jpic** [comment]
This error means that you have a list instead of a queryset in choices: AttributeError: 'list' object has no attribute 'queryset'

**Comment by jpic** [comment]
I think you should have this after instanciating your widget: 

    form.fields['dependsOn'].widget.choices = form.fields['dependsOn'].choices

**Comment by asdfkaba** [comment]
ohaa, yes you were right, that solves the problem.
Thank you very much for your help :)

**Comment by jpic** [comment]
Thanks for your feedback, keep up the great work :guitar:
