### ISSUE TITLE
"getFormPrefix is not a function" when using forward.Const

### ISSUE THREAD

**Issue by tewald** [yourlabs/django-autocomplete-light#792]
Hi!

I'm using this fantastic library, but then I run into a problem.
Here is a form that I use in a inline tab:

```python
class ComponentImageForm(forms.models.ModelForm):

    class Meta:
        widgets = {
            'image': autocomplete.ModelSelect2(
                url='image_autocomplete',
                attrs={
                    'data-html': 'true'
                }
            )
        }
```

It works as expected.
I need to search only for product images, and this is a hard coded key on my image model.
So, adding forward to the mix:

```python
class ComponentImageForm(forms.models.ModelForm):

    class Meta:
        widgets = {
            'image': autocomplete.ModelSelect2(
                url='image_autocomplete',
                forward=(
                    forward.Const('product', 'image_application'),
                ),
                attrs={
                    'data-html': 'true'
                }
            )
        }
```

That gives me a "getFormPrefix() is not a function" error.

What I'm doing wrong?

Thanks!

**Comment by tewald** [comment]
Again, I've found the problem.
I'm using here tinymce, that has hardcoded to load an 1.9.1 jQuery. 
Removing it everything works, including what I reported on #793.
Why, oh why?

Closing as a "caused by other libs".

**Comment by jpic** [comment]
Because after we have registered our own extension on the jquery object, tinymce loads its own jquery and overrides ours which has the extensions loaded with a fresh instance. It's a pretty common issue .
