### ISSUE TITLE
Can't listen to select2 events in django admin

### ISSUE THREAD

**Issue by tewald** [yourlabs/django-autocomplete-light#793]
Hi,

Sorry to bother, but I can't listen to select2 events in django admin.
I did it like indicated on #668, with no success.
Here's some code:

```javascript
$(document).on('autocompleteLightInitialize', '[data-autocomplete-light-function=select2]',
  function () {
    console.log('registering', $(this));
    // is there any better or more correct form?
    var c = $('select#' + $(this).context.id + '.select2-hidden-accessible');
    c.on('select2:selecting', function (evt) {
      console.log('wheee', evt);
    });
  }
);
```
I get the 'registering' messages for all of the selects on my (inline) form, but the 'wheee' message never is shown.

Chrome shows me that I have 2 event listeners for select2:selecting for any of the selects, so I'll say that the register has worked (I guess).

No other errors or messages on the browser console.

The idea is to get the returned data and update the inline row of the form (an image, in this case).

Thanks!

**Comment by jpic** [comment]
Hi Thomas !

It really looks like this question would be better asked for to the select2 user community, it's not specific to DAL - whatever is specific to DAL you've already got to work apparently ^^

Best

**Comment by tewald** [comment]
You're right.
Closing this issue and asking the right people then! ;-)
Thanks for the answer @jpic!

**Comment by tewald** [comment]
After reading some source code (RTFSC), logging around, and learning about jQuery + django admin, I've fixed my problem!

To help future fellow programmers:

DAL is using jQuery 2.2.3 with Select2 plugin loaded, but my script was running on the default Django Admin jQuery (1.9.1) **without** Select2.
To fix it, I changed my script to:

```javascript
(function($){
    $(document).on('autocompleteLightInitialize', '[data-autocomplete-light-function=select2]',
      function () {
        var c = $('select#' + $(this).context.id + '.select2-hidden-accessible');
        c.on('select2:selecting', function (evt) {
          console.log('wheee', evt);
        });
      }
    );
})(django.jQuery);
```

Now it works as expected.

:-)

**Comment by jpic** [comment]
Nice one !
