### ISSUE TITLE
Live demo, static

### ISSUE THREAD

**Issue by dima-kov** [yourlabs/django-autocomplete-light#800]
Live demo site is not displaying good now. http://dal-yourlabs.rhcloud.com/ Static files don't load.

**Comment by markrlondon** [comment]
I'm seeing the same problem.   Can it be fixed?  Thanks!

**Comment by oonid** [comment]
and now the live demo site can be opened at all, HTTP 500 Internal Server Error
http://dal-yourlabs.rhcloud.com/
anyone know what happened?
any other alternative on live DAL demo?
thank you.

**Comment by jpic** [comment]
Live demo fixed in 355db3785a0d58b660fee47e710998d9948ec88b to release soon
