### ISSUE TITLE
Live Demo Exception

### ISSUE THREAD

**Issue by gileadslostson** [yourlabs/django-autocomplete-light#808]
It seems the live demo has `DEBUG` set to `True` and is currently throwing an exception.
![image](https://cloud.githubusercontent.com/assets/698090/23738054/105ecea2-0497-11e7-897d-a32cb402a8ef.png)

**Comment by jpic** [comment]
Fixed !

**Comment by jpic** [comment]
Apparently it's broken again, i don't have time to fix it right now, but know that it's the test_project you can run yourself in the repository meanwhile.

**Comment by gileadslostson** [comment]
Cool =) I just wanted to let you know.

**Comment by jpic** [comment]
Thanks !​
