### ISSUE TITLE
Django 1.11 compatibility

### ISSUE THREAD

**Issue by silviogutierrez** [yourlabs/django-autocomplete-light#812]
I could be wrong, but I believe that Django's 1.11 template rendering feature breaks django-autocomplete-light at the moment.

The following works fine in 1.10 but simply doesn't render in 1.11 (my view won't load because now it's trying to render the default select with thousands of options):

```python

# admin.py
class EntitlementInline(admin.TabularInline):
    model = Entitlement
    form = EntitlementForm
    extra = 0

# forms.py
class EntitlementForm(forms.ModelForm):
    class Meta:
        model = models.Entitlement
        fields = ('__all__')
        widgets = {
            'company': autocomplete.ModelSelect2(url='company_autocomplete'),
            'issue': autocomplete.ModelSelect2(url='issue_autocomplete'),
        }
```

I searched the issue queue and saw no duplicate issues, so I hope this ticket can serve to track the incompatibility.

Thanks for an a great library,

Silvio

**Comment by jpic** [comment]
I recon I'm not quite done adding dj11 support: https://github.com/yourlabs/django-autocomplete-light/pull/797

Contributions welcome !!

**Comment by silviogutierrez** [comment]
Shoot, I went through all the issues but not the PRs! My apologies for the noise.

**Comment by jpic** [comment]
Not a problem, however, a helping hand would be welcome :)​

But you opened this the right day because I happen to be able to free a
handful of hours for this during the next days :P

**Comment by jpic** [comment]
#827 fixes it, should be merged in a matter of hours.

**Comment by silviogutierrez** [comment]
That's great. Sorry I didn't get to help. I use this library a lot, so if I fix or add anything I'll definitely contribute.

**Comment by jpic** [comment]
Thanks my friend, don't worry, it's not over for DAL yet, you'll have your
chance ;)
