### ISSUE TITLE
[Question] How to copy autocomplete field from one form to another

### ISSUE THREAD

**Issue by wkang0** [yourlabs/django-autocomplete-light#818]
I have two exactly the same forms (A and B) except one form A has initial values for a autocomplete fields. The question is how to use javaScript to copy the selected options from form A to form B.

**Comment by jpic** [comment]
Did you see the linked auto completes example and docs ? Even if its not
exactly what you want, you should find the necessary ingredients there !

**Comment by wkang0** [comment]
The question is how to append an option to the autocompleted field. I tried to append a new option with jQuery, but it doesn't show up on the field.

**Comment by jpic** [comment]
Did you try just adding an option element to the select ? It should work:
that is how it supports add-another in the admin.

**Comment by wkang0** [comment]
Yes, I did. But there is no effect. Here is the jQuery code.

$('#id_references').append($("<option></option>").attr('value', '1').text('234235'))

**Comment by jpic** [comment]
Did you try with .append($('option[value=1]')​) ?

**Comment by wkang0** [comment]
Yes. I tried. But it did nothing. The previous method did add option to the the fields but the option does not show up on the box.

**Comment by jpic** [comment]
What do you mean show up on the box ? Be selected ?​

**Comment by wkang0** [comment]
Yes, I means be selected.

**Comment by wkang0** [comment]
This one is working fine. Thanks a lot for your help. 

$("#id_references").append($('\<option selected>\</option>').attr('value', '1').text('Group A')).trigger('change')

**Comment by jpic** [comment]
Good job @wkang0 !
