### ISSUE TITLE
autocomplete fields not initialized when DOM is ready before select2.js is loaded

### ISSUE THREAD

**Issue by apinsard** [yourlabs/django-autocomplete-light#819]
When the DOM is ready before `select2.js` script is loaded, the `autocompleteLightInitialize` event is sent while the listener is not yet set.

This results in autocomplete fields not initialized.

I worked this around by calling `$('[data-autocomplete-light-function]:not(.select2-hidden-accessible)').trigger('autocompleteLightInitialize')` in a script called after `select2.js`.

Is there a more proper way to deal with this ?

**Comment by jpic** [comment]
Interresting, have you tried moving select2.full.js at the top of the widget media list ? https://github.com/yourlabs/django-autocomplete-light/blob/master/src/dal_select2/widgets.py#L26

**Comment by apinsard** [comment]
Actually, we use RequireJS to ensure scripts dependencies. So I set the dependencies as the following:

- jquery.init.js depends on jquery
- autocomplete.init.js depends on jquery.init.js
- select2.full.js depends on autocomplete.init.js
- forward.js depends on select2.full.js
- select2.js depends on forward.js.

I tried the following, according to your comment:

- jquery.init.js depends on jquery
- select2.full.js depends on jquery.init.js
- autocomplete.init.js depends on select2.full.js
- forward.js depends on autocomplete.init.js
- select2.js depends on forward.js.

But this didn't change anything.

To me, the issue lies in the fact that [`autocompleteLightInitialize` event is triggered](https://github.com/yourlabs/django-autocomplete-light/blob/master/src/dal/static/autocomplete_light/autocomplete.init.js#L45) when the [DOM is ready](https://github.com/yourlabs/django-autocomplete-light/blob/master/src/dal/static/autocomplete_light/autocomplete.init.js#L49-L50). Which may be before [the listener is set up](https://github.com/yourlabs/django-autocomplete-light/blob/master/src/dal_select2/static/autocomplete_light/select2.js#L3) unless you call your scripts synchronously at the end of the `<body>` which I don't want to do.

Forcing `select2.js` to be executed before `autocomplete.init.js` with the following precedence:

- jquery.init.js depends on jquery
- select2.full.js depends on jquery.init.js
- select2.js depends on select2.full.js.
- autocomplete.init.js depends on select2.js
- forward.js depends on autocomplete.init.js

Seems to fix the issue. Yet, it looks not entirely satisfying as [`select2.js` uses `get_forwards()`](https://github.com/yourlabs/django-autocomplete-light/blob/master/src/dal_select2/static/autocomplete_light/select2.js#L29) which is defined by `forward.js`, which may not yet be loaded when `get_forwards() is reached.

**Comment by jpic** [comment]
Right, I didn't understand the issue properly, kudos for finding a solution ! Our JS needs love, feel free to submit a PR with a refactor that suits your needs, I'll be more than happy to learn more about JS !

**Comment by sandino** [comment]
Hi!

I'm not sure if my issue has to do with this, but I constantly get the error in console:

> Uncaught ReferenceError: get_forwards is not defined

Installing version 3.1.8 solves the problem.

**Comment by sandino** [comment]
Sorry, that was my bad. After adding

    <script type="text/javascript" src="/static/autocomplete_light/forward.js"></script>

to the template everything works on the last version of dal (currently 3.2.1).

**Comment by apinsard** [comment]
Now fixed in tree.
