### ISSUE TITLE
Test rename feature

### ISSUE THREAD

**Issue by jpic** [yourlabs/django-autocomplete-light#828]
I've just noticed that I merged the forward feature before the tests were actually implemented, is it possible that you add them when you find time ?

**Comment by gagarski** [comment]
Hi James!

There is an app in the test project, named `rename_forward` which uses the same scenaria as `linked_data` app but with (slightly artificial) use of rename and const feature. Are some more tests needed?

**Comment by jpic** [comment]
I found the example app, but not the test that would run the browser to try that it works, have i missed it perhaps ?

**Comment by gagarski** [comment]
There are [test_functional.py](https://github.com/yourlabs/django-autocomplete-light/blob/master/test_project/rename_forward/test_functional.py) and [test_forms.py](https://github.com/yourlabs/django-autocomplete-light/blob/master/test_project/rename_forward/test_forms.py) in the `master` branch, but you removed them in the `fix_tests` branch in [this commit](https://github.com/yourlabs/django-autocomplete-light/commit/4eee301c1cb6c8e4dab532ed3d2fd1e0e81d1ed3). 
Actually the whole `rename_forward` app is just a copy-paste of `linked_data` app and implements the same fucntionality but with artificial use of rename and const feature so the test scenarios are copy-paste too (but actually different model and form are imported into test because of relative import).

**Comment by gagarski** [comment]
I'd be glad to refactor these files to avoid code duplication (seems quite easy) but currently I have no luck in running any Selenium tests at all.
I can browse project pages when `runserver` is running after adding the following lines to the end of settings/base.py:
```python
DEBUG = True
ALLOWED_HOSTS = []
```
but when I run `./manage.py test` every Selenium test fails and all I can see in the browser window is "Server Error (500)" (like even DEBUG is disabled). Also I cannot see any tracebacks from server in my console. Does Django use other settings when running tests? Any ideas?

**Comment by jpic** [comment]
Ok, enable debug with the DEBUG env var. Debugging settings have env vars in this repo. tox.ini shows how to set DJANGO_SETTINGS_MODULE which is a standard django env var. To list environments use `tox -l` and then `tox -e envname`. Configuring LOGGING to stream '*' loggers with DEBUG level to console or file might also help, I've had this issue too and can't reproduce now but nothing more complex than a LOGGING configuration helped me IIRC.

So, there was a bug in the linked_data test code, also present in rename_forward (fix, not applied to your code, because i thought it was unappliable: c4f331197af3b5583faec3d0b5c91d4f18d57490). Feel free to fork fix_test to customize your tests. Otherwise, I can volunteer, if you can contribute pure unit tests instead. I can maintain the functional test codebase but there needs unit tests too to back me up because selenium+travis=time consuming...

**Comment by jpic** [comment]
Perhaps it'll work better with the current master ?​

**Comment by gagarski** [comment]
@jpic Yes, now it's better.
I run tests with the following command:
```
$ DEBUG=True ./manage.py test linked_data.test_functional
```

and Firefox starts and does some clicks but I get these strange errors:
```
$ DEBUG=True ./manage.py test linked_data.test_functional   
Creating test database for alias 'default'...
System check identified some issues:

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_DEBUG.

System check identified 1 issue (0 silenced).
E/Users/kirill/repos/django-autocomplete-light/test_project/.env/lib/python3.6/site-packages/django/core/paginator.py:112: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <QuerySet []>
  UnorderedObjectListWarning
EE
======================================================================
ERROR: test_can_select_option_in_first_extra_inline (linked_data.test_functional.AdminLinkedDataTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kirill/repos/django-autocomplete-light/test_project/linked_data/test_functional.py", line 68, in test_can_select_option_in_first_extra_inline
    self.test_filter_options(story)
  File "/Users/kirill/repos/django-autocomplete-light/test_project/linked_data/test_functional.py", line 38, in test_filter_options
    story.assert_suggestion_labels_are(
AttributeError: 'InlineSelectOption' object has no attribute 'assert_suggestion_labels_are'

======================================================================
ERROR: test_filter_option_in_first_inline (linked_data.test_functional.AdminLinkedDataTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kirill/repos/django-autocomplete-light/test_project/linked_data/test_functional.py", line 63, in test_filter_option_in_first_inline
    self.test_filter_options(story)
  File "/Users/kirill/repos/django-autocomplete-light/test_project/linked_data/test_functional.py", line 38, in test_filter_options
    story.assert_suggestion_labels_are(
AttributeError: 'InlineSelectOption' object has no attribute 'assert_suggestion_labels_are'

======================================================================
ERROR: test_filter_options (linked_data.test_functional.AdminLinkedDataTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kirill/repos/django-autocomplete-light/test_project/linked_data/test_functional.py", line 38, in test_filter_options
    story.assert_suggestion_labels_are(
AttributeError: 'SelectOption' object has no attribute 'assert_suggestion_labels_are'

----------------------------------------------------------------------
Ran 3 tests in 13.583s

FAILED (errors=3)
Destroying test database for alias 'default'...
```

As I can see, `SelectOption` and `InlineSelectOption` definitely have `assert_suggestion_labels_are` method inherited from `BaseStory` class. More strange thing is that these tests work fine when run from PyCharm.

**Comment by jpic** [comment]
I don't know if manage.py test would work but you can try `tox -l` to list environments and `tox -e envname` for a particular one, otherwise reverse tox.ini to find how tests are run, something like setting DJANGO_SETTINGS_MODULE and running py.test would work.

**Comment by gagarski** [comment]
#833

**Comment by jpic** [comment]
:medal_sports:
