### ISSUE TITLE
Forwarded BooleanField always 'on'

### ISSUE THREAD

**Issue by marekjedrzejewski** [yourlabs/django-autocomplete-light#837]
Hi,
I am trying to write an autocomplete in ModelForm, that based on previous, added to form BooleanField shows only only some positions or all when checked. 

Problem is, that the forwarded value is always string 'on', no matter if field is checked or not. If I explicitly set the html value attribute to something else, it shows whatever is there, but if I'd like to use it I'd have to write additional javascript that would set the value attribute on change.

Is there any elegant way to handle this?

**Comment by jpic** [comment]
I think that's a specific case that was not implemented. @gagarski do you have an opinion on this ?

**Comment by gagarski** [comment]
Yeah, in `get_forwards()` we just select inputs by their `name` attribute and call `val()` method, but with checkboxes and radio buttons it does not work. However, it seems easy to fix.

**Comment by jpic** [comment]
@marekjedrzejewski do you want to propose a patch ?

**Comment by marekjedrzejewski** [comment]
For now I'm working around it by this

    // DIRTY HACKS HERE! checkbox not working as expected
    document.getElementById('id_show_paid').value = ''
    document.getElementById('id_show_paid').onclick = function() {
        if (this.checked) {
            this.value = 'True'
        }
        else {
            this.value = ''
        }
    }

on the model form template, but if you're saying that's an easy patch, I could try that when I'm back home.

Wish me luck, that's gonna be the first patch I write to a project not made by me. Adventure, here I come :)

**Comment by jpic** [comment]
I think we're going to need to patch this: https://github.com/yourlabs/django-autocomplete-light/blob/master/src/dal/static/autocomplete_light/forward.js

And also update the test case to forward a boolean: https://github.com/yourlabs/django-autocomplete-light/blob/master/test_project/rename_forward/forms.py

**Comment by marekjedrzejewski** [comment]
Added check for field type on line 42:

    if($field.attr('type') === 'checkbox')
        forwardedData[dstName] = $field[0].checked;
    else
        forwardedData[dstName] = $field.val();

but when I try to test it I can't get the browser to load the updated script. Tried collectstatic, removing forward.js from wsgi folder, even clearing whole directory, but it's still serving me old version of the script.

**Comment by jpic** [comment]
Did you try with CTRL+SHIFT+F5 or CRTL+SHIFT+R ?

If you are using the test_project, have you exported DEBUG=True ?

Otherwise, we have whitenoise serving static files and I'm not sure that doesn't come with a little auto-reload issue.

**Comment by marekjedrzejewski** [comment]
I didn't touch DEBUG, but now that you mentioned it I set DEBUG = True in test_project/settings/base.py, but still the old version gets loaded. And yes, tried ctrl+shift+r, and also clearing browser cache in Chromium developer tools + opening the script file itself. Opening it in Firefox and Epiphany, that I didn't use with it before didn't help either, so that's definitely something on the server side.

**Comment by jpic** [comment]
Are you on windows or linux ?

You need DEBUG to be True before:

https://github.com/yourlabs/django-autocomplete-light/blob/master/test_project/settings/base.py#L108

And

https://github.com/yourlabs/django-autocomplete-light/blob/master/test_project/settings/base.py#L124

You can set it by exporting the DEBUG /environment/ variable, or by editing settings here:

https://github.com/yourlabs/django-autocomplete-light/blob/master/test_project/settings/base.py#L5

If that doesn't help there is an article about static files here that helped a lot of people: 

http://blog.yourlabs.org/post/30382323418/surviving-djangocontribstaticfiles-or-how-to

You can use the `manage.py findstatic` command to see where Django loads static files from on your disk.

**Comment by marekjedrzejewski** [comment]
Linux. Changed the line 5. Now I see that it loads this version from '/usr/lib/python3.6/site-packages/dal/static/autocomplete_light/forward.js'.

I ran it without virtualenv and assumed it would load the version from local repo, but now that I did use virtualenv it keeps giving me the error

    ?: (dal_select2.E001) Select2 static files not checked out
      	HINT: Run git submodule update --init in DAL (/home/marek/Dokumenty/django-autocomplete-
      light/lib/python3.6/site-packages/django_autocomplete_light-3.2.4-py3.6.egg)

even after I did run git submodule update --init inside /home/marek/Dokumenty/django-autocomplete-
      light/lib/python3.6/site-packages/django_autocomplete_light-3.2.4-py3.6.egg

**Comment by jpic** [comment]
Oh, I think this is because you didn't install with `--editable`. So your env contains a copy from when you installed the package. When installing with `pip install --editable /path/to/git/repo` then it uses a symlink and changes in the repo also apply in the env.

Or did you install with --editable ?

**Comment by marekjedrzejewski** [comment]
Well, I did the following:

1. cloned the repo
2. cd'd inside it
3. virtualenv ./
4. source bin/activate
5. cd test_project
6. pip install -r requirements.txt

and then the git submodule update thing. And I'm not super familiar with virtualenvs so I may have done it wrong. Can you post steps required to get it to work for noob?

**Comment by jpic** [comment]
Yep, so `git clone --recursive` clones the repo + submodules.

Otherwise, `git submodule update --init` would do the trick.

Before `pip install -r requirements.txt`, try `pip install -e /path/to/dal` (make sure dal isn't already installed in its static package form before).

If in doubt, these instructions should work: http://django-autocomplete-light.readthedocs.io/en/master/install.html#install-the-demo-project

**Comment by marekjedrzejewski** [comment]
Thanks, managed to do it :)

Created pull request for it:
https://github.com/yourlabs/django-autocomplete-light/pull/839
but didn't have idea for meaningful test, so it only outputs the value to console just to be able to check if it works.

**Comment by jpic** [comment]
Nice one !
