### ISSUE TITLE
Autocomplete for GM2Mfield : FieldError, cannot resolve keyword 

### ISSUE THREAD

**Issue by kamal-el** [yourlabs/django-autocomplete-light#842]
i use django-autocomplete-light with django-gm2m :
for applying the filter on all the querysets :

qs = qs.filter(EMP-FIRST-NAME__icontains=self.q).

my models don't have a same name of  its fields:

   ** EMP-FIRST-NAME (field) for models Employees.

  ** FIRST-NAME (field) for models Freecontracts.

 ** AG_NAME (field) for models Freeagencies.

 ** FRE_FIRST_NAME (field) for models Freelancers

how can i do for applying filter for all models (qs)??

** Views.py ** :

class RessourceAutocompleteView(Select2QuerySetSequenceView):

     def get_queryset(self):

             employees = Employees.objects.all()
             freecontracts = Frecontract.objects.filter(IS_ACTIVE=True)
             freeagencies = Freagencies.objects.filter(IS_ACTIVE=True)
             freelancers = Freelancers.objects.filter(IS_ACTIVE=True)

       if self.q:
             employees =   Employees.objects.filter(EMP_FIRST_NAME__icontains=self.q)
             freecontracts =    Frecontract.objects.filter(FIRST_NAME__icontains=self.q)
             freeagencies = Freagencies.objects.filter(AG_NAME__icontains=self.q)
             freelancers = Freelancers.objects.filter(FRE_FIRST_NAME__icontains=self.q)

        qs = QuerySetSequence(employees, freecontracts, freeagencies, freelancers)

        if self.q:
             # This would apply the filter on all the querysets
             # this tuple how can i do for apllying filter in all models qs??!!!
             qs = qs.filter(EMP_FIRST_NAME__icontains=self.q)

Thank you for your help.

**Comment by jpic** [comment]
If you apply the filter here

```
   if self.q:
         employees =   Employees.objects.filter(EMP_FIRST_NAME__icontains=self.q)
         freecontracts =    Frecontract.objects.filter(FIRST_NAME__icontains=self.q)
         freeagencies = Freagencies.objects.filter(AG_NAME__icontains=self.q)
         freelancers = Freelancers.objects.filter(FRE_FIRST_NAME__icontains=self.q)
```

Why try to re-apply it there ?

```

    if self.q:
         # This would apply the filter on all the querysets
         # this tuple how can i do for apllying filter in all models qs??!!!
         qs = qs.filter(EMP_FIRST_NAME__icontains=self.q)
```

I think this is not needed and could potentially break the qss.

**Comment by kamal-el** [comment]
Yes  you're right,  that line broke the qss, thank you very much for your help.
