### ISSUE TITLE
Autocompletion for django-gm2m's GM2MField : Error When Adding New Element: Select a valid choice. 11-14 (a primary key) is not one of the available choices

### ISSUE THREAD

**Issue by kamal-el** [yourlabs/django-autocomplete-light#848]
First of all I apologize I am beginner to speak english.
I am able to use autocomplete on the existing items, and am able create new items before saving form. However, after adding the new items, I keep getting the error saying that its primary key is not one of the available choices. 
The same problem when updating. 
Can someone please help me figure out what's wrong with this setup ?:

**Form.py**

` class QAMForm(autocomplete.FutureModelForm): `
        
        `def __init__(self, *args, **kwargs):`
  
              TRANSLATOR = autocomplete.GM2MQuerySetSequenceField(queryset=autocomplete.QuerySetSequence(
                     Employees.objects.filter(IS_ACTIVE=True, TYPE_RESOURCE__TYPE='TLR'),
                     Frecontract.objects.filter(IS_ACTIVE=True),
                     Freagencies.objects.filter(IS_ACTIVE=True),
                     Freelancers.objects.filter(IS_ACTIVE=True),
                    ), required=False,label=_("Traducteur(s)"), widget=autocomplete.QuerySetSequenceSelect2Multiple('qm:ressource-autocomplete')
    )

               PROOFREADER = autocomplete.GM2MQuerySetSequenceField(queryset=autocomplete.QuerySetSequence(
                     Employees.objects.filter(IS_ACTIVE=True),
                     Frecontract.objects.filter(IS_ACTIVE=True),
                     Freagencies.objects.filter(IS_ACTIVE=True),
                     Freelancers.objects.filter(IS_ACTIVE=True),
                     ),
                    required=False, label=_("Relecteur(s)"), widget=autocomplete.QuerySetSequenceSelect2Multiple(
            'qm:ressource-autocomplete'),
    )
                PM = forms.ModelMultipleChoiceField(queryset=Employees.objects.filter(TYPE_RESOURCE__TYPE__in=('PMJ', 'PMS')), required=False, label=_("PM(s)"),)

                class Meta:
                        model = Feedback
                        fields = ['PM']

**View.py**:

` def checked_pm(request):`
       ......
      `if form.is_valid():`
      `cd = form.cleaned_data['Criteria']`
      `saved_form = form.save(commit=False)`
       `saved_form.PM = [pm.pk]`
      `emps = Employees.objects.filter(pk__in=(12, 13, 14))`
      `saved_form.TRANSLATOR = emps # These are a new items` 
      `form.save_m2m()`
      `saved_form.save()`
      `return JsonResponse({"error": 0, "id": saved_form.pk})`
              

![capture-2](https://cloud.githubusercontent.com/assets/23530540/25990013/1619687a-36f6-11e7-9e77-9fd414268c66.png)

Thanks in advance.

**Comment by kamal-el** [comment]
Can anybody help me, please?

**Comment by jpic** [comment]
Why are you instantiating three fields in `__init__` into 3 variables that don't seem used anywhere ?

**Comment by kamal-el** [comment]
Yes you are right, the initialized objects must have the criteria of the variables declared in the function __init__. 
Thank you very much.
