### ISSUE TITLE
Disable creation of new tags

### ISSUE THREAD

**Issue by mekanix** [yourlabs/django-autocomplete-light#853]
Is it possible to make autocomplete not create new tags? I want user(s) to be able to add tags only from a list of tags (used to autocomplete, too). Is it possible? A bit less important, is it possible with 2.3.3? Thank you!

**Comment by gagarski** [comment]
Perhaps tag feature is not what you need. Won't (Model)MultipleChoiceField + (Model)Select2Multiple widget do the job?

**Comment by mekanix** [comment]
At the end we went with a solution of adding what we need through JS as this feature was not the only one requested. Thank you!
