### ISSUE TITLE
Support insertion of choices for models (instead of remoate data source)

### ISSUE THREAD

**Issue by osamak** [yourlabs/django-autocomplete-light#865]
There are cases were the queryset in question is not extensive or frequently changed to warrant a remote data source (think a limited list of suppliers).  In these cases, it would be more practical to support inserting the results of the queryset as `option` tags or (probably less easy) as an array data source within the JavaScript source code.

**Comment by osamak** [comment]
That report is so wrong and absurd.  Just realized that omitting the `url` parameter does exactly that.  Thanks for the awesome work!

**Comment by jpic** [comment]
:D :D :D :guitar: :trumpet:
