### ISSUE TITLE
First time dynamically inserted widget not initializing

### ISSUE THREAD

**Issue by Paul424** [yourlabs/django-autocomplete-light#867]
I have a container view that only renders a container element with a data-url. Then an ajax call loads a form which is then inserted into the dom tree. The form contains select elements that i like to auto-complete using select2.

What i've done is to use the ModelSelect2 widget on the specific field + i've set include_media to True of the crispy form (using crispy forms...), reason being that it's much easier for the widget static files to ship with the form then to push them separately to the frontend for insertion (in the footer for instance).

I can see the static files are all loading so that's ok, but the control is not working....

I guess the reason is that the form is inserted first, then the js files get loaded/initialized so the autocomplete-init.js is not yet listening to "DOMNodeInserted" and the first time loading such form it will fail. The second time however it does work...

widgets = {
            u'country': ModelSelect2(url='autocomplete-country'),
        }

My fix is to make the init call explicitly from the ajax done handler, since i know some if these were loaded and need to be initialized at that point:

$("select[data-autocomplete-light-function]").trigger('autocompleteLightInitialize');

Hope this helps so anyone facing the same issues...

Paul

**Comment by jpic** [comment]
Thanks, that makes sense, but I thought auto initialization would be triggered on document ready so it wouldn't matter if the script was loaded before or after the form HTML ?

**Comment by Paul424** [comment]
You are correct however the init-script being loaded is not listening yet to the dom-inserted event, so i guess you'll always be too late. Reason that it works the second time is that the "old" script is still there and listening...

**Comment by jpic** [comment]
Right, what version are you on ? I wonder if #820 fixes this, it's in 3.2.9, but I think not ^^
Otherwise, I think it would work to contribute that extra call to initialize, looking at the code it seems safe (initialize() is supposed to prevent double initialization but might be subject race conditions / not thread safe).
@apinsard do you have an opinion on this ?

**Comment by Paul424** [comment]
I upgraded to 3.2.9 while working on this (simple check to see if that fixes it), but unfortunately ...it did not.

**Comment by apinsard** [comment]
Indeed, I think #820 should fix it. However, I made a mistake in #820 (shame) that I corrected in #864.

**Comment by jpic** [comment]
Awesome, thanks for answering, @Paul424 could you confirm this works for you ?

**Comment by jpic** [comment]
@Paul424 I have merged #864 which had evolved a bit since last time, can you take a look please ? Thanks !

**Comment by DSynergy** [comment]
I was having the same issue...it appears the newest version has fixed the problem. Thanks
