### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Q-bart** [yourlabs/django-autocomplete-light#871]
Why there is no any locale at the project? I could help to translate it into several languages.

**Comment by jpic** [comment]
Translate what?

**Comment by Q-bart** [comment]
All the strings marked for translation, for example, https://github.com/yourlabs/django-autocomplete-light/blob/master/src/dal_select2/views.py#L39

Clients complain about such strings.

**Comment by jpic** [comment]
Agreed, looking forward to review a pull request !

**Comment by Q-bart** [comment]
Pull request was sent.

**Comment by jpic** [comment]
:guitar:

**Comment by Q-bart** [comment]
One more thing: does select2 internationalization (https://github.com/select2/select2#internationalization-i18n) is used here in django-autocomplete-light? I asked this because those strings, like "Please enter [3] or more characters", are not translated.

**Comment by luzfcb** [comment]
@Q-bart the standard (no standard) used by select2 in translation filenames is the problem, see #746

**Comment by jpic** [comment]
@Q-bart yep @luzfcb has done most of the work I think you can rebase PR #746 and finish it easy <3

**Comment by jpic** [comment]
Please add the pt_BR case since this PR was started by our friend from Brazil haha
