### ISSUE TITLE
Creating an object using create_field doesn't obey overriden get_result_label

### ISSUE THREAD

**Issue by cgada** [yourlabs/django-autocomplete-light#879]
I don't think this is intended behaviour, though I'd like confirmation.

[This line](https://github.com/yourlabs/django-autocomplete-light/blob/master/src/dal/views.py#L119) calls six.text_type on the newly created object, returning text for this newly created object that might be inconsistent if a user has overriden get_result_label().

**Comment by jpic** [comment]
Agreed, looking forward to review a PR !

**Comment by timdiels** [comment]
Actually, I believe it should use `get_selected_result_label` ([downstream issue](https://gitlab.psb.ugent.be/beg-orcae/orcae/issues/733)). For example, I show `name - description` in the list with `get_result_label` and `name` in the badges with `get_selected_result_label`. The text returned in the created option is used for a badge, so I end up with a badge `name - description`.
