### ISSUE TITLE
Using forward option to reference an inline field does not work if the dal field is outside the inline

### ISSUE THREAD

**Issue by FacundoMainere** [yourlabs/django-autocomplete-light#890]
When using this with TabularInline i can't forward reference fields inside the TabularInline from fields that have the autocomplete outside of the inline.
The problem is that the fix for #713 , is assuming that you are doing this from the same inline and then calculating the prefix. 
I think a better solution for this would be a prefix option in the instantiation of ModelSelect2 or a more powerful forward option that lets you use wildcards (eg. forward=['statepriority_set-*-state']).
I can provide a PR for this it's a desired feature.

```
class CampaignForm(forms.ModelForm):

    class Meta:
        model    = Campaign
        fields   = ('__all__')
        forwards = ['statepriority_set-'+str(i)+'-state' for i in range(30)]
        widgets  = {
        'initial_state': autocomplete.ModelSelect2(url='initial-state-autocomplete', forward=forwards)
        }
```

For the time being i hardcoded it this way, i know it doesn't fix the problem if my campaign has more than 30 states, but is good enough until we add this feature here or i add it in a fork

**Comment by jpic** [comment]
Ouch, I had never thought of this, indeed, we should be able to specify the form prefix, if any, for a forward field.
For this, it looks like the wildcard works.
As always, we will need test & documentation update to merge.
Keep up the great work !
<3

**Comment by jpic** [comment]
> For this, it looks like the wildcard works. 

**BUT** it's been suggested in #894 that we use wildcards to select several fields.

I think [@leo-orellana implementation](https://github.com/Cambalab/django-autocomplete-light/commit/0fc030750c21082509adc8995df44c10b749607e) is cleaner, I'd just like to change use_suffix by something more explicit about what is going on, ie. `keep_prefix=True` would be the default and would ensure it searches in the same Django Form the field is in.

Makes sense to you ?

**Comment by FacundoMainere** [comment]
Hi @jpic thanks for your response, yes, we have been working alongside @leo-orellana to bring a solution to this, the biggest problem with wildcards is that jquery selectors doesnt support any form of it. But i believe there should be a way. I agree that your solution seems more explicit, we will get back to you with a corrected implementation, tests and docs.

**Comment by FacundoMainere** [comment]
Hey, i made a little JQuery extension to select elements using wildcards, what do you think of implementing the solution using it?

https://github.com/Cambalab/jquery-wildcard-selector

If you agree we will provide a PR

**Comment by jpic** [comment]
I'd say yes to reuse libraries rather to implementing our own. Can you explain what's the advantage of using the wildcard selector instead of jquery regexp selector ?

**Comment by FacundoMainere** [comment]
Does JQuery have a native regexp selector? i don't know of it.
Do you refer to this one: https://j11y.io/javascript/regex-selector-for-jquery/ ?
If you are referring to that one, i guess we can do it with it, i based my implementation on his, i think the advantage of my implementation is the simplicity of the expression. The regex selector is more powerful of course.
We can use whichever you want.

**Comment by jpic** [comment]
All right, i'm all in favor of your implementation, we can afford git submodules like we already do with select2, however, it should also work with #894 and #895.
Would you like to continue discussion on #895 ?

**Comment by FacundoMainere** [comment]
Ok, we will implement it on top of #895

**Comment by jpic** [comment]
I would be delighted if you can make this work @FacundoMainere, after all, we're doing open source to avoid effort duplication ;)
The code is probably functional and used in prod by Kirill but we need a little selenium test to ensure there won't be regression after merging.
