### ISSUE TITLE
How to get Model data

### ISSUE THREAD

**Issue by davideghz** [yourlabs/django-autocomplete-light#893]
Hi, so far I've been using jQuery to get Model `id` from `event.params.data.id`

Something like:

```
$('select').on('select2:select', function (event) {
  console.log(event.params.data.slug);
  ...
}
```
I used id to build a `url` and then redirect the user to it using JS (ofter click on a button).

Now I moved my Model and urls.py to use field `slug`. How can I add it to the same `event` object?

This is how I build my form:
```
class HomeForm(forms.Form):
    dj_name = forms.ModelChoiceField(
        queryset=DjProfile.objects.all(),
        widget=autocomplete.ModelSelect2(
            url='dj-autocomplete',
            attrs={
                # Set some placeholder
                'data-placeholder': 'Trova Dj',
                # Only trigger autocompletion after 3 characters have been typed
                'data-minimum-input-length': 3,
            },
        )
    )
```

and this is what `dj-autocomplete` points to:
```
class DjProfileAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = DjProfile.objects.all()
        return qs.filter(name__icontains=self.q) if self.q else qs
```

**Comment by davideghz** [comment]
For now I solved overriding the `get_result_value` method in order to returns my Model's `slug`.

```
class DjProfileAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = DjProfile.objects.all()
        return qs.filter(name__icontains=self.q) if self.q else qs

    def get_result_value(self, result):
        return result.slug
```

this is definitely not the correct approach but put me one step ahead vs where I was few hours ago ... any other suggestion will be greatly appreciated!

**Comment by jpic** [comment]
Perhaps you could try to return a json list of dicts with a `slug` in addition to `id` and `text` in an override of [`get_results`](https://github.com/yourlabs/django-autocomplete-light/blob/master/src/dal_select2/views.py#L18).

Then, figure a way with select2 ;)
