### ISSUE TITLE
Django 1.10 and DAL v3 Select2 not loading Jquery properly?

### ISSUE THREAD

**Issue by bbiney1** [yourlabs/django-autocomplete-light#900]
Directly referencing a similar, if not, the exact same issue as provided in the following link, it's just that neither the solution in this issue (nor in anything else I've found) has worked. https://github.com/yourlabs/django-autocomplete-light/issues/858

I've been trying to configure autocomplete on the admin change form for a model called `KeywordInContext`, and I've kinda hit this as a stopping point. I have followed steps on the [DAL tutorial ](http://django-autocomplete-light.readthedocs.io/en/master/tutorial.html), all the way to the point where I can am trying to use the autocomplete view as a widget in my form.

But now when I load the page for the model, I see can only see a select box with a null option (or a prepopulated option, if you click an existing KeywordInContext object). I also see in console the following.

<img width="341" alt="autocompletedebug" src="https://user-images.githubusercontent.com/22688868/29288084-80b71a16-8105-11e7-9533-77b80955d3b1.png">

The most important message in my console being

> Select2: An instance of jQuery or a jQuery-compatible library was not found. Make sure that you are including jQuery before Select2 on your web page.

CTRL + SHIFT + R doesn't do anything (nor does changing my browser or... any of those things have an effect) , implying this isn't a browser problem. 

What exactly is this error? Is there any overriding I could do to possibly fix it (or at least, force an instance of the jquery library)?

Also if any further info is needed, I can provide.

**Comment by jpic** [comment]
Yeah, I think it will work better if you load jQuery before DAL.

**Comment by xrmx** [comment]
@bbiney1  This should be already handled in master by 22d68c835f10e5d4fdc96447046e059eaac3131e
@jpic any plan for a new release please?

**Comment by jpic** [comment]
Version 3.2.10 released, thanks for the heads up.
Let us know if you still run into any issue after the upgrade.

**Comment by victorpluna** [comment]
I have the same issue. It was fixed?
Django: 1.10.5
Autocomplete-light: 3.2.10

**Comment by jpic** [comment]
@victorpluna what happens when you make it load jquery before select2 ?

**Comment by tik9** [comment]
How do you load jquery before select2? I use Django 1.11 with admin and DAL 3.2.10

**Comment by aijogja** [comment]
I also has the same problem. 
With Safari browser, it does not load DAL. But when I use Chrome or Firefox, it works well. 

<img width="811" alt="screen shot 2018-02-16 at 08 07 04" src="https://user-images.githubusercontent.com/1049429/36289092-a19e073a-12f0-11e8-8455-d637595e06d7.png">

As you see, jquery loaded before select2, but it still error in Sarafi.

**Comment by tnedev** [comment]
I've got the same issue when trying to use it in the admin.

**Comment by tnedev** [comment]
Actually fallowing #858 and opening incognito window did the trick.
