### ISSUE TITLE
No TextInput-like form< no information render.

### ISSUE THREAD

**Issue by Masaaq** [yourlabs/django-autocomplete-light#903]
I used [this](http://django-autocomplete-light.readthedocs.io/en/master/tutorial.html) guide to make autocomplete forms on my page.

My forms.py
```class PlanForm(forms.ModelForm):
    driver=forms.ModelChoiceField(
        queryset=Driver.objects.all(),
        widget=autocomplete.ModelSelect2(url='dautoc')
    )
    class Meta:
        model = Plan
        fields = ('driver', )
        widgets = {
        }
```

urlpatterns

```
urlpatterns = [
    url(r'^dautoc/$', DriverAutocomplete.as_view(), name="dautoc"),
]
```

views.py
```class DriverAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        if not self.request.user.is_authenticated():
            return Driver.objects.none()

        qs = Driver.objects.all()

        if self.q:
            qs = qs.filter(name__istartswith=self.q)
        return qs
```

And it's supposed to work fine, because it's almost identical, but instead I don't receive any results from my model's db and more of that it's Select-like instead of TextInput.

Any help or info is appreciated.

**Comment by jpic** [comment]
It seems like your python is ok because the select is meant to be empty because it's going to fetch results.
Are you sure that javascript is loading correctly ?
Does it work with runserver with DEBUG=True ?
If you're on a git checkout, have you initialized submodules ?

**Comment by Masaaq** [comment]
Thank you for your response!

Python gives me only this error 

`UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'personnel.models.Driver'> QuerySet.
  allow_empty_first_page=allow_empty_first_page, **kwargs)`

and nothing more.
JavaScript. The web browser console remains silent and doesn't respond with any errors.

Debug is set to True, and still shows nothing.

I'm not on the git checkout

**Comment by jpic** [comment]
The python warning is because you forgot to add default ordering in the Model I suppose.

If you have no js error, no select2, perhaps the js is not loaded at all ?
Have you tried rendering {{ forms.media }} after loading jquery.js like in the documentation ?

**Comment by Masaaq** [comment]
Thank you for helping me out!

It was {{form.media}} indeed. The thing is I'm more into {{blocks}} and snippets and I have absolutely missed the {{ form.media }}.

Thank you once again!

**Comment by jpic** [comment]
No problem have fun !
