### ISSUE TITLE
How to write template using formset?

### ISSUE THREAD

**Issue by apnewberry** [yourlabs/django-autocomplete-light#906]
I'm very excited to use this project; it looks really cool! 

I have set up a `class PersonForm(forms.ModelForm)` that uses

```{html}
full_name = forms.ModelChoiceField(
            queryset=Person.objects.all(),
            widget=autocomplete.ModelSelect2(url='name-autocomplete'),
)
```

I don't quite understand how to use a formset here. I'm passing in a formset in the `render` call as `formset`. The page has a table where each row represents an object, each column represents a field. 
Thanks!

```
{% load static %}
<html>

<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
<body>

<div class="top">

  <div class="div-img sub">
    <img id="clip"  src="{% get_static_prefix %}{{image_path}}"/>
  </div>


  <div class="div-table sub">
    <form action="{% url 'collector:submit' list_id %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ formset.management_form }}

      <table id="id_data_table">
        {% for form in formset %}
              {{ form.media }}
        {% if forloop.first %}
          <thead><tr>
            {% for field in form.visible_fields %}
              <th>{{ field.label|capfirst }}</th>
            {% endfor %}
          </tr></thead>
        {% endif %}
        <tr>
          {%for field in form.visible_fields %}
            <td>
              {{field}}
            </td>
          {%endfor%}

        </tr>

      {% endfor %}

    </table>

    <p/>
    <div class="div-submit">
          <input type="submit"/>
    </div>

  </form>

</div>
</div>
</body>

<script>
  function copyTextValue(bf) {
    var text = document.getElementsByClassName("call-number")[0].value ;
    elements = document.getElementsByClassName("call-number");
    for (var i = 0; i < elements.length; i++){
      elements[i].value = text
    }
  }
</script>

</html>

```
in `views.py`:
```
class NameAutocompleteFromList(autocomplete.Select2ListView):

    def get_list(self):
        print('running get list')
        return ['Jane', 'John']
```
in urls.py:
```
    url(
        r'^name-list-autocomplete',
        NameAutocompleteFromList.as_view(), name='name-list-autocomplete'
    )
```

In forms.py:
```
class PersonForm(forms.ModelForm):

   def __init__(self, *args, **kwargs):
        super(PersonForm, self).__init(args, kwargs)
        self.fields['full_name'] = autocomplete.Select2ListChoiceField(
            choice_list=lambda: ['Bill', 'Jane', 'Lucy'],
            widget=autocomplete.ListSelect2(
                url=reverse('collector:name-list-autocomplete'),
                attrs={'data-placeholder': 'Autocomplete...'},
            )
        )
```

**Comment by jpic** [comment]
You need to load form.media after loading jQuery, just follow the docs and check the examples and you should be fine. Please let us know when you have a more specific question.

**Comment by apnewberry** [comment]
Using the above code, the autocomplete form appears and offers 'Jane' and 'John' (not Bill, Jane, and Lucy). But it is _extremely_ intensive, nearly freezing my computer when I run it with `./manage.py runserver`. Perhaps diagnostically, Chrome never stops "Waiting for localhost". But I don't see any 

The reason I'm using `__init__` for that form is that each page should have a different set of autocomplete suggestions. For example, using this instead works well:

```
self.fields['full_name'] = forms.ChoiceField(
                choices=kwargs['choices'],
            )
```

Thanks for your help!

**Comment by jpic** [comment]
Is there any reason why you feed a different choice list to the widget and the view ? It's expected that you make it the same, one for initial page rendering, the other for ajax queries.
Does firefox also crash or is this specific to chrome ?
What OS are you on ?
Do you have any traceback ?
Does your computer also freeze when you remove the choice_field argument from the widget ?

**Comment by apnewberry** [comment]
Trying two different choice lists was just for testing. Deleting or replacing the list in the Form with the other list doesn't change anything. 

[Here's a screenshot](https://i.imgur.com/2oHn7CN.png) of the formset. Each row is a form; each column is a field.

It slows to a halt around the 8th form (out of 12 on this page), and the final 4 autocomplete fields never fill.

In firefox, after a while, a notification appears that jquery is stuck, but then the browser becomes unresponsive. There is no notable event in the django server log.

**Comment by jpic** [comment]
Are you able to reproduce this in a new test app in the test_project of this repository ?
Can you post the view code ?
How many empty forms are created by the python formset ?
Are there any forms added to the formset with script code ?
If so, what is the script code ?
What's the DOM like for the autocomplete in a form that's working and for a form that's not working ?
