### ISSUE TITLE
DAL static not loading in template

### ISSUE THREAD

**Issue by davideghz** [yourlabs/django-autocomplete-light#907]
Hi everybody - my question is a bit general, but I can provide you with the relevant bits if necessary ..

I'm able to load a DAL form in my home-page, which is extending `base.html`. The same DAL form does not work in another template which is extending the same `base.html`. I mean, the DAL JS files are not loaded in the other template..

What might be the problem?

This is what is not loaded in the other template:

```
<link href="/static/autocomplete_light/vendor/select2/dist/css/select2.css" type="text/css" media="all" rel="stylesheet" />
<link href="/static/autocomplete_light/select2.css" type="text/css" media="all" rel="stylesheet" />
<script type="text/javascript" src="/static/autocomplete_light/jquery.init.js"></script>
<script type="text/javascript" src="/static/autocomplete_light/autocomplete.init.js"></script>
<script type="text/javascript" src="/static/autocomplete_light/vendor/select2/dist/js/select2.full.js"></script>
<script type="text/javascript" src="/static/autocomplete_light/select2.js"></script>
```

**Comment by davideghz** [comment]
I was passing the form into the context with the varibale named `event_track_form` ..I just renamed it to `form` and now it works.. is it somehow related to DAL internals?

**Comment by jpic** [comment]
Probably related to having `{{ form.media }}` in the template, perhaps you could try with `{{ event_track_form.media }}` ?
