### ISSUE TITLE
Allow every registered user to create objects 

### ISSUE THREAD

**Issue by davideghz** [yourlabs/django-autocomplete-light#918]
`Note that creating objects is only allowed to staff users with add permission by default.`

It would be great to pass an option from `urls.py` like
```
views.MyModelAutocomplete.as_view(create_field='name', public=True)
```
to skip the permission check here: http://django-autocomplete-light.readthedocs.io/en/master/_modules/dal/views.html#BaseQuerySetView.post

I would love to contribute with a PR but I still don't feel that confortable with Python/Django :)

In the meantime, is there any way to make this option available for all the subscribed users? Thanks!

**Comment by jpic** [comment]
What happens after you grant the create permission for that model to your registered user ? It seems like that's what [has_add_permission](http://django-autocomplete-light.readthedocs.io/en/master/_modules/dal/views.html#BaseQuerySetView.has_add_permission) is doing.
Perhaps we we have misleading documentation somewhere ?

**Comment by davideghz** [comment]
Yeah it actually works and I believe it's a way safer way to handle the point. I was approaching the problem from the other side.

The misleading part in the docs is the reference to `only allowed to staff users`. I was induced to think that only `staff users` could create objects, but I can actually grant `add` permission to a user even if it's no staff.

I would change it to `Note that creating objects is only allowed to staff users with add permission by default. If you want to grant add permission to other users you have to explicitly set it.` and then add a noob-proof-example, like:
```
permission = Permission.objects.get(name='Can add model-name')
user.user_permissions.add(permission)
```

**Comment by jpic** [comment]
Can you confirm that it works with any authenticated user which has create permission and that is_staff is not required anymore ?
Then we should update the documentation yes

**Comment by davideghz** [comment]
Yes, I do confirm that `is_staff` is no longer required. I can contribute to the docs if you explain me how :)

**Comment by jpic** [comment]
Sure, just make a pull request with changes in the docs/ subdirectory.

**Comment by davideghz** [comment]
Open source noob here :) what's the correct flow? I cloned the repo but then I'm not allowed to push any new branch to origin..

**Comment by davideghz** [comment]
oh, got it https://github.com/yourlabs/django-autocomplete-light/pull/919
