### ISSUE TITLE
CDN media / django-autocomplete staticfiles

### ISSUE THREAD

**Issue by scoopseven** [yourlabs/django-autocomplete-light#925]
We use s3 (s3Boto) to deliver staticfiles, but it doesn't look like there's a way to configure django-autocomplete to look at s3.mydomain.com/static/ for it's media files, rather than www.mydomain.com/static/.

We just loaded the files on our server as a workaround, just wondering if this is a feature that's needed or an easy setting that I missed. 

Many thanks,

Mark

**Comment by jpic** [comment]
dal relies on django.contrib.staticfiles just like anything and i don't know of anything that would block

what do the script/link tags look like in your html ?

**Comment by jpic** [comment]
Please contribute to media pr: #746
