### ISSUE TITLE
BaseQuerySetView.create_object() and concurrency

### ISSUE THREAD

**Issue by dilyanpalauzov** [yourlabs/django-autocomplete-light#926]
`BaseQuerySetView` contains:
```python
def create_object(self, text):
    """Create an object given a text."""
    return self.get_queryset().create(**{self.create_field: text})
```
which is supposed to be called, when the to-be-created object does not already exist.  However, if another threat has already created this object, `get_queryset().create()` fails.  Please replace the code to:
```python
def create_object(self, text):
    """Create an object, if it does not already exist, given a text."""
    return self.get_queryset().get_or_create(**{self.create_field: text})[0]
```

https://docs.djangoproject.com/en/1.11/ref/models/querysets/#get-or-create says `get_or_create()` is atomic.

**Comment by jpic** [comment]
Really nice !!! care to make a pull request ?

**Comment by dilyanpalauzov** [comment]
This can certainly be incorporated without having a 'pull request'.

**Comment by jpic** [comment]
Maybe yes

**Comment by jpic** [comment]
Commited this.
