### ISSUE TITLE
QuerySetSequence querysets order is not preserved

### ISSUE THREAD

**Issue by todorvelichkov** [yourlabs/django-autocomplete-light#930]
I think I traced the problem to here:

https://github.com/yourlabs/django-autocomplete-light/blob/3.2.10/src/dal_select2_queryset_sequence/views.py#L33

An ordinary dict is being used for grouping the results, and the response after that becomes unordered.

**Comment by jpic** [comment]
Thanks for your report !

Could you please check if this is fixed in master with Melvyn's contribution ?

**Comment by todorvelichkov** [comment]
@jpic, yes I believe this will fix it because it the same thing I did in my project.

**Comment by jpic** [comment]
Awesome, reopen if needed !

<3
