### ISSUE TITLE
Disable autocomplete-light

### ISSUE THREAD

**Issue by gogija** [yourlabs/django-autocomplete-light#931]
Hello!
Is there approach for disabling element?
For example: i need to disable auto-complete field before something event.
How i can do it?
Help me please, i broke my brain.

**Comment by jpic** [comment]
Did you try this ? 
https://stackoverflow.com/questions/17680946/select2-will-not-disable-or-clear

**Comment by melvyn-sopacua** [comment]
Closing for now. If this didn't resolve your issue, feel free to re-open.
