### ISSUE TITLE
Autocomplete Scroll to the top at open for the first time

### ISSUE THREAD

**Issue by jdevmx** [yourlabs/django-autocomplete-light#934]
I'm using autocomplete light with django, but when open the select for the first time, the page scroll to the top, I read something about select2, but without sucess,

Please heeeeelp

**Comment by jpic** [comment]
i think there's an issue open for this upstream in select2

**Comment by melvyn-sopacua** [comment]
The issue is [here](https://github.com/select2/select2/issues/5022)

**Comment by jpic** [comment]
They are waiting for a pull request: https://github.com/select2/select2/issues/5022#issuecomment-352921587
