### ISSUE TITLE
How to copy one field value to another

### ISSUE THREAD

**Issue by livingsilver94** [yourlabs/django-autocomplete-light#935]
How can I copy hidden and displayed values from one field to another in JavaScript?

**Comment by jpic** [comment]
With jquery perhaps ?

**Comment by livingsilver94** [comment]
How? with `val()` I can copy the "real", hidden value, but I can't figure out how to copy the displayed one.

**Comment by jpic** [comment]
Have you tried something like $('#yourselect option:selected').html() ? or with [selected=selected] or even '[value="' + $yourselect + '"] ?

**Comment by livingsilver94** [comment]
`$('#yourselect option:selected').html()` is working fine, thanks 👍
