### ISSUE TITLE
$(...).select2 is not a function

### ISSUE THREAD

**Issue by luca120289** [yourlabs/django-autocomplete-light#936]
Hi everybody,
I'm having trouble with django-autocomplete-light.

I'm using the last version on django 1.11.7 with django-jet 1.0.6.

When I try to use django-autocomplete-light in the admin interface, in change_list template, I've got this error in console:

`$(...).select2 is not a function`

For showing the autocomplete I've created a custom form like this:

`class EmailsAdminForm(ModelForm):
    class Meta:
        model = Emails
        fields = '__all__'
        widgets = {
            'user': autocomplete.ModelSelect2Multiple(url='customer-autocomplete'),
            'date': autocomplete.ModelSelect2Multiple(url='date-autocomplete'),
        }`

It seems a problem of jquery.
Someone know how to fix this?

Thanks in advance.

**Comment by jpic** [comment]
Is there anything in the browser error console ?

**Comment by luca120289** [comment]
This is the complete code showed in console:

`Uncaught TypeError: $(...).select2 is not a function
    at HTMLSelectElement.<anonymous> (select2.js:102)
    at HTMLDocument.dispatch (jquery.js:4737)
    at HTMLDocument.elemData.handle (jquery.js:4549)
    at Object.trigger (jquery.js:7819)
    at HTMLSelectElement.<anonymous> (jquery.js:7903)
    at Function.each (jquery.js:365)
    at jQuery.fn.init.each (jquery.js:137)
    at jQuery.fn.init.trigger (jquery.js:7902)
    at HTMLSelectElement.initialize (autocomplete.init.js:47)
    at Function.each (jquery.js:365)`

**Comment by jpic** [comment]
What happens if you load the widget's media after jquery ?

http://django-autocomplete-light.readthedocs.io/en/master/tutorial.html#using-autocompletes-outside-the-admin

**Comment by luca120289** [comment]
But I'm using it inside the admin, not outside.
This tutorial is for using it outside.

**Comment by jpic** [comment]
You're using it in django-jet, not django.contrib.admin.

For $.select2 to be loaded, we need the form.media to render correctly.

Could you paste the page html ?

**Comment by luca120289** [comment]
Ok, this is the template used by django-jet:

`{% extends "admin/base_site.html" %}
{% load i18n admin_urls static admin_modify %}

{% block extrahead %}{{ block.super }}
<script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
{{ media }}
{% endblock %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />{% endblock %}

{% block coltype %}colM{% endblock %}

{% block bodyclass %}{{ block.super }} app-{{ opts.app_label }} model-{{ opts.model_name }} change-form{% endblock %}

{% if not is_popup %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; <a href="{% url 'admin:app_list' app_label=opts.app_label %}">{{ opts.app_config.verbose_name }}</a>
&rsaquo; {% if has_change_permission %}<a href="{% url opts|admin_urlname:'changelist' %}">{{ opts.verbose_name_plural|capfirst }}</a>{% else %}{{ opts.verbose_name_plural|capfirst }}{% endif %}
&rsaquo; {% if add %}{% blocktrans with name=opts.verbose_name %}Add {{ name }}{% endblocktrans %}{% else %}{{ original|truncatewords:"18" }}{% endif %}
</div>
{% endblock %}
{% endif %}

{% block content %}<div id="content-main">
{% block object-tools %}
{% if change %}{% if not is_popup %}
  <ul class="object-tools">
    {% block object-tools-items %}
    <li>
        {% url opts|admin_urlname:'history' original.pk|admin_urlquote as history_url %}
        <a href="{% add_preserved_filters history_url %}" class="historylink">{% trans "History" %}</a>
    </li>
    {% if has_absolute_url %}<li><a href="{{ absolute_url }}" class="viewsitelink">{% trans "View on site" %}</a></li>{% endif %}
    {% endblock %}
  </ul>
{% endif %}{% endif %}
{% endblock %}
<form {% if has_file_field %}enctype="multipart/form-data" {% endif %}action="{{ form_url }}" method="post" id="{{ opts.model_name }}_form" novalidate>{% csrf_token %}{% block form_top %}{% endblock %}
<div>
{% if is_popup %}<input type="hidden" name="{{ is_popup_var }}" value="1" />{% endif %}
{% if to_field %}<input type="hidden" name="{{ to_field_var }}" value="{{ to_field }}" />{% endif %}
{% if save_on_top %}{% block submit_buttons_top %}{% submit_row %}{% endblock %}{% endif %}
{% if errors %}
    <p class="errornote">
    {% if errors|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
    </p>
    {{ adminform.form.non_field_errors }}
{% endif %}

{% block field_sets %}
{% for fieldset in adminform %}
  {% include "admin/includes/fieldset.html" %}
{% endfor %}
{% endblock %}

{% block after_field_sets %}{% endblock %}

{% block inline_field_sets %}
{% for inline_admin_formset in inline_admin_formsets %}
    {% include inline_admin_formset.opts.template %}
{% endfor %}
{% endblock %}

{% block after_related_objects %}{% endblock %}

{% block submit_buttons_bottom %}{% submit_row %}{% endblock %}

{% block admin_change_form_document_ready %}
    <script type="text/javascript"
            id="django-admin-form-add-constants"
            src="{% static 'admin/js/change_form.js' %}"
            {% if adminform and add %}
                data-model-name="{{ opts.model_name }}"
            {% endif %}>
    </script>
{% endblock %}

{# JavaScript for prepopulated fields #}
{% prepopulated_fields_js %}

</div>
</form></div>
{% endblock %}`

**Comment by jpic** [comment]
I was thinking about the rendered html, btw i don't see form.media in this template, perhaps that's an issue ?

`{{ form.media }}` should be after the script tag for jquery.js and then $.select2 should be defined ;)

**Comment by luca120289** [comment]
You're right!

I don't know if is an issue of django-jet but I extended the template, included the jquery and then the form media and know it works.

Thank you very much!!

If someone else is using django-jet and face the same problem, you need to extend the change_list.html template of your model like this to get django-autocomplete-light works:

`{% extends "admin/change_form.html" %}

{% load static %}

{% block extrahead %}
<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
{{ adminform.form.media }}
{% endblock %}`

**Comment by jpic** [comment]
Nice one !!

Would you like to contribute a short note about django-jet in the tutorial like there is grappeli ?

https://github.com/yourlabs/django-autocomplete-light/blob/master/docs/install.rst

**Comment by luca120289** [comment]
Yes, no problem :)

When I have some free time I'll do it.

**Comment by jpic** [comment]
Lovely <3 <3 <3 <3 <3 <3
