### ISSUE TITLE
ModuleNotFoundError with Django2 due to urlresolvers being removed

### ISSUE THREAD

**Issue by h4k1m0u** [yourlabs/django-autocomplete-light#940]
Hi,

Apparently, `Django 2` was release today, and while I tried to update `Django` to get rid of a bug with Geospatial processing in an existing project, I got an error from  `dal` which is caused by:

> The django.core.urlresolvers module is removed in favor of its new location, django.urls.
[Source](https://docs.djangoproject.com/en/2.0/releases/2.0/#features-removed-in-2-0)

Below is the relevant part of the error I got:

```
  File "/usr/lib/python3.6/site-packages/dal/autocomplete.py", line 26, in <module>
    from .widgets import (
  File "/usr/lib/python3.6/site-packages/dal/widgets.py", line 10, in <module>
    from django.core.urlresolvers import reverse
ModuleNotFoundError: No module named 'django.core.urlresolvers'
```

**Comment by melvyn-sopacua** [comment]
Please update to 3.2.10. This has been fixed a while ago.
