### ISSUE TITLE
add_lazy_relation is deprecated - django 2.0

### ISSUE THREAD

**Issue by SettembreNero** [yourlabs/django-autocomplete-light#942]
Hi, I'm trying to use django-autocomplete-light with django 2.0, but when I try to `./manage.py migrate` I get this error: `ImportError: cannot import name 'add_lazy_relation'`. Guess that's related to the [deprecation](https://docs.djangoproject.com/en/1.11/_modules/django/db/models/fields/related/) of the referenced function.

**Comment by melvyn-sopacua** [comment]
Could you verify if this is in fact in DAL? I suspect it is in [gm2m](https://bitbucket.org/tkhyn/django-gm2m/src/8e63cdeecdac5ac452ac24229d28a8872a69e33b/gm2m/relations.py?at=release&fileviewer=file-view-default#relations.py-2).

**Comment by melvyn-sopacua** [comment]
[PR submitted](https://bitbucket.org/tkhyn/django-gm2m/pull-requests/2/fix-to-not-break-packages-using-gm2m-on/diff)

**Comment by SettembreNero** [comment]
Yes, it is, sorry for posting in the wrong place!

**Comment by melvyn-sopacua** [comment]
No problem. As a result, gm2m is now ready for Django 2.0.
