### ISSUE TITLE
BaseQuerysetView: user.is_authenticated Django 2.0 compatibility

### ISSUE THREAD

**Issue by noahbkim** [yourlabs/django-autocomplete-light#943]
DAL breaks when rendering the API views because of a call to `request.user.is_authenticated()`, which is deprecated as a method in Django 2.0. This can be fixed by removing the actual function call and just using the read-only property. This change will remain backwards compatible as suggested by [this](https://docs.djangoproject.com/en/1.11/ref/contrib/auth/#django.contrib.auth.models.User.is_authenticated).

**Comment by noahbkim** [comment]
Thanks for taking a look at this so quickly!

**Comment by noahbkim** [comment]
Could you guys push this to release as soon as possible? My team made the mistake of migrating to 2.0 prematurely and we're now seeing the consequences...

**Comment by noahbkim** [comment]
Oh crap! It works!

**Comment by jpic** [comment]
What ? We haz releasable branch for 2.0 but no CI service on which selenium tests will pass ...
