### ISSUE TITLE
multiple remove sign display for single record

### ISSUE THREAD

**Issue by piyushgohel** [yourlabs/django-autocomplete-light#946]
Hello, 

this library show multiple remove images for single value. I have set autocomplete_light.ChoiceWidget in django form

Here I attached sample image for more detail

![error](https://user-images.githubusercontent.com/23516944/33701229-eaa878f0-db43-11e7-9059-f7db61166a8e.jpg)

**Comment by melvyn-sopacua** [comment]
Without code of the form and template (at the very least) it's hard to figure out what happens.

**Comment by piyushgohel** [comment]
Thanks for reply. here i mention some of code which is required.

event_form = event_form_class(initial={'klant': klant})

forms.py (in that event_form_class define )
--------------------
       self.fields['klant'].widget = autocomplete_light.ChoiceWidget('KlantAutocomplete')

in template i have used following line:
------------------------------------------------
            {{ event_form.klant }}

**Comment by jpic** [comment]
Hi my friend, I'm sorry but you will need to fix the bug in yourlabs/jquery-autocomplete-light or upgrade to DAL v3
