### ISSUE TITLE
Widget TaggitSelect2 looks like Multiple choice select, not Tag input with autocomplete

### ISSUE THREAD

**Issue by robben1234** [yourlabs/django-autocomplete-light#948]
Here is [screenshot (dropbox)](https://www.dropbox.com/s/fxpw36dggpbb604/Screenshot%202017-12-07%2022.35.22.png). Code is absolutely identical to [docs](http://django-autocomplete-light.readthedocs.io/en/master/taggit.html).

**Comment by jpic** [comment]
Yep, just fixed a but about it in master. Updated select2 and taggit tests pass again.
