### ISSUE TITLE
How to translate the search fields?

### ISSUE THREAD

**Issue by linneudm** [yourlabs/django-autocomplete-light#949]
What do I need to do to translate to my preferred language (pt-BR)?
I'm sorry if this issue has already been resolved. It was not very clear to me.

**Comment by jpic** [comment]
We need help to finish #1142 !

**Comment by linneudm** [comment]
Sorry @jpic , i dont understand. You say #1142?

**Comment by jpic** [comment]
This has been taken care of in #746, did you try with 3.3.0-rc1 ?

**Comment by linneudm** [comment]
That's enough! I was using version 3.2.10. Wow! Thank you!
