### ISSUE TITLE
DAL does not work on production server

### ISSUE THREAD

**Issue by Tur8008** [yourlabs/django-autocomplete-light#950]
Hello,
I have trouble with DAL which installed on Django 2.0. On dev. server it works good, but on production it doesn't work at all.
The problem appears when I use dropdown field in  standart django-admin. 
![2017-12-19_17-44-03](https://user-images.githubusercontent.com/9642686/34162353-787c7dee-e4e4-11e7-9dcd-ce486275b3bc.png)
The select box is empty. But on dev server everything is ОК.  I use gunicorn + nginx. I saw log info and when I noticed that when I drop filed nothing is going on, no one query, at all. I think widget in form does't make query. Why it's going on?

**Comment by Tur8008** [comment]
It's important! I've turned on incognito mode in google chrome and firefox it workes.  Why it's qoing on?

**Comment by jpic** [comment]
What are the XHR request/responses ?

**Comment by Tur8008** [comment]
?

**Comment by Tur8008** [comment]
I think it's possible incorrect implementaions of request if ghrome blocks it.

**Comment by jpic** [comment]
What happens in webkit inspector when you reproduce this ?

**Comment by Tur8008** [comment]
![2017-12-19_18-55-29](https://user-images.githubusercontent.com/9642686/34165805-53bab1ec-e4ee-11e7-811e-0f3f0d11a71b.png)

**Comment by Tur8008** [comment]
![2017-12-19_19-03-38](https://user-images.githubusercontent.com/9642686/34166212-67fc7bda-e4ef-11e7-990e-1bd65addac09.png)
In incognito mode

**Comment by jpic** [comment]
So, why does it not load jquery when you open the page with the browser that throws the error ?

**Comment by Tur8008** [comment]
So why uou ask you?:)

**Comment by Tur8008** [comment]
What are you point Chrome is wrong?

**Comment by jpic** [comment]
Well chrome shows that $ is undefined which means that jquery is not loaded properly.

**Comment by jpic** [comment]
What happens when you load jquery before select2?

**Comment by Tur8008** [comment]
OK, thanks! What's the reason of improperly jquery loading, I don't know while. But, I've opened that page from another computer and it works.
