### ISSUE TITLE
Missing `autocomplete_light/forward.js`

### ISSUE THREAD

**Issue by philgyford** [yourlabs/django-autocomplete-light#957]
I'm using 3.3.0-rc2 and getting this error when I load an admin page that uses autocomplete_light:

> ValueError: Missing staticfiles manifest entry for 'autocomplete_light/forward.js'

A quick search shows the file [is referenced in `src/dal_select2/widgets.py`](https://github.com/yourlabs/django-autocomplete-light/blob/1174c89871ae7ddf7d7b8be904d589d8ad6b61bb/src/dal_select2/widgets.py#L55) but [was removed](https://github.com/yourlabs/django-autocomplete-light/blob/def1fae76b2e83d7f864467450c9d7d5f5e4dafd/CHANGELOG#L82) in version 3.2.7.

**Comment by jpic** [comment]
Thanks for your feedback !

Does it work when you remove that line ?

**Comment by jpic** [comment]
Tests still pass for me after removing that line (should have been removed during rebase, my bad).

Please confirm removing the line fixes the issue for you and I will merge #958 and issue a -rc3 release ;)

**Comment by philgyford** [comment]
Yes, it looks like removing the line fixes the problem on my local copy. Thanks for the speedy response :)

**Comment by jpic** [comment]
Fix released in 3.3.0-rc3

Please keep up the gr8 feedback :guitar:
