### ISSUE TITLE
tutorial.rst: getFormPrefix()

### ISSUE THREAD

**Issue by gagarski** [yourlabs/django-autocomplete-light#962]
As far as I know, there is `getFormPrefixes()` now instead of `getFormPrefix()`. Tutorial should be updated accordigly.

**Comment by jpic** [comment]
Nice, there is the little paragraph to update ;)

https://github.com/yourlabs/django-autocomplete-light/edit/master/docs/tutorial.rst

**Comment by gagarski** [comment]
Seems like I misunderstood the concept of `getFormPrefixes()`. 

`getFormPrefix()` is still there, and using `getFormPrefixes()` instead would be cumbersome.
