### ISSUE TITLE
get_result_label override does not work on initial values

### ISSUE THREAD

**Issue by jlachowski** [yourlabs/django-autocomplete-light#964]
First of all many thanks for this great project!

I have setup a autocomplete view class derived from `Select2QuerySetView` where I extend the `get_result_label` function as follows:

```
    def get_result_label(self, result):
        html = super(MyAutocomplete, self).get_result_label(result)
        rnd = _(u'<strong>(Some additional info)</strong>') if result.is_some_flag else u''
        html = format_html(
            u'{text} {info}',
            text=result.name,
            info=rnd
        )
        return html
```
and it works flawlessly if I use it in a form when creating a new item. However once I use this to edit an existing item the label of the initial selection does not have the `(Some additional info)`. 

Is it possible to force the form/field/widget to re-load this selection from the autocomplete view? I assume that the initial value (label) is provided by the form not the autocomplete view. How can I sync it or reuse the autocomplete view in field initial value setting?

Since the `option` is initially added to the `select` even re-selecting the option from the autocomplete results (where it has the `(Some additional info)`) results in no change of the initial label (`option` text).

**Comment by jpic** [comment]
I think you need to override the widget rendering.

**Comment by gagarski** [comment]
You need to do the following in your form init code:
```
self.fields["your_awesome_field"].label_from_instance = lambda inst: my_awesome_stringify(inst)
```

It is theoretically possible to fetch selected item from autocomplete view when form is loaded but typically autocomplete view does not allow to fetch specific item by id.
