### ISSUE TITLE
django-autocomplete-light is not working with gunicorn

### ISSUE THREAD

**Issue by jmcrowet** [yourlabs/django-autocomplete-light#965]
dal fields of my app are working perfectly when I use "python manage.py runserver" but when I try to run my app with gunicorn the dal fields are empty (as on the picture and as if I didn't put form.media in my template ...). Except for dal field there is no problems.   
Is there something to change in the code for dal to work with gunicorn?

![dal](https://user-images.githubusercontent.com/19777373/35281350-034ca492-0053-11e8-9523-cbeb610fecef.png)

**Comment by melvyn-sopacua** [comment]
Please read up on [Django Deployment](https://docs.djangoproject.com/en/2.0/howto/static-files/deployment/)
