### ISSUE TITLE
No module named 'queryset_sequence'

### ISSUE THREAD

**Issue by Guilouf** [yourlabs/django-autocomplete-light#971]
`django-autocomplete-light-3.2.10`
`django2.0.1`

```
INSTALLED_APPS = [
    ....
    'dal',
    'dal_select2',
    'dal_queryset_sequence',
]
```

When im trying this [tutorial](http://django-autocomplete-light.readthedocs.io/en/master/gfk.html), i can't import anything with `from dal_queryset_sequence`, not only from my own code, but also not working is source code.

EX: (in views):

`from dal_select2_queryset_sequence.views import Select2QuerySetSequenceView`

  ```
File "/home/guigui/Programmation/ZIF/gabarit/views.py", line 21, in <module>
    from dal_select2_queryset_sequence.views import Select2QuerySetSequenceView
  File "/usr/local/lib/python3.6/dist-packages/dal_select2_queryset_sequence/views.py", line 3, in <module>
    from dal_queryset_sequence.views import BaseQuerySetSequenceView
  File "/usr/local/lib/python3.6/dist-packages/dal_queryset_sequence/views.py", line 7, in <module>
    from queryset_sequence import QuerySetSequence
ModuleNotFoundError: No module named 'queryset_sequence'
```

I installed the package via pip, its not clear in the docs, do i need to install a a new django extension, is it [this](https://pypi.python.org/pypi/django-querysetsequence) queryset_sequence ??

**Comment by Guilouf** [comment]
Ok, `queryset_sequence` was, already or as a autocomplete dependency, installed, but had to be upgraded, via `python3.6 -m pip install django-querysetsequence --upgrade`

**Comment by jpic** [comment]
Thanks for reporting!

**Comment by NaturalBornCamper** [comment]
Might I suggest the doc be updated to say we have to install:
`django-querysetsequence==0.13`?
I didn't know that package and I thought it was included in dal when the docs say it should be added in `INSTALLED_APPS`, I struggled quite a bit before finding it in an example's requirements.txt

**Comment by tylerecouture** [comment]
Ran into this too. Docs [here](https://django-autocomplete-light.readthedocs.io/en/master/gfk.html#register-the-view-for-the-form) don't mention that this is a separate package that has to be installed.
