### ISSUE TITLE
Display bug with generic foreign key autocomplete

### ISSUE THREAD

**Issue by Guilouf** [yourlabs/django-autocomplete-light#978]
The input box hide the header of the first object class (should see Agronomical Object): 
![bug_autocomplete](https://user-images.githubusercontent.com/10614714/36247202-68780b30-1233-11e8-92f5-10dcd5ab78ff.png)

Same in firefox and chrome

Btw i don't see the point of the generic foreign key autocomplete, as it seems to have no action on the `content_type` field, and all possibilities are displayed regardless the selection in `content_type`.
I was hopping one form field that fill the `content_type` and `object_id` fields at the same time.

**Comment by jpic** [comment]
It works for me. Perhaps you should ask about your display bug on select2/select2 ?

![2018-02-15-100252_1632x823_scrot](https://user-images.githubusercontent.com/94636/36248338-6e8e712c-1237-11e8-913d-2ec5c749a669.png)
![2018-02-15-100222_621x330_scrot](https://user-images.githubusercontent.com/94636/36248339-6eae10c2-1237-11e8-9c88-ef25d6cc0d96.png)

**Comment by Guilouf** [comment]
My css was somewhat interfering
