### ISSUE TITLE
Unecessary Queryset call in GenericForeignKeyForm demo

### ISSUE THREAD

**Issue by Guilouf** [yourlabs/django-autocomplete-light#979]
Followed this [tutorial](http://django-autocomplete-light.readthedocs.io/en/master/gfk.html), 
in the view, all is set to query the database, as defined in `get_queryset` method.

So why would i have to add this `queryset` keyword for `QuerySetSequenceModelField` ?
It seems to me an unecessary, maybe unoptimised call to the DB.
```python
class TreatmentForm(autocomplete.FutureModelForm):
    object_id = dal_queryset_sequence.fields.QuerySetSequenceModelField(
            # works the same way i commented or not
            #queryset=autocomplete.QuerySetSequence(
                #AgronomicalObject.objects.all(),  
                #Molecule.objects.all(),
            #),
            queryset=None,  # works
            required=False,
            widget=dal_select2_queryset_sequence.widgets.QuerySetSequenceSelect2('autocomp'),
        )

    class Meta:
        model = Treatment
        fields = '__all__'
```

The thing is i have to "mock" the `queryset` argument, maybe it should be really optional ?

**Comment by jpic** [comment]
I don't understand, how is the form field supposed to validate data if it doesn't have the querysetsequence ?

**Comment by Guilouf** [comment]
It's not working with `queryset=None`, but with `autocomplete.QuerySetSequence()`

I haven't understood this was for validation, as the vanilla generic foreign key `object_id` doesn't have validation other than type check.
I was a bit quick on this

Is there anyway to share the `querysetsequence` defined in `Select2QuerySetSequenceView` and the form ? That's not very DRY an that's 2 call to the same queryset ?

**Comment by jpic** [comment]
Well that's the whole issue with autocompletion. PR welcome
