### ISSUE TITLE
3.3.0-rc5 select2.js and autocomplete.init.js bug when included many times

### ISSUE THREAD

**Issue by mpasternak** [yourlabs/django-autocomplete-light#981]
Hi, 

the premise of this bug is: I have no control over what my django.admin includes in the HTML source. I do have a global search form, based on autocomplete, so I need to include dal JavaScript on every single page. And, occasionally, I do have a form with autocomplete. Django admin adds form.media, so I may get dal's JavaScript included many times. 

If I include autocomplete.init.js and/or select2.js more than once, I do get a strange, erroneous behaviour but when? Only when I use that small, very useful ``"Create '%s'"`` option. 

The item created gets submitted more than once. It gets submitted so many times as the times the autocomplete.init.js and select2.js is included. So, usually the first request that hits the server gets OK'd (HTTP status 200), another requests fail with 500 Server Error and I get stack trace about non-unique primary keys in my tables, because the software tries to create the item many times. 

What's good about this is, that I do have a patch! And I'll submit it shortly. 

Thanks for maintenance and development, as usual! Truly yours, with deepest regards, 

-- 
m

**Comment by mpasternak** [comment]
Pull request created, https://github.com/yourlabs/django-autocomplete-light/pull/982 WHERE MY REVIEWERS AT

**Comment by jpic** [comment]
Awesome, great research ;)

**Comment by jpic** [comment]
question about 61890f3f6def did 3.3.0 rcX break something with create_options for you ?
