### ISSUE TITLE
Recipe / helper for integration with DRF browsable API

### ISSUE THREAD

**Issue by blueyed** [yourlabs/django-autocomplete-light#984]
I think it would be nice to have a recipe and/or helper to use DAL with Django REST Frameworks' browsable API.
Is there something in this regard already?

Ref: http://www.django-rest-framework.org/topics/browsable-api/#autocomplete

**Comment by jpic** [comment]
I was wondering about this one time, but at the end just using the right autocomplete widget with the right autocomplete url name in the drf filter form worked without any hack.

**Comment by blueyed** [comment]
@jpic 
Sounds good.
Can you share the recipe/snippet?

But be worth to add it to docs, and then link from DRF's docs to it.

**Comment by jpic** [comment]
Sure:

```
class PostViewSet(viewsets.ModelViewSet):
    filter_class = PostFilter
    filter_backends = (filters.OrderingFilter, DjangoFilterBackend,)

class PostFilter(FilterSet):
    poster = django_filters.ModelMultipleChoiceFilter(queryset=Poster.objects.all(), widget=autocomplete.ModelSelect2Multiple(url='posts:poster_autocomplete'))
```

**Comment by jpic** [comment]
But do you have this issue ? https://github.com/encode/django-rest-framework/issues/5079
